#!/bin/bash

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
NCCL_XPYD_SCRIPT=$SCRIPT_DIR/disagg_example_p2p_nccl_xpyd.sh

PREFILL_GPUS=0 DECODE_GPUS=1 PREFILL_PORTS=20003 DECODE_PORTS=20005 \
MODEL=Qwen/Qwen3-1.7B \
ASYNC_TRANSFER=true \
NCCL_DEBUG=WARN \
NCCL_DEBUG_SUBSYS=ALL \
NCCL_P2P_DISABLE=1 \
NCCL_SHM_DISABLE=1 \
NCCL_IB_DISABLE=1 \
NCCL_NET_GDR_LEVEL=0 \
VLLM_LOGGING_LEVEL=INFO \
PATH=/usr/local/nvidia/bin:$PATH \
bash $NCCL_XPYD_SCRIPT