// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright contributors to the vLLM project

//! Incremental detokenization for the streaming derender endpoints.
//!
//! Ports `vllm/tokenizers/detokenizer_utils.py::detokenize_incrementally`
//! onto the caller-supplied, JSON-serializable [`DerenderStreamState`].
//!
//! The Rust [`Tokenizer`] trait has no `convert_ids_to_tokens` /
//! `convert_tokens_to_string` pair; token pieces come from `id_to_token`
//! (with special/OOV ids mapped to `""` exactly like Python's
//! `_replace_none_with_empty`), and `convert_tokens_to_string(pieces)` is
//! approximated by mapping the pieces back to ids via `token_to_id` and
//! running a single `decode(ids, false)` over them.

use thiserror_ext::AsReport as _;
use vllm_text::tokenizer::DynTokenizer;

use super::types::DerenderStreamState;
use crate::error::{ApiError, server_error};

/// Convert one token id into the raw token piece carried in the decode
/// window.
///
/// Out-of-vocab ids and (when `skip_special_tokens`) special tokens map to
/// `""`, matching Python's `convert_ids_to_tokens` + `_replace_none_with_empty`
/// behavior.
fn token_piece(tokenizer: &DynTokenizer, token_id: u32, skip_special_tokens: bool) -> String {
    if token_id as usize >= tokenizer.vocab_size() {
        return String::new();
    }
    if skip_special_tokens && tokenizer.is_special_id(token_id) {
        return String::new();
    }
    tokenizer.id_to_token(token_id).unwrap_or_default()
}

/// Approximate `convert_tokens_to_string(pieces)`: round-trip the pieces
/// through `token_to_id` and decode them in one shot.
pub(super) fn pieces_to_text(
    tokenizer: &DynTokenizer,
    pieces: &[String],
) -> Result<String, ApiError> {
    let ids: Vec<u32> = pieces.iter().filter_map(|piece| tokenizer.token_to_id(piece)).collect();
    tokenizer
        .decode(&ids, false)
        .map_err(|error| server_error!("derender detokenization failed: {}", error.as_report()))
}

/// Slice `text` to the characters after the first `prefix_chars`, mirroring
/// Python's `new_text[len(prefix_text):]` (which slices by code point).
fn drop_prefix_chars(text: &str, prefix_chars: usize) -> String {
    text.chars().skip(prefix_chars).collect()
}

/// Outcome of feeding one new token into the incremental decode window.
struct IncrementalStep {
    /// The raw piece appended to the window (`""` for skipped/OOV tokens).
    new_piece: String,
    /// Newly visible text, or `""` when the tail is an unfinished multi-byte
    /// sequence.
    text: String,
    prefix_offset: usize,
    read_offset: usize,
}

/// Port of `detokenize_incrementally` for a single new token id.
///
/// `prev_tokens` is always a (possibly empty) list here, so this only
/// implements the non-first-iteration path from Python.
///
/// The offsets are necessary to defeat cleanup algorithms in the decode which
/// decide to add a space or not depending on the surrounding ids.
fn detokenize_incrementally(
    tokenizer: &DynTokenizer,
    new_token_id: u32,
    prev_tokens: &[String],
    prefix_offset: usize,
    read_offset: usize,
    skip_special_tokens: bool,
) -> Result<IncrementalStep, ApiError> {
    let new_piece = token_piece(tokenizer, new_token_id, skip_special_tokens);

    // The prefix text is necessary only to defeat cleanup algorithms in
    // the decode which decide to add a space or not depending on the
    // surrounding ids.
    let prefix_text = pieces_to_text(tokenizer, &prev_tokens[prefix_offset..read_offset])?;
    let new_text = {
        let mut window: Vec<&str> =
            prev_tokens[prefix_offset..].iter().map(String::as_str).collect();
        window.push(&new_piece);
        let ids: Vec<u32> =
            window.iter().filter_map(|piece| tokenizer.token_to_id(piece)).collect();
        tokenizer.decode(&ids, false).map_err(|error| {
            server_error!("derender detokenization failed: {}", error.as_report())
        })?
    };

    let prefix_chars = prefix_text.chars().count();
    // A trailing U+FFFD char means it's a potential unfinished byte sequence
    // from byte fallback tokenization. If it's in the middle, it's probably a
    // real invalid id generated by the model.
    if new_text.chars().count() <= prefix_chars || new_text.ends_with('\u{FFFD}') {
        return Ok(IncrementalStep {
            new_piece,
            text: String::new(),
            prefix_offset,
            read_offset,
        });
    }

    Ok(IncrementalStep {
        new_piece,
        text: drop_prefix_chars(&new_text, prefix_chars),
        prefix_offset: read_offset,
        read_offset: prev_tokens.len() + 1,
    })
}

/// Incrementally detokenize `delta_token_ids` from prior stream state.
///
/// Resumes decoding from the offsets carried in `state` rather than
/// replaying token history. `state.prev_tokens` holds the trailing decode
/// window (from `prefix_offset` onward) that `detokenize_incrementally`
/// still needs to reproduce any partially read multi-byte character
/// (tracked by `read_offset`). The delta tokens are fed straight onto it.
///
/// The window is bounded. `detokenize_incrementally` never reads before
/// `prefix_offset`, so after processing we trim `prev_tokens` to that
/// tail and rebase the offsets to it. State transport therefore stays
/// O(window) per chunk instead of re-sending the full token history.
///
/// Returns `(new_text, updated_state)` — the delta text for this chunk and
/// the state to pass to the next call.
pub(super) fn detokenize_delta(
    tokenizer: &DynTokenizer,
    delta_token_ids: &[u32],
    state: &DerenderStreamState,
    skip_special_tokens: bool,
) -> Result<(String, DerenderStreamState), ApiError> {
    let mut prev_tokens = state.prev_tokens.clone();
    let mut prefix_offset = state.prefix_offset;
    let mut read_offset = state.read_offset;

    let mut text = String::new();
    for &token_id in delta_token_ids {
        let step = detokenize_incrementally(
            tokenizer,
            token_id,
            &prev_tokens,
            prefix_offset,
            read_offset,
            skip_special_tokens,
        )?;
        prev_tokens.push(step.new_piece);
        text.push_str(&step.text);
        prefix_offset = step.prefix_offset;
        read_offset = step.read_offset;
    }

    // Trim to the tail still readable by detokenize_incrementally
    // (everything before prefix_offset is dead) and rebase the offsets so
    // the carried window stays bounded regardless of generation length.
    let trimmed = prev_tokens.split_off(prefix_offset);
    let mut updated_state = state.clone();
    updated_state.prev_tokens = trimmed;
    updated_state.prefix_offset = 0;
    updated_state.read_offset = read_offset - prefix_offset;
    Ok((text, updated_state))
}
