// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright contributors to the vLLM project

use super::types::{ResponseToolChoice, ResponsesRequest};
use crate::error::{ApiError, bail_invalid_request};

/// Enforce the compatibility contract of the Rust Responses API frontend.
///
/// Store-dependent features are rejected because the Rust frontend has no
/// response store (the Python frontend gates them behind
/// `VLLM_ENABLE_RESPONSES_API_STORE=1`):
/// - `store=true` requests still execute, matching the Python frontend's
///   implicit downgrade when the store is disabled; only the combination
///   with `background=true` is rejected.
/// - `previous_response_id` cannot be resolved without a store, and is
///   rejected with a 404 like an unknown response ID would be.
///
/// HTTP status and `param` match Python; the body retains the Rust frontend's
/// string error codes rather than Python's numeric HTTP codes.
pub(super) fn validate_request_compat(request: &ResponsesRequest) -> Result<(), ApiError> {
    if request.background.unwrap_or(false) {
        bail_invalid_request!(
            param = "background",
            "background=true requires the Responses API store, which is not \
             supported by this frontend."
        );
    }

    if request.previous_response_id.is_some() {
        return Err(ApiError::response_not_found(
            request.previous_response_id.clone().unwrap_or_default(),
        ));
    }

    if request
        .previous_input_messages
        .as_ref()
        .is_some_and(|messages| !messages.is_empty())
    {
        bail_invalid_request!(
            param = "previous_input_messages",
            "previous_input_messages requires Harmony rendering, which is not supported by this frontend."
        );
    }

    if request.prompt.is_some() {
        bail_invalid_request!(param = "prompt", "prompt template is not supported");
    }

    if let Some(ResponseToolChoice::Mode(mode)) = &request.tool_choice
        && !matches!(mode.as_str(), "none" | "auto" | "required")
    {
        bail_invalid_request!(
            param = "tool_choice",
            "tool_choice string form must be one of 'none', 'auto', or 'required'; \
             got '{mode}'."
        );
    }

    if let Some(truncation) = &request.truncation
        && !matches!(truncation.as_str(), "auto" | "disabled")
    {
        bail_invalid_request!(
            param = "truncation",
            "truncation must be 'auto' or 'disabled'; got '{truncation}'."
        );
    }

    if request.max_tool_calls.is_some() {
        bail_invalid_request!(
            param = "max_tool_calls",
            "max_tool_calls is not supported by this frontend."
        );
    }

    if let Some(metadata) = &request.metadata
        && (metadata.len() > 16
            || metadata
                .iter()
                .any(|(key, value)| key.chars().count() > 64 || value.chars().count() > 512))
    {
        bail_invalid_request!(
            param = "metadata",
            "metadata supports at most 16 pairs, with keys up to 64 characters and values up to 512 characters"
        );
    }

    if let Some(tier) = request.service_tier.as_deref()
        && !matches!(tier, "auto" | "default" | "flex" | "scale" | "priority")
    {
        bail_invalid_request!(param = "service_tier", "unknown service_tier '{tier}'");
    }

    if let Some(include) = &request.include
        && include.iter().any(|field| field != "reasoning.encrypted_content")
    {
        // TODO: Support output logprobs. Encrypted reasoning is an accepted
        // no-op for Codex, which also replays plaintext reasoning items.
        bail_invalid_request!(
            param = "include",
            "only reasoning.encrypted_content is accepted; encrypted reasoning is not generated by this frontend"
        );
    }

    if request.top_logprobs.is_some_and(|count| count != 0) {
        bail_invalid_request!(
            param = "top_logprobs",
            "output logprobs are not supported by this frontend"
        );
    }

    if let Some(summary) =
        request.reasoning.as_ref().and_then(|reasoning| reasoning.summary.as_deref())
        && !matches!(summary, "auto" | "concise" | "detailed")
    {
        bail_invalid_request!(
            param = "reasoning.summary",
            "unknown reasoning.summary '{summary}'"
        );
    }

    if let Some(verbosity) = request.text.as_ref().and_then(|text| text.verbosity.as_deref())
        && !matches!(verbosity, "low" | "medium" | "high")
    {
        bail_invalid_request!(
            param = "text.verbosity",
            "unknown text.verbosity '{verbosity}'"
        );
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;
    fn base_request() -> ResponsesRequest {
        serde_json::from_value(json!({
            "model": "test-model",
            "input": "hello",
        }))
        .unwrap()
    }

    #[test]
    fn background_true_is_rejected() {
        let mut request = base_request();
        request.background = Some(true);
        let error = validate_request_compat(&request).unwrap_err();
        assert!(matches!(error, ApiError::InvalidRequest { .. }));
    }

    #[test]
    fn previous_response_id_is_rejected_with_not_found() {
        let mut request = base_request();
        request.previous_response_id = Some("resp_missing".to_string());
        let error = validate_request_compat(&request).unwrap_err();
        assert!(matches!(error, ApiError::ResponseNotFound { .. }));
        assert_eq!(error.status_code(), axum::http::StatusCode::NOT_FOUND);
    }

    #[test]
    fn store_true_without_background_is_accepted() {
        let mut request = base_request();
        request.store = Some(true);
        assert!(validate_request_compat(&request).is_ok());
    }

    #[test]
    fn prompt_template_is_rejected() {
        let mut request = base_request();
        request.prompt = Some(json!({"id": "ptmpl"}));
        let error = validate_request_compat(&request).unwrap_err();
        assert!(matches!(error, ApiError::InvalidRequest { .. }));
    }

    #[test]
    fn unknown_tool_choice_mode_is_rejected() {
        let mut request = base_request();
        request.tool_choice = Some(ResponseToolChoice::Mode("sometimes".to_string()));
        let error = validate_request_compat(&request).unwrap_err();
        assert!(matches!(error, ApiError::InvalidRequest { .. }));
    }

    #[test]
    fn unknown_truncation_value_is_rejected() {
        let mut request = base_request();
        request.truncation = Some("maybe".to_string());
        let error = validate_request_compat(&request).unwrap_err();
        assert!(matches!(error, ApiError::InvalidRequest { .. }));
    }

    #[test]
    fn auto_truncation_is_accepted() {
        let mut request = base_request();
        request.truncation = Some("auto".to_string());
        assert!(validate_request_compat(&request).is_ok());
    }

    #[test]
    fn unsupported_history_and_tool_controls_are_rejected() {
        let mut request = base_request();
        request.previous_input_messages = Some(vec![json!({"role": "user", "content": "hi"})]);
        assert!(matches!(
            validate_request_compat(&request),
            Err(ApiError::InvalidRequest { .. })
        ));

        let mut request = base_request();
        request.max_tool_calls = Some(1);
        assert!(matches!(
            validate_request_compat(&request),
            Err(ApiError::InvalidRequest { .. })
        ));
    }

    #[test]
    fn empty_previous_input_messages_are_accepted_as_no_history() {
        let mut request = base_request();
        request.previous_input_messages = Some(vec![]);

        assert!(validate_request_compat(&request).is_ok());
    }

    #[test]
    fn output_presentation_controls_are_accepted_for_compatibility() {
        let request = serde_json::from_value(json!({
            "model": "test-model",
            "input": "hello",
            "include": ["reasoning.encrypted_content"],
            "reasoning": {"summary": "concise"},
            "text": {"verbosity": "low"},
        }))
        .unwrap();
        assert!(validate_request_compat(&request).is_ok());
    }
}
