#!/usr/bin/env bash

usage() {
    echo``
    echo "build 'nm-vllm' in specified python and venv"
    echo
    echo "usage: ${0} <options>"
    echo
    echo "  -p    - python version"
    echo "  -v    - name for virtualenv"
    echo "  -h    - this list of options"
    echo
}

PYPI_IP=
PYTHON=
VENV=

while getopts "hp:v:" OPT; do
    case "${OPT}" in
        h)
            usage
            exit 1
            ;;
        p)
            PYTHON="${OPTARG}"
            ;;
        v)
            VENV="${OPTARG}"
            ;;
    esac
done

# check if variables are valid
if [ -z "${PYTHON}" ]; then
    echo "please provide python version, e.g. 3.10.12"
    usage
    exit 1
fi

if [ -z "${VENV}" ]; then
    echo "please provide python virutalenv name, e.g. TEST"
    usage
    exit 1
fi

source $(pyenv root)/versions/${PYTHON}/envs/${VENV}/bin/activate
pip3 install -r requirements-cuda.txt -r requirements-build.txt
pip3 install -e .
