# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_checkout:
      - git fetch --unshallow || true
    post_install:
      - |
        set -ex
        if [ "$READTHEDOCS_VERSION_TYPE" != "external" ] || ! git diff --quiet origin/main -- \
            docs/ \
            examples/ \
            '*.md' \
            requirements/docs.txt \
            $(python tools/fetch_api_files.py);
        then
          # changes detected, proceed with doc generation
          exit 0;
        fi
        # no changes detected, verify generated docs are up to date
        COMMIT=$(git rev-parse HEAD)
        # generate docs on current branch
        python docs/mkdocs/hooks/generate_argparse.py
        python docs/mkdocs/hooks/generate_metrics.py
        rm -rf /tmp/generated
        mkdir -p /tmp/generated
        mv docs/generated /tmp/generated/current
        # go back to last commit
        git checkout HEAD~
        python docs/mkdocs/hooks/generate_argparse.py
        python docs/mkdocs/hooks/generate_metrics.py
        mv docs/generated /tmp/generated/last
        if diff -r /tmp/generated/last /tmp/generated/current; then
          echo "Generated docs are up to date, skipping update."
          exit 183
        fi
        rm -rf /tmp/generated/
        git checkout $COMMIT --force

mkdocs:
  configuration: mkdocs.yaml
  fail_on_warning: true

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - requirements: requirements/docs.txt
