# The vLLM Dockerfile is used to construct vLLM image that can be directly used
# to run the OpenAI compatible server.

FROM ubuntu:22.04 AS dev

RUN apt-get update -y && \
    apt-get install -y \
        git python3-pip \
        ffmpeg libsm6 libxext6 libgl1
WORKDIR /workspace

COPY . .
ARG GIT_REPO_CHECK=0
RUN --mount=type=bind,source=.git,target=.git \
    if [ "$GIT_REPO_CHECK" != 0 ]; then bash tools/check_repo.sh ; fi

COPY . /workspace/vllm

# build vLLM with OpenVINO backend
RUN --mount=type=cache,target=/root/.cache/pip \
    VLLM_TARGET_DEVICE="openvino" \
    python3 -m pip install -v /workspace/vllm/

COPY examples/ /workspace/examples
COPY benchmarks/ /workspace/benchmarks

# install development dependencies (for testing)
RUN python3 -m pip install -e tests/vllm_test_utils

CMD ["/bin/bash"]
