#!/usr/bin/env bash
set -euo pipefail

# Manual router bring-up extracted from:
# pd_tp_dep_mooncake_offload_nixl_400G_producer_random_python_bench.yaml

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

ROUTER_REPO="${ROUTER_REPO:-/home/${USER}/router}"
HOST="${HOST:-0.0.0.0}"
ROUTER_PORT="${ROUTER_PORT:-8100}"
PROMETHEUS_PORT="${PROMETHEUS_PORT:-29000}"
POLICY="${POLICY:-round_robin}"
LOG_LEVEL="${LOG_LEVEL:-info}"
INTRA_NODE_DATA_PARALLEL_SIZE="${INTRA_NODE_DATA_PARALLEL_SIZE:-1}"

if [[ -z "${LOG_DIR:-}" ]]; then
  latest_log_dir="$(find "${SCRIPT_DIR}/logs" -maxdepth 1 -type d -name 'kimi-1p1d_*' 2>/dev/null | sort | tail -n 1 || true)"
  LOG_DIR="${latest_log_dir:-}"
fi

if [[ -n "${LOG_DIR}" && -f "${LOG_DIR}/nodes.env" ]]; then
  # nodes.env is generated by launch_1p1d_slurm.sh and contains simple KEY=VALUE
  # endpoint assignments for the current allocation.
  set -a
  # shellcheck disable=SC1091
  source "${LOG_DIR}/nodes.env"
  set +a
fi

split_urls() {
  local value=$1
  local -n out=$2
  local item
  IFS=',' read -r -a out <<< "${value}"
  for i in "${!out[@]}"; do
    item="${out[$i]}"
    item="${item#"${item%%[![:space:]]*}"}"
    item="${item%"${item##*[![:space:]]}"}"
    out[$i]="${item}"
  done
}

prefill_urls=()
decode_urls=()

if [[ -n "${PREFILL_URLS:-}" ]]; then
  split_urls "${PREFILL_URLS}" prefill_urls
elif [[ -n "${PREFILL_URL:-}" ]]; then
  prefill_urls=("${PREFILL_URL}")
fi

if [[ -n "${DECODE_URLS:-}" ]]; then
  split_urls "${DECODE_URLS}" decode_urls
else
  if [[ -n "${DECODE_URL_0:-}" ]]; then
    decode_urls+=("${DECODE_URL_0}")
  fi
  if [[ -n "${DECODE_URL_1:-}" ]]; then
    decode_urls+=("${DECODE_URL_1}")
  fi
fi

if (( ${#prefill_urls[@]} == 0 )); then
  echo "No prefill URL found. Set PREFILL_URLS or LOG_DIR pointing to nodes.env." >&2
  exit 1
fi
if (( ${#decode_urls[@]} == 0 )); then
  echo "No decode URL found. Set DECODE_URLS or LOG_DIR pointing to nodes.env." >&2
  exit 1
fi

prefill_args=()
for url in "${prefill_urls[@]}"; do
  [[ -n "${url}" ]] && prefill_args+=(--prefill "${url}")
done

decode_args=()
for url in "${decode_urls[@]}"; do
  [[ -n "${url}" ]] && decode_args+=(--decode "${url}")
done

if [[ -x "${ROUTER_REPO}/target/release/vllm-router" && "${ROUTER_USE_CARGO:-0}" != "1" ]]; then
  router_cmd=("${ROUTER_REPO}/target/release/vllm-router")
else
  router_cmd=(cargo run --release --)
fi

echo "=== 1P/1D router ==="
echo "Repo:            ${ROUTER_REPO}"
echo "Host:            ${HOST}"
echo "Port:            ${ROUTER_PORT}"
echo "Prometheus port: ${PROMETHEUS_PORT}"
echo "Policy:          ${POLICY}"
echo "Prefill URLs:    ${prefill_urls[*]}"
echo "Decode URLs:     ${decode_urls[*]}"
echo "Started:         $(date -Iseconds)"
echo "==================="

cd "${ROUTER_REPO}"

exec "${router_cmd[@]}" \
  --policy "${POLICY}" \
  --log-level "${LOG_LEVEL}" \
  --prometheus-port "${PROMETHEUS_PORT}" \
  --host "${HOST}" \
  --port "${ROUTER_PORT}" \
  --vllm-pd-disaggregation \
  --intra-node-data-parallel-size "${INTRA_NODE_DATA_PARALLEL_SIZE}" \
  "${prefill_args[@]}" \
  "${decode_args[@]}" \
  "$@"
