# SPDX-License-Identifier: Apache-2.0
"""Train a DFlash2 drafter against a REAP-pruned target on Modal.

    modal run inco/modal/modal_speculators.py

Runs the *offline* pipeline -- server up, regenerate responses, prepare data,
extract hidden states, server down, train -- which is what lets one container
do the whole run on a single GPU: the vLLM server and the trainer never need
it at the same time.

Two Python environments, because they cannot be reconciled:

  * system python  -- this fork's vLLM, which supplies the
    `extract_hidden_states` speculative method and
    `ExampleHiddenStatesConnector`.
  * `/opt/spec`    -- speculators, which pins `transformers>=5.0` and
    `torch>=2.9`; installing it over the fork would replace the engine.

They communicate over HTTP on localhost, exactly as the upstream
`examples/train/*.sh` scripts do. `docs/user_guide/tutorials/train.md`
recommends separate venvs for the same reason.

Training data is on-policy: `regenerate-responses` re-answers every prompt
with *this* checkpoint, so the draft learns the pruned model's own output
distribution rather than some other model's. `docs/user_guide/tutorials/
train.md:107` requires that; the `tutorial_regen` dataset the upstream examples
use was generated by Qwen3-8B and is wrong for this target.

Prompts come from `evol-codealpaca-v1`, the corpus REAP was calibrated on, so
the drafter is trained on the distribution the retained experts are strongest
at. `--skip-regen` falls back to an off-policy preset, which is a pipeline
check rather than a usable drafter -- see the 64-sample smoke result in
EXPERIMENTS.md.
"""

from __future__ import annotations

import json
import os
import random
import re
import subprocess
import sys
import time
import urllib.request
from concurrent.futures import ThreadPoolExecutor

import modal

GPU = os.environ.get("INCO_SPEC_GPU", "H100")
TIMEOUT_S = int(os.environ.get("INCO_SPEC_TIMEOUT", 6 * 60 * 60))
CUDA_VARIANT = os.environ.get("INCO_CUDA_VARIANT", "cu130")

LOCAL = modal.is_local()
REMOTE_REPO = "/workspace/vllm"
REMOTE_SPEC = "/workspace/speculators"
SPEC_PY = "/opt/spec/bin/python"
SPEC_CLI = "/opt/spec/bin/speculators"

REPO_ROOT = (
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    if LOCAL
    else REMOTE_REPO
)
LOCAL_SPEC = os.path.join(REPO_ROOT, "inco", "speculators")

# The 1024-sample REAP 50% checkpoint written by modal_reap.py.
PRUNED = (
    "/reap/pruned/Qwen3-30B-A3B-Instruct-2507/evol-codealpaca-v1"
    "/pruned_models/layerwise_reap-renorm_true-seed_42-0.50"
)

# REAP's own calibration corpus, reused as the regeneration prompt set.
CODE_PROMPTS = "theblackcat102/evol-codealpaca-v1"

# Run under /opt/spec (`datasets` lives there, not in the engine env). Emits the
# {"prompt": ...} rows that regenerate-responses expects from a local file:
# `load_input_dataset` gives an unregistered dataset `prompt_field="prompt"`.
PROMPT_EXTRACT = """
import json, sys
from datasets import load_dataset

hf_path, field, limit, outfile = sys.argv[1], sys.argv[2], int(sys.argv[3]), sys.argv[4]
if hf_path.endswith((".json", ".jsonl")):
    rows = load_dataset("json", data_files=hf_path, split="train", streaming=True)
else:
    rows = load_dataset(hf_path, split="train", streaming=True)
# Shuffled because the file order of these corpora tracks their source subsets,
# and taking the first N would sample one of them rather than the corpus.
rows = rows.shuffle(seed=42, buffer_size=10_000)

written = 0
with open(outfile, "w") as fh:
    for row in rows:
        prompt = (row.get(field) or "").strip()
        if not prompt:
            continue
        fh.write(json.dumps({"prompt": prompt}, ensure_ascii=False) + "\\n")
        written += 1
        if written >= limit:
            break

print(f"wrote {written} prompts to {outfile}")
if written < limit:
    raise SystemExit(f"only {written} of {limit} prompts available in {hf_path}")
"""

app = modal.App("inco-speculators")

HF_SECRETS = (
    [modal.Secret.from_dict({"HF_TOKEN": os.environ["HF_TOKEN"]})]
    if LOCAL and os.environ.get("HF_TOKEN")
    else []
)


def _git(*args: str) -> str:
    return subprocess.check_output(["git", "-C", REPO_ROOT, *args], text=True).strip()


def _fork_build_env() -> dict[str, str]:
    """Pin the precompiled wheel, as modal_baseline.py does. See its docstring."""
    base = _git("merge-base", "HEAD", "origin/main")
    meta = f"https://wheels.vllm.ai/{base}/{CUDA_VARIANT}/vllm/metadata.json"
    try:
        with urllib.request.urlopen(meta, timeout=30) as resp:
            version = json.loads(resp.read())[0]["version"]
    except Exception as exc:
        raise RuntimeError(f"no {CUDA_VARIANT} wheel for base {base}: {exc}") from exc
    print(f"[modal] precompiled {CUDA_VARIANT} wheel {version} (base {base[:9]})")
    return {
        "VLLM_PRECOMPILED_WHEEL_COMMIT": base,
        "VLLM_MAIN_CUDA_VERSION": CUDA_VARIANT.removeprefix("cu")[:2] + ".0",
        "SETUPTOOLS_SCM_PRETEND_VERSION": version,
    }


FORK_BUILD_ENV = _fork_build_env() if LOCAL else {}

hf_cache = modal.Volume.from_name("inco-hf-cache", create_if_missing=True)
vllm_cache = modal.Volume.from_name("inco-vllm-cache", create_if_missing=True)
reap_models = modal.Volume.from_name("inco-reap", create_if_missing=True)
spec_out = modal.Volume.from_name("inco-spec", create_if_missing=True)

image = (
    modal.Image.from_registry("nvidia/cuda:13.0.3-devel-ubuntu24.04", add_python="3.12")
    .apt_install("git", "curl")
    .pip_install("uv")
    .env(FORK_BUILD_ENV)
    .add_local_dir(
        REPO_ROOT,
        remote_path=REMOTE_REPO,
        copy=True,
        ignore=[
            ".git",
            ".venv*",
            "inco",
            "**/__pycache__",
            "**/*.pyc",
            "**/*.so",
            ".ruff_cache",
            ".pytest_cache",
            ".mypy_cache",
            ".coverage*",
            "build",
            "dist",
            "*.egg-info",
            "**/*.log",
        ],
    )
    .run_commands(
        f"cd {REMOTE_REPO} && VLLM_USE_PRECOMPILED=1 uv pip install --system -e .",
    )
    # `.git` *is* uploaded here (6MB): speculators' setup.py uses
    # setuptools-git-versioning, which shells out to git for the sha and the
    # commit count. There is no PRETEND_VERSION escape hatch as there is for
    # setuptools-scm, so the metadata has to be present.
    .add_local_dir(
        LOCAL_SPEC,
        remote_path=REMOTE_SPEC,
        copy=True,
        ignore=[".venv*", "**/__pycache__", "**/*.pyc", "docs/assets", "output"],
    )
    .run_commands(
        # Separate interpreter so speculators' torch/transformers pins cannot
        # touch the engine installed above.
        "uv venv /opt/spec --python 3.12",
        # --no-deps then an explicit set, mirroring modal_reap.py: resolving
        # speculators normally drags in the `hs-connectors>0.7.0` constraint,
        # which the local workspace copy (0.7.0.dev) does not satisfy.
        f"cd {REMOTE_SPEC}/hs_connectors && "
        f"uv pip install --python {SPEC_PY} --no-deps -e .",
        f"cd {REMOTE_SPEC} && uv pip install --python {SPEC_PY} --no-deps -e .",
        f"uv pip install --python {SPEC_PY} "
        "aiohttp click 'datasets>=4.0.0,<=5.0.1' httpx huggingface-hub "
        "'loguru>=0.7.2,<=0.7.3' 'numpy>=2.0.0,<=2.4.6' 'openai>=2.0.0' protobuf "
        "psutil 'pydantic>=2.0.0' pydantic-settings rich safetensors "
        "'torch>=2.9.0,<=2.13.0' 'tqdm>=4.66.3,<=4.70.0' "
        "'transformers>=5.0.0,<5.17.0' 'typer>=0.12.0'",
    )
    .env(
        {
            "HF_HOME": "/cache/hf",
            "HF_XET_HIGH_PERFORMANCE": "1",
            "VLLM_CACHE_ROOT": "/cache/vllm",
            "CUDA_HOME": "/usr/local/cuda",
            # /opt/spec/bin must NOT go on PATH: Modal resolves the
            # function's own interpreter from it, so the function would run
            # inside the speculators venv and `sys.executable` -- which
            # launch_vllm.py uses to spawn the engine -- would have no vLLM.
            # Both speculators binaries are invoked by absolute path.
            "PATH": "/usr/local/cuda/bin:/usr/local/bin:/usr/bin:/bin",
            "FLASHINFER_WORKSPACE_BASE": "/cache/vllm/flashinfer",
            "FLASHINFER_CACHE_DIR": "/cache/vllm/flashinfer/jit",
            "TOKENIZERS_PARALLELISM": "false",
        }
    )
)


def _stream(cmd: list[str], *, cwd: str, label: str, env: dict | None = None) -> int:
    """Run a step, prefixing each line with elapsed minutes."""
    print(f"\n=== {label} ===\n$ {' '.join(cmd)}", flush=True)
    started = time.monotonic()
    proc = subprocess.Popen(
        cmd,
        cwd=cwd,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        text=True,
        bufsize=1,
        env={**os.environ, "PYTHONUNBUFFERED": "1", **(env or {})},
    )
    for line in proc.stdout:
        elapsed = (time.monotonic() - started) / 60
        print(f"[{elapsed:5.1f}m] {line.rstrip()}", flush=True)
    rc = proc.wait()
    print(f"[{label}] rc={rc}", flush=True)
    return rc


def _wait_health(url: str, proc: subprocess.Popen, timeout_s: float) -> None:
    """Poll /health, aborting the moment the server process dies."""
    deadline = time.monotonic() + timeout_s
    while time.monotonic() < deadline:
        if proc.poll() is not None:
            raise RuntimeError(f"vLLM server exited early with rc={proc.returncode}")
        try:
            with urllib.request.urlopen(f"{url}/health", timeout=5) as resp:
                if resp.status == 200:
                    print("[server] ready", flush=True)
                    return
        except Exception:
            pass
        time.sleep(5)
    raise TimeoutError(f"server not ready within {timeout_s}s")


def _train_and_report(
    out, hidden, model, label, layer_ids, steps,
    epochs, lr, seq_length, block_size, max_anchors, num_layers,
) -> str:
    """Step 5 plus the run summary. Shared by the full run and --train-only."""
    # Step 5 -- train the draft on the freed GPU.
    steps.append(
        (
            "train",
            _stream(
                [
                    "/opt/spec/bin/torchrun",
                    "--standalone", "--nproc_per_node", "1",
                    "-m", "speculators.train",
                    "--verifier-name-or-path", model,
                    # --data-path is the *prepare-data* output (an Arrow
                    # dataset); the hidden states are a separate tree.
                    "--data-path", out,
                    "--hidden-states-path", hidden,
                    "--save-path", f"{out}/checkpoints",
                    "--on-missing", "raise",
                    "--epochs", str(epochs),
                    "--lr", str(lr),
                    "--total-seq-len", str(seq_length),
                    "--speculator-type", "dflash2",
                    "--block-size", str(block_size),
                    "--max-anchors", str(max_anchors),
                    "--num-layers", str(num_layers),
                    "--target-layer-ids", *layer_ids,
                ],
                cwd=REMOTE_SPEC,
                label="Step 5: train dflash2",
            ),
        )
    )

    spec_out.commit()
    hf_cache.commit()

    found = subprocess.run(
        ["find", f"{out}/checkpoints", "-maxdepth", "3"],
        capture_output=True, text=True,
    ).stdout.strip()
    summary = "\n".join(f"  {name:24} rc={rc}" for name, rc in steps)
    return (
        f"target: {model}\naux layers: {layer_ids}\n\n{summary}\n\n"
        f"checkpoints:\n{found or '  (none)'}\n\n"
        f"pull with: modal volume get inco-spec {label} ./inco/results/spec"
    )




@app.function(
    image=image,
    gpu=GPU,
    timeout=TIMEOUT_S,
    volumes={
        "/cache/hf": hf_cache,
        "/cache/vllm": vllm_cache,
        "/reap": reap_models,
        "/spec": spec_out,
    },
    secrets=HF_SECRETS,
)
def pipeline(
    model: str = PRUNED,
    label: str = "dflash2-reap50-code-5k",
    # Off-policy fallback, used only under --skip-regen: a prepare-data preset
    # name, an `hf:` spec, or a path.
    dataset: str = "ultrachat",
    # On-policy prompt source: an HF dataset id, or a local .jsonl whose rows
    # already carry a "prompt" field (then --prompt-field is ignored).
    prompt_dataset: str = CODE_PROMPTS,
    prompt_field: str = "instruction",
    # 5000 samples / 5 epochs is the upstream dflash2 recipe
    # (examples/train/dflash2_qwen3_8b_ultrachat_online_5k.sh).
    max_samples: int = 5000,
    seq_length: int = 2048,
    epochs: int = 5,
    lr: float = 3e-4,
    block_size: int = 8,
    max_anchors: int = 512,
    num_layers: int = 5,
    # 48-layer analogue of the example's "2 18 33" for Qwen3-8B's 36 layers.
    # Must match what launch_vllm.py bakes into eagle_aux_hidden_state_layer_ids.
    target_layer_ids: str = "2 24 45",
    concurrency: int = 16,
    # Regeneration is plain decoding against the target, so it runs much wider
    # than hidden-state extraction. 1024 output tokens covers the 512-token
    # serving shape with headroom for the target to run long.
    regen_concurrency: int = 64,
    regen_max_tokens: int = 1024,
    # Must exceed seq_length. prepare-data renders with
    # truncate_prompt_tokens=seq_length, and vLLM's render endpoint budgets
    # max_tokens = max_model_len - input_length. Set them equal and every
    # conversation that reaches the truncation limit renders a budget of 0,
    # which SamplingParams rejects -- a silent per-conversation data drop.
    max_model_len: int = 0,  # 0 -> 2 * seq_length
    gpu_memory_utilization: float = 0.85,
    port: int = 8000,
    # Reuse prepare-data/hidden-states already on the volume and go
    # straight to step 5. Saves re-serving the target.
    train_only: bool = False,
    # Train on an off-policy preset instead of this checkpoint's own outputs.
    skip_regen: bool = False,
) -> str:
    out = f"/spec/{label}"
    hidden = f"{out}/hidden_states"
    os.makedirs(out, exist_ok=True)
    layer_ids = target_layer_ids.split()
    max_model_len = max_model_len or 2 * seq_length
    endpoint = f"http://localhost:{port}"
    prompts = f"{out}/prompts.jsonl"
    regen = f"{out}/regen.jsonl"
    # regenerate-responses writes boundary rows (input_ids + loss_mask), which
    # prepare-data passes through instead of re-rendering.
    train_data = dataset if skip_regen else regen

    # Fail loudly here rather than 20 minutes into a server start.
    import importlib.util

    if importlib.util.find_spec("vllm") is None:
        raise RuntimeError(
            f"this function must run under the fork's interpreter, but "
            f"sys.executable={sys.executable} has no vllm"
        )
    print(f"[spec] engine python: {sys.executable}", flush=True)
    print(f"[spec] target={model}\n[spec] out={out}", flush=True)

    steps: list[tuple[str, int]] = []
    if train_only:
        print("[spec] train_only: reusing existing data on the volume", flush=True)
        return _train_and_report(
            out, hidden, model, label, layer_ids, steps,
            epochs, lr, seq_length, block_size, max_anchors, num_layers,
        )

    # Step 0 -- the prompt set. Ahead of the server because a wrong dataset id
    # or field name should cost seconds, not a 5-minute weight load.
    if not skip_regen:
        rc = _stream(
            [SPEC_PY, "-c", PROMPT_EXTRACT, prompt_dataset, prompt_field,
             str(max_samples), prompts],
            cwd=REMOTE_SPEC,
            label="Step 0: extract prompts",
        )
        steps.append(("prompts", rc))
        if rc != 0:
            raise RuntimeError(f"prompt extraction failed, rc={rc}")

    # Step 1 -- vLLM server, under the *fork's* interpreter.
    # Not a context manager: the handle has to outlive this statement and is
    # closed in the finally below, once the server is down.
    server_log = open(f"{out}/server.log", "w")  # noqa: SIM115
    server = subprocess.Popen(
        [
            sys.executable,
            f"{REMOTE_SPEC}/scripts/launch_vllm.py",
            model,
            "--target-layer-ids",
            *layer_ids,
            "--hidden-states-path",
            hidden,
            "--",
            "--port",
            str(port),
            "--gpu-memory-utilization",
            str(gpu_memory_utilization),
            "--max-model-len",
            str(max_model_len),
        ],
        cwd=REMOTE_SPEC,
        stdout=server_log,
        stderr=subprocess.STDOUT,
        env={**os.environ, "PYTHONUNBUFFERED": "1"},
    )

    try:
        _wait_health(endpoint, server, timeout_s=1800)

        # Step 1b -- on-policy responses from the target itself. Failing hard
        # here matters: without it prepare-data would silently fall through to
        # whatever `dataset` points at and train the draft on the wrong
        # distribution. --resume lets an interrupted file be continued.
        if not skip_regen:
            rc = _stream(
                [
                    SPEC_CLI, "regenerate-responses",
                    "--endpoint", f"{endpoint}/v1/chat/completions",
                    # Doubles as the tokenizer path for the review-only `text`
                    # twin, so it must be the checkpoint, not a served alias.
                    "--model", model,
                    "--dataset", prompts,
                    "--limit", str(max_samples),
                    "--concurrency", str(regen_concurrency),
                    "--max-tokens", str(regen_max_tokens),
                    "--outfile", regen,
                    "--resume",
                    "--seed", "42",
                    # Qwen3 non-thinking defaults, from the model card.
                    "--sampling-params",
                    json.dumps({"temperature": 0.7, "top_p": 0.8, "top_k": 20}),
                ],
                cwd=REMOTE_SPEC,
                label="Step 1b: regenerate-responses",
            )
            steps.append(("regenerate", rc))
            if rc != 0:
                raise RuntimeError(f"regeneration failed, rc={rc}")

        # Step 2 -- to speculator format. Regenerated rows arrive as
        # input_ids + loss_mask and pass straight through; an off-policy
        # preset is rendered through the target's chat template instead.
        steps.append(
            (
                "prepare-data",
                _stream(
                    [
                        SPEC_CLI, "prepare-data",
                        "--model", model,
                        "--data", train_data,
                        "--render-endpoint", endpoint,
                        "--max-samples", str(max_samples),
                        "--output", out,
                        "--seq-length", str(seq_length),
                    ],
                    cwd=REMOTE_SPEC,
                    label="Step 2: prepare-data",
                ),
            )
        )

        # Step 3 -- the part that actually exercises the pruned target: aux
        # hidden states at layers 2/24/45 pulled out through the connector.
        steps.append(
            (
                "generate-offline-data",
                _stream(
                    [
                        SPEC_CLI, "generate-offline-data",
                        "--preprocessed-data", out,
                        "--endpoint", f"{endpoint}/v1",
                        "--output", hidden,
                        "--max-samples", str(max_samples),
                        "--concurrency", str(concurrency),
                        "--validate-outputs",
                    ],
                    cwd=REMOTE_SPEC,
                    label="Step 3: generate-offline-data",
                ),
            )
        )
    finally:
        print("\n=== Step 4: stopping server ===", flush=True)
        server.terminate()
        try:
            server.wait(timeout=120)
        except subprocess.TimeoutExpired:
            server.kill()
        server_log.close()

    return _train_and_report(
        out, hidden, model, label, layer_ids, steps,
        epochs, lr, seq_length, block_size, max_anchors, num_layers,
    )


@app.local_entrypoint()
def main(
    model: str = PRUNED,
    label: str = "dflash2-reap50-code-5k",
    prompt_dataset: str = CODE_PROMPTS,
    prompt_field: str = "instruction",
    max_samples: int = 5000,
    seq_length: int = 2048,
    epochs: int = 5,
    regen_concurrency: int = 64,
    regen_max_tokens: int = 1024,
    train_only: bool = False,
    skip_regen: bool = False,
) -> None:
    print(
        pipeline.remote(
            model=model,
            label=label,
            prompt_dataset=prompt_dataset,
            prompt_field=prompt_field,
            max_samples=max_samples,
            seq_length=seq_length,
            epochs=epochs,
            regen_concurrency=regen_concurrency,
            regen_max_tokens=regen_max_tokens,
            train_only=train_only,
            skip_regen=skip_regen,
        )
    )


# ---------------------------------------------------------------------------
# Serving the trained drafter: acceptance and throughput
# ---------------------------------------------------------------------------

# Epoch 4 of the 5000-sample on-policy run. Validation improved monotonically,
# so this is also `checkpoint_best`.
DRAFTER = "/spec/dflash2-reap50-code-5k/checkpoints/4"

# Short-form code prompt sets, as "<hf id>:<split>:<field>:<limit>". Both
# EvalPlus sets expose the prompt under `prompt`: HumanEval+ as a signature
# plus docstring, MBPP+ as a one-line natural-language instruction.
EVAL_SPECS = "evalplus/humanevalplus:test:prompt:64,evalplus/mbppplus:test:prompt:64"

EVAL_PROMPTS = """
import json, sys
from datasets import load_dataset

outfile = sys.argv[1]
written = 0
with open(outfile, "w") as fh:
    for spec in sys.argv[2:]:
        hf_path, split, field, limit = spec.rsplit(":", 3)
        rows = load_dataset(hf_path, split=split)
        rows = rows.select(range(min(int(limit), len(rows))))
        for row in rows:
            prompt = (row.get(field) or "").strip()
            if not prompt:
                continue
            fh.write(json.dumps({"prompt": prompt, "source": hf_path}) + "\\n")
            written += 1
print(f"wrote {written} prompts to {outfile}")
if written == 0:
    raise SystemExit("no prompts extracted")
"""


def _http_json(url: str, payload: dict | None = None, timeout: float = 900.0) -> dict:
    body = json.dumps(payload).encode() if payload is not None else None
    request = urllib.request.Request(
        url, data=body, headers={"Content-Type": "application/json"}
    )
    with urllib.request.urlopen(request, timeout=timeout) as response:
        raw = response.read()
    return json.loads(raw) if raw else {}


def _spec_counters(base: str) -> dict:
    """Cumulative spec-decode counters off /metrics, summed over engines.

    Counters, not gauges, so a point's numbers are the delta across it. The
    per-position vector is labelled by draft index 0..num_speculative_tokens-1.
    """
    with urllib.request.urlopen(f"{base}/metrics", timeout=30) as response:
        text = response.read().decode()

    named = {
        "vllm:spec_decode_num_drafts_total": "drafts",
        "vllm:spec_decode_num_draft_tokens_total": "draft_tokens",
        "vllm:spec_decode_num_accepted_tokens_total": "accepted",
    }
    totals = {"drafts": 0.0, "draft_tokens": 0.0, "accepted": 0.0}
    per_pos: dict[int, float] = {}
    for line in text.splitlines():
        if not line or line.startswith("#"):
            continue
        name, _, value = line.rpartition(" ")
        try:
            observed = float(value)
        except ValueError:
            continue
        metric = name.split("{", 1)[0]
        if metric in named:
            totals[named[metric]] += observed
        elif metric == "vllm:spec_decode_num_accepted_tokens_per_pos_total":
            position = re.search(r'position="(\d+)"', name)
            if position:
                index = int(position.group(1))
                per_pos[index] = per_pos.get(index, 0.0) + observed
    return {**totals, "per_pos": per_pos}


def _one_request(base: str, model_name: str, prompt: str, max_tokens: int) -> tuple:
    started = time.monotonic()
    data = _http_json(
        f"{base}/v1/chat/completions",
        {
            "model": model_name,
            "messages": [{"role": "user", "content": prompt}],
            "max_tokens": max_tokens,
            # Greedy: spec decode is lossless, so both phases must produce the
            # same tokens. That equality is the integrity check below.
            "temperature": 0.0,
        },
    )
    return time.monotonic() - started, int(data["usage"]["completion_tokens"])


def _measure(
    base: str,
    model_name: str,
    prompts: list[str],
    concurrency: int,
    max_tokens: int,
    *,
    spec: bool,
    waves: int = 8,
    min_requests: int = 24,
    warmup_requests: int = 16,
) -> dict:
    """One concurrency point: throughput, plus the acceptance delta over it.

    Sends ``waves * concurrency`` requests, cycling the prompt pool, which is
    `bench/sweep.py`'s convention. A fixed request count instead makes the
    high-concurrency points a ramp-up and a drain with no steady state in
    between: at 128 prompts and c=64 the drafted phase finished in 8s and two
    runs of the same config disagreed by 46%.
    """
    # Whole multiples of the pool, so every concurrency runs *the same
    # workload*: each prompt appears an equal number of times. aiperf gets this
    # for free from synthetic fixed-shape requests; with real prompts, a bare
    # `waves * concurrency` makes the prompt mix -- and so the mean output
    # length -- a function of concurrency, which is not a thing the engine did.
    # The floor is bench/config.py's; 8 waves is its requests_per_concurrency.
    target = max(min_requests, waves * concurrency)
    pool = len(prompts)
    requested = pool * max(1, -(-target // pool))
    warmup_count = max(warmup_requests, concurrency)
    prompts = [prompts[i % len(prompts)] for i in range(requested)]
    # NOTE: callers must hand this an already-shuffled pool. Taking a prefix of
    # a pool grouped by source makes the workload itself a function of
    # concurrency -- c<=8 drew only HumanEval+ and scored accept_len 4.0-4.3
    # against 3.92 for the mixed points above it.
    warmup = [prompts[i % len(prompts)] for i in range(warmup_count)]
    with ThreadPoolExecutor(max_workers=concurrency) as pool:
        list(pool.map(lambda p: _one_request(base, model_name, p, 32), warmup))
    # Harmless with caching disabled; kept so the point still starts cold if
    # someone turns prefix caching back on.
    _http_json(f"{base}/reset_prefix_cache", {})

    before = _spec_counters(base) if spec else None
    started = time.monotonic()
    with ThreadPoolExecutor(max_workers=concurrency) as pool:
        results = list(
            pool.map(lambda p: _one_request(base, model_name, p, max_tokens), prompts)
        )
    wall = time.monotonic() - started
    after = _spec_counters(base) if spec else None

    tokens = sum(count for _, count in results)
    point = {
        "concurrency": concurrency,
        "requests": len(results),
        "waves": round(len(results) / concurrency, 1),
        "pool_repeats": len(results) // len(set(prompts)),
        "wall_s": round(wall, 2),
        "output_tokens": tokens,
        "tok_s_gpu": round(tokens / wall, 1),
        "tok_s_user": round(sum(n / lat for lat, n in results) / len(results), 1),
        "mean_latency_s": round(sum(lat for lat, _ in results) / len(results), 2),
    }
    if before is not None and after is not None:
        drafts = after["drafts"] - before["drafts"]
        draft_tokens = after["draft_tokens"] - before["draft_tokens"]
        accepted = after["accepted"] - before["accepted"]
        point["drafts"] = int(drafts)
        point["draft_tokens"] = int(draft_tokens)
        point["accepted_tokens"] = int(accepted)
        # vLLM's convention (v1/spec_decode/metrics.py:113): the bonus token
        # counts toward the length, so a drafter that never lands scores 1.0.
        point["accept_len"] = round(1 + accepted / drafts, 3) if drafts else None
        point["accept_rate"] = (
            round(accepted / draft_tokens, 4) if draft_tokens else None
        )
        point["per_pos_rate"] = (
            [
                round(
                    (after["per_pos"].get(i, 0.0) - before["per_pos"].get(i, 0.0))
                    / drafts,
                    3,
                )
                for i in sorted(after["per_pos"])
            ]
            if drafts
            else []
        )
    return point


def _serve_target(
    serve_path: str,
    served_name: str,
    log_path: str,
    *,
    graph_ceiling: int,
    port: int,
    kv_cache_gib: float,
    max_num_seqs: int,
    max_model_len: int,
    gpu_memory_utilization: float,
):
    cmd = [
        sys.executable,
        "-m",
        "vllm.entrypoints.cli.main",
        "serve",
        # For the drafted phase this is the *drafter* checkpoint, not the
        # target: a speculators config makes vLLM swap the served model and
        # tokenizer for its own `verifier.name_or_path` and build the
        # speculative config from the checkpoint
        # (transformers_utils/config.py:740). Passing the target plus
        # --speculative-config instead would need trust_remote_code for the
        # draft's `auto_map`.
        serve_path,
        "--port",
        str(port),
        "--served-model-name",
        served_name,
        "--max-model-len",
        str(max_model_len),
        "--max-num-seqs",
        str(max_num_seqs),
        "--gpu-memory-utilization",
        str(gpu_memory_utilization),
        # Off, not on. The prompt pool repeats 2-6x within a point at high
        # concurrency, so with caching those repeats read their prefills out
        # of the cache and the high-c points score up to ~13% of their token
        # work for free relative to c<=16.
        "--no-enable-prefix-caching",
        # Both phases capture the same range, and it must cover the *drafted*
        # forward pass, which is concurrency x (1 + num_speculative_tokens)
        # rows -- not concurrency. The 512 default (compilation.py:703) is
        # exactly 64 x 8, so without this every point above c=64 silently
        # ran the draft eager while the baseline kept its graphs.
        "--compilation-config",
        json.dumps({"max_cudagraph_capture_size": graph_ceiling}),
        # Pinned off, not merely omitted. `async_scheduling` defaults to None,
        # which resolves to True unless something blocks it -- and
        # `config/vllm.py:1345` blocks it for method="dflash" only. Omitting
        # the flag therefore gives the no-draft phase an async scheduler the
        # drafted phase cannot have, which flatters the baseline.
        "--no-async-scheduling",
        # Pinned, and identical in both phases: Modal's "H100" is either an
        # 80GB HBM3 or a 94GB NVL, and letting KV float would change the
        # servable batch between the two servers being compared.
        "--kv-cache-memory-bytes",
        str(int(kv_cache_gib * 1024**3)),
        "--default-chat-template-kwargs",
        '{"enable_thinking": false}',
    ]
    # Note this makes the numbers incomparable to the reap50-1024-512 sweep,
    # which runs with async scheduling on.

    print(f"[spec] serving: {' '.join(cmd)}", flush=True)
    log = open(log_path, "w")  # noqa: SIM115
    proc = subprocess.Popen(
        cmd,
        stdout=log,
        stderr=subprocess.STDOUT,
        # /reset_prefix_cache and /server_info are dev-mode routes.
        env={**os.environ, "PYTHONUNBUFFERED": "1", "VLLM_SERVER_DEV_MODE": "1"},
    )
    return proc, log


def _server_audit(base: str) -> dict:
    """The few /server_info fields that would invalidate a phase comparison."""
    try:
        info = _http_json(f"{base}/server_info?config_format=json", timeout=60)
    except Exception as exc:  # noqa: BLE001
        return {"error": repr(exc)}
    config = info.get("vllm_config") or {}
    scheduler = config.get("scheduler_config") or {}
    cache = config.get("cache_config") or {}
    speculative = config.get("speculative_config") or {}
    return {
        "async_scheduling": scheduler.get("async_scheduling"),
        "max_num_seqs": scheduler.get("max_num_seqs"),
        "prefix_caching": cache.get("enable_prefix_caching"),
        "num_gpu_blocks": cache.get("num_gpu_blocks"),
        "spec_method": speculative.get("method"),
        "num_speculative_tokens": speculative.get("num_speculative_tokens"),
    }


@app.function(
    image=image,
    gpu=GPU,
    timeout=TIMEOUT_S,
    volumes={
        "/cache/hf": hf_cache,
        "/cache/vllm": vllm_cache,
        "/reap": reap_models,
        "/spec": spec_out,
    },
    secrets=HF_SECRETS,
)
def acceptance(
    model: str = PRUNED,
    drafter: str = DRAFTER,
    label: str = "specdec-reap50-code",
    specs: str = EVAL_SPECS,
    concurrencies: str = "1,2,4,8,16,32,48,64,80,96",
    # Requests per point are waves * concurrency, so this is wall-clock per
    # point rather than a sample size; 8 matches the aiperf sweeps.
    waves: int = 8,
    max_tokens: int = 512,
    kv_cache_gib: float = 32.0,
    # Above the top concurrency on purpose: at concurrency == max_num_seqs the
    # scheduler has zero slack, which cost ~2% in the short-128-128 sweep.
    max_num_seqs: int = 128,
    max_model_len: int = 4096,
    gpu_memory_utilization: float = 0.90,
    port: int = 8000,
    # Must match the checkpoint's speculators_config.proposal_methods[0]; it
    # sets how many rows per request the verify pass carries.
    spec_tokens: int = 7,
    # Measure the drafted phase only. The no-draft phase on the same container
    # is what makes the throughput number mean anything, so this is off.
    skip_baseline: bool = False,
) -> str:
    """Serve the REAP target with and without the drafter; report both."""
    out = f"/spec/{label}"
    os.makedirs(out, exist_ok=True)
    endpoint = f"http://localhost:{port}"
    served_name = "target"
    points = [int(c) for c in concurrencies.split(",") if c.strip()]
    # Sized from what the *scheduler* can produce, not from what the sweep
    # asks for: the batch can reach max_num_seqs requests, each carrying
    # (1 + spec_tokens) rows through the verify pass. Covering that leaves
    # headroom above the top concurrency instead of landing exactly on it,
    # so a queued or warmup batch cannot fall off the captured range.
    # Costs ~2 min of startup and some memory per extra size; if a phase OOMs
    # at capture time, drop kv_cache_gib rather than this.
    rows = max(max_num_seqs, max(points)) * (1 + spec_tokens)
    graph_ceiling = max(512, -(-rows // 16) * 16)
    print(
        f"[spec] graph ceiling {graph_ceiling} rows (max c={max(points)})",
        flush=True,
    )

    prompt_file = f"{out}/prompts.jsonl"
    rc = _stream(
        [SPEC_PY, "-c", EVAL_PROMPTS, prompt_file, *specs.split(",")],
        cwd=REMOTE_SPEC,
        label="Step 0: extract eval prompts",
    )
    if rc != 0:
        raise RuntimeError(f"prompt extraction failed, rc={rc}")
    with open(prompt_file) as fh:
        rows = [json.loads(line) for line in fh if line.strip()]
    # Interleaved, not concatenated: _measure takes a prefix of this list, so a
    # source-grouped pool would make every point below one wave of the pool a
    # different workload from the ones above it.
    random.Random(42).shuffle(rows)
    prompts = [row["prompt"] for row in rows]
    sources: dict[str, int] = {}
    for row in rows:
        sources[row["source"]] = sources.get(row["source"], 0) + 1
    print(f"[spec] {len(prompts)} prompts: {sources}", flush=True)

    phases = [("draft", drafter)]
    if not skip_baseline:
        phases.append(("no-draft", model))

    results: dict = {
        "model": model,
        "drafter": drafter,
        "prompts": len(prompts),
        "sources": sources,
        "max_tokens": max_tokens,
        "phases": {},
    }
    for name, serve_path in phases:
        proc, log = _serve_target(
            serve_path,
            served_name,
            f"{out}/server-{name}.log",
            graph_ceiling=graph_ceiling,
            port=port,
            kv_cache_gib=kv_cache_gib,
            max_num_seqs=max_num_seqs,
            max_model_len=max_model_len,
            gpu_memory_utilization=gpu_memory_utilization,
        )
        try:
            _wait_health(endpoint, proc, timeout_s=1800)
            phase: dict = {"audit": _server_audit(endpoint), "points": []}
            for concurrency in points:
                measured = _measure(
                    endpoint,
                    served_name,
                    prompts,
                    concurrency,
                    max_tokens,
                    spec=name == "draft",
                    waves=waves,
                )
                print(f"[{name}] {measured}", flush=True)
                phase["points"].append(measured)
            results["phases"][name] = phase
        finally:
            print(f"[spec] stopping {name} server", flush=True)
            proc.terminate()
            try:
                proc.wait(timeout=180)
            except subprocess.TimeoutExpired:
                proc.kill()
            log.close()

    for name, phase in results["phases"].items():
        for warning in _integrity_warnings(phase["points"]):
            print(f"[integrity] {name}: {warning}", flush=True)
            phase.setdefault("warnings", []).append(warning)

    with open(f"{out}/results.json", "w") as fh:
        json.dump(results, fh, indent=2)
    spec_out.commit()
    return _acceptance_report(results, out, label)


def _integrity_warnings(points: list[dict], min_waves: float = 4.0) -> list[str]:
    """bench/report.py's checks, applied to a phase measured here.

    Not imported from there: the container image excludes `inco/`, so this
    function is a copy. Keep the two in step.
    """
    found = []
    ordered = sorted(points, key=lambda p: p["concurrency"])
    for earlier, later in zip(ordered, ordered[1:]):
        if later["tok_s_user"] > earlier["tok_s_user"]:
            found.append(
                f"tok/s/user rose from {earlier['tok_s_user']:.1f} at c="
                f"{earlier['concurrency']} to {later['tok_s_user']:.1f} at c="
                f"{later['concurrency']}: impossible, so these points do not "
                "measure the engine"
            )
    for point in ordered:
        seen = point["requests"] / point["concurrency"]
        if seen < min_waves:
            found.append(
                f"c={point['concurrency']} saw only {seen:.1f} waves "
                f"({point['requests']} requests)"
            )
    return found


def _acceptance_report(results: dict, out: str, label: str) -> str:
    """Markdown for the two phases, plus the lossless-output check."""
    lines = [
        f"target:  {results['model']}",
        f"drafter: {results['drafter']}",
        f"prompts: {results['prompts']} {results['sources']}",
        f"max_tokens: {results['max_tokens']}, greedy",
        "",
        (
            "| phase | c | tok/s/gpu | tok/s/user | mean lat s | out tok | "
            "accept_len | accept_rate |"
        ),
        "|---|---|---|---|---|---|---|---|",
    ]
    for name, phase in results["phases"].items():
        for point in phase["points"]:
            lines.append(
                f"| {name} | {point['concurrency']} | {point['tok_s_gpu']} | "
                f"{point['tok_s_user']} | {point['mean_latency_s']} | "
                f"{point['output_tokens']} | {point.get('accept_len', '-')} | "
                f"{point.get('accept_rate', '-')} |"
            )

    drafted = results["phases"].get("draft", {}).get("points", [])
    plain = results["phases"].get("no-draft", {}).get("points", [])
    if plain:
        lines += ["", "| c | tok/s/gpu draft | no-draft | ratio | output tokens |"]
        lines.append("|---|---|---|---|---|")
        for spec_point, base_point in zip(drafted, plain):
            ratio = spec_point["tok_s_gpu"] / base_point["tok_s_gpu"]
            # Greedy spec decode is lossless, so the two phases should emit the
            # same tokens for the same prompts. A gap means one phase truncated
            # or the sampling path differed -- read the throughput with care.
            delta = spec_point["output_tokens"] - base_point["output_tokens"]
            lines.append(
                f"| {spec_point['concurrency']} | {spec_point['tok_s_gpu']} | "
                f"{base_point['tok_s_gpu']} | {ratio:.2f}x | "
                f"{spec_point['output_tokens']} vs {base_point['output_tokens']} "
                f"({delta:+d}) |"
            )

    for name, phase in results["phases"].items():
        lines += ["", f"{name} audit: {phase['audit']}"]
        for point in phase["points"]:
            if point.get("per_pos_rate"):
                lines.append(
                    f"  c={point['concurrency']} per-position acceptance: "
                    f"{point['per_pos_rate']}"
                )

    lines += [
        "",
        f"saved to {out}/results.json",
        f"pull with: modal volume get inco-spec {label} ./inco/results/spec",
    ]
    return "\n".join(lines)
