---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lmcache.lmcache.ai
  resources:
  - cacheblendengines
  - lmcachecoordinators
  - lmcacheengines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lmcache.lmcache.ai
  resources:
  - cacheblendengines/finalizers
  - lmcachecoordinators/finalizers
  - lmcacheengines/finalizers
  verbs:
  - update
- apiGroups:
  - lmcache.lmcache.ai
  resources:
  - cacheblendengines/status
  - lmcachecoordinators/status
  - lmcacheengines/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
