# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project

from typing import ClassVar

import torch

import vllm.envs as envs
from vllm.config.cache import CacheDType
from vllm.logger import init_logger
from vllm.config import get_current_vllm_config_or_none
from vllm.model_executor.layers.attention.mla_attention import (
    MLACommonBackend,
    MLACommonDecodeMetadata,
    MLACommonImpl,
    MLACommonMetadata,
    MLACommonMetadataBuilder,
    QueryLenSupport,
)
from vllm.platforms import current_platform
from vllm.platforms.interface import DeviceCapability
from vllm.triton_utils import triton
from vllm.utils.torch_utils import is_quantized_kv_cache
from vllm.v1.attention.backend import (
    AttentionCGSupport,
    AttentionLayer,
    AttentionType,
    MultipleOf,
)
from vllm.v1.attention.ops.triton_decode_attention import (
    _decode_softmax_reducev_fwd,
    _fwd_grouped_kernel_stage1,
)

# Tuned per-bucket kernel configs (auto-generated by bench/tune_triton_mla.py)
try:
    from vllm.v1.attention.backends.mla.triton_mla_tuning import (
        lookup_config as _lookup_tuned_config,
    )
except ImportError:
    _lookup_tuned_config = None

logger = init_logger(__name__)

# Maximum num_kv_splits the attn_logits pool is allocated for. Each CG bucket
# picks its own `num_kv_splits <= MAX_NUM_KV_SPLITS` (see `_pick_num_kv_splits`)
# and passes a slice `attn_logits[:B, :, :num_kv_splits, :]` to the kernel —
# the slice preserves parent strides so different buckets coexist in the same
# underlying storage. `num_kv_splits` is a Triton `tl.constexpr`, so each
# bucket gets its own compiled kernel; `B` is constant per capture so this is
# CG-safe.
MAX_NUM_KV_SPLITS = 64

# Legacy constant kept for the VLLM_BATCH_INVARIANT path and as the small-batch
# cap; long-context single-request is still best with 64 splits on sm120 fp8.
CG_NUM_KV_SPLITS = 64


def _pick_num_kv_splits(B: int, q_num_heads: int) -> int:
    """Bucket-aware num_kv_splits.

    Target: keep total stage-1 CTAs (B * H_blocks * num_kv_splits) in the
    3-6x SM-count range on sm120 (144 SMs). BLOCK_H=8, so H_blocks=ceil(H/8).
    At B=1 we want many splits (bandwidth-bound, long ctx); at B=128 we want
    few (stage-1 already oversubscribes, stage-2 merge cost scales with splits).
    """
    # BLOCK_H=8 on sm120 fp8 MLA, see _decode_grouped_att_m_fwd.
    h_blocks = max(1, (q_num_heads + 7) // 8)
    # Target ~576 stage-1 CTAs (≈4× SM count); round DOWN to power of 2 so
    # splits never over-shoot. Cap at MAX_NUM_KV_SPLITS (pool shape).
    target = max(1, 576 // (B * h_blocks))
    # prev_pow2(target)
    p = 1
    while (p << 1) <= target:
        p <<= 1
    return max(1, min(MAX_NUM_KV_SPLITS, p))

# Persistent CUDA-graph-safe buffers SHARED across all TritonMLAImpl layer
# instances. Layers run sequentially in a forward pass so one buffer is enough
# per (device, shape, dtype) signature. Keyed so a mixed-dtype / multi-device
# deployment still works.  Size at 30k ctx with spec=3 on sm120 TP=8:
#   attn_logits: (512, 8, 64, 513) float32 = 538 MB  (vs 61× that per-layer)
#   o:           (512, 8, 512)    bf16    = 4 MB
#   lse:         (512, 8)         bf16    = 8 KB
_SHARED_CG_BUFFERS: dict[tuple, torch.Tensor] = {}


def _get_shared_cg_buffer(
    key_prefix: str,
    shape: tuple[int, ...],
    dtype: torch.dtype,
    device: torch.device,
    init_zeros: bool = False,
) -> torch.Tensor:
    key = (key_prefix, device, shape, dtype)
    buf = _SHARED_CG_BUFFERS.get(key)
    if buf is None:
        if init_zeros:
            buf = torch.zeros(shape, dtype=dtype, device=device)
        else:
            buf = torch.empty(shape, dtype=dtype, device=device)
        _SHARED_CG_BUFFERS[key] = buf
    return buf


class TritonMLABackend(MLACommonBackend):
    supported_dtypes: ClassVar[list[torch.dtype]] = [torch.float16, torch.bfloat16]
    supported_kv_cache_dtypes: ClassVar[list[CacheDType]] = [
        "auto",
        "float16",
        "bfloat16",
        "fp8",
        "fp8_e4m3",
    ]

    @classmethod
    def get_supported_head_sizes(cls) -> list[int]:
        return []

    @staticmethod
    def get_supported_kernel_block_sizes() -> list[int | MultipleOf]:
        return [MultipleOf(16)]

    @classmethod
    def supports_block_size(cls, block_size: int | None) -> bool:
        if block_size is None:
            return True
        return block_size % 16 == 0

    @staticmethod
    def get_name() -> str:
        return "TRITON_MLA"

    @classmethod
    def supports_batch_invariance(cls) -> bool:
        return True

    @staticmethod
    def get_impl_cls() -> type["TritonMLAImpl"]:
        return TritonMLAImpl

    @staticmethod
    def get_builder_cls() -> type["TritonMLAMetadataBuilder"]:
        return TritonMLAMetadataBuilder

    @classmethod
    def supports_compute_capability(cls, capability: DeviceCapability) -> bool:
        return True


class TritonMLAMetadataBuilder(MLACommonMetadataBuilder[MLACommonMetadata]):
    # FULL cudagraphs are safe to capture per-batch-size as long as every
    # replay uses the same num_kv_splits / output buffer addresses. We enforce
    # both in TritonMLAImpl.forward_mqa (fixed CG_NUM_KV_SPLITS + persistent
    # buffers) and here (per-query block_table / seq_lens written in-place into
    # persistent cg_buf_*).
    _cudagraph_support: ClassVar[AttentionCGSupport] = AttentionCGSupport.UNIFORM_BATCH
    # UNIFORM = all requests in the batch have the same query_len. Combined
    # with _init_reorder_batch_threshold(supports_spec_as_decode=True), this
    # makes spec-verify batches (query_len = 1 + num_spec_tokens per request)
    # route through the decode path instead of the expensive prefill branch.
    query_len_support: ClassVar[QueryLenSupport] = QueryLenSupport.UNIFORM

    def __init__(self, *args, **kwargs):
        # Force supports_dcp_with_varlen=True so that
        # _init_reorder_batch_threshold does NOT override our bumped threshold
        # back to 1 under DCP>1. Our per-query seq_lens expansion in
        # _build_decode operates on dcp_local_seq_lens (which the base
        # build() already passes in when DCP is active), and the Triton MLA
        # decode kernel reads the per-query local seq_len directly, so the
        # semantics are well-defined under DCP+spec-verify.
        kwargs.setdefault("supports_dcp_with_varlen", True)
        super().__init__(*args, **kwargs)

        # Persistent CUDA-graph-safe buffers for the spec-verify case where the
        # Triton decode kernel needs per-query block_table rows and seq_lens.
        # These are populated in _build_decode via `.copy_()` so the addresses
        # seen by a captured graph stay stable across replays.
        #
        # Size: max_num_seqs * reorder_batch_threshold covers the largest
        # captured cudagraph shape. reorder_batch_threshold was just bumped by
        # `_init_reorder_batch_threshold(supports_spec_as_decode=True)` to
        # 1 + num_spec_tokens, so this is (max_num_seqs * (1+num_spec)).
        max_num_tokens = (
            self.vllm_config.scheduler_config.max_num_seqs
            * max(1, int(self.reorder_batch_threshold))
        )
        block_size = self.kv_cache_spec.block_size
        max_model_len = self.vllm_config.model_config.max_model_len
        max_blocks_per_req = (max_model_len + block_size - 1) // block_size

        self._cg_buf_block_table: torch.Tensor | None = None
        self._cg_buf_seq_lens: torch.Tensor | None = None
        self._cg_max_num_tokens = max_num_tokens
        self._cg_max_blocks_per_req = max_blocks_per_req
        self._cg_enabled = (
            self.compilation_config.cudagraph_mode.has_full_cudagraphs()
        )

    def _maybe_lazy_init_cg_bufs(
        self, device: torch.device, block_table_dtype: torch.dtype,
        seq_lens_dtype: torch.dtype,
    ) -> None:
        if self._cg_buf_block_table is None:
            # Zero-init so unused cells (beyond bt_cols_src / bt_rows) are
            # deterministic page=0 instead of random bytes. Kernel masks
            # those out via seq_lens anyway, but this removes any chance of
            # wild pointer arithmetic in stage-1 pointer compute and lets us
            # drop the per-step zero_() that used to clear stale tail.
            self._cg_buf_block_table = torch.zeros(
                (self._cg_max_num_tokens, self._cg_max_blocks_per_req),
                dtype=block_table_dtype,
                device=device,
            )
            self._cg_buf_seq_lens = torch.zeros(
                (self._cg_max_num_tokens,),
                dtype=seq_lens_dtype,
                device=device,
            )

    def _build_decode(
        self,
        block_table_tensor: torch.Tensor,
        seq_lens_device: torch.Tensor,
        max_seq_len: int,
        query_start_loc_cpu: torch.Tensor,
        query_start_loc_device: torch.Tensor,
        num_decode_tokens: int,
        dcp_tot_seq_lens_device: torch.Tensor | None,
    ) -> MLACommonDecodeMetadata:
        num_reqs = seq_lens_device.shape[0]
        # For pure decode (num_decode_tokens == num_reqs, query_len==1 per req)
        # block_table already has the right shape and seq_lens is one per query.
        # The interesting case is spec-verify (num_decode_tokens == num_reqs * qpr
        # with qpr > 1): the Triton decode kernel indexes block_table with
        # `cur_batch` (0..num_decode_tokens-1) treating each query as an
        # independent "request", and loads seq_lens at the same index. So we
        # expand block_table by repeating each row `qpr` times and derive per-
        # query seq_lens from the post-step seq_lens_device.
        if num_decode_tokens > num_reqs and num_reqs > 0:
            qpr = num_decode_tokens // num_reqs
            # num_decode_tokens must be exactly num_reqs * qpr under UNIFORM
            # query_len_support. Assert to catch builder misconfiguration
            # early instead of silently indexing OOB in the kernel.
            assert num_decode_tokens == num_reqs * qpr, (
                "TritonMLA decode-path expects uniform query_len per request; "
                f"got num_decode_tokens={num_decode_tokens}, num_reqs={num_reqs}"
            )

            self._maybe_lazy_init_cg_bufs(
                device=block_table_tensor.device,
                block_table_dtype=block_table_tensor.dtype,
                seq_lens_dtype=seq_lens_device.dtype,
            )

            # Widen block_table_tensor in case it has fewer columns than our
            # persistent buffer (happens if this step only has small prefixes).
            bt_rows = num_decode_tokens
            bt_cols_src = block_table_tensor.shape[1]
            assert bt_rows <= self._cg_buf_block_table.shape[0], (
                f"spec-verify num_decode_tokens={bt_rows} exceeds CG buffer "
                f"capacity {self._cg_buf_block_table.shape[0]}"
            )
            assert bt_cols_src <= self._cg_buf_block_table.shape[1], (
                f"block_table has {bt_cols_src} columns > CG buffer "
                f"{self._cg_buf_block_table.shape[1]}"
            )

            # Expand in-place into CG-stable buffer: row i*qpr+j -> request
            # i's block_table row (same for every j in 0..qpr-1).
            for j in range(qpr):
                # Each strided slice is contiguous along dim 0 with stride qpr
                self._cg_buf_block_table[j:bt_rows:qpr, :bt_cols_src].copy_(
                    block_table_tensor
                )
            # Columns beyond bt_cols_src are unused by the kernel — it bounds
            # accesses with seq_lens via masked tl.load. We used to zero_()
            # them defensively every step, but (a) the buffer is now zeros-
            # initialised, (b) masked loads on CUDA never fault on wild
            # pointers, and (c) the per-step zero_() cost scales with mml
            # (up to ~7 MB copy at mml=262k). Safely dropped.

            # Per-query seq_lens for spec verify (qpr queries per request).
            # Query j in request i covers KV positions 0..(ctx+j) globally, so
            # its GLOBAL post-step seq_len is (global_per_req[i] - (qpr-1) + j).
            #
            # Under DCP, seq_lens_device passed in is already the LOCAL per-
            # request length (the base builder substitutes dcp_local_seq_lens
            # for seq_lens before calling _build_decode); we cannot derive
            # per-query LOCAL lens linearly from that because the dcp split is
            # per global position. Instead: build per-query GLOBAL seq_lens
            # from dcp_tot_seq_lens_device and run get_dcp_local_seq_lens on
            # them to get per-query LOCAL lens for this rank. In the non-DCP
            # case the linear derivation from seq_lens_device is correct as
            # before.
            _arange = torch.arange(
                qpr,
                device=seq_lens_device.device,
                dtype=seq_lens_device.dtype,
            )
            if dcp_tot_seq_lens_device is not None and self.dcp_world_size > 1:
                from vllm.v1.attention.backends.utils import (
                    get_dcp_local_seq_lens,
                )
                global_per_query = (
                    dcp_tot_seq_lens_device.to(seq_lens_device.dtype).unsqueeze(1)
                    - (qpr - 1)
                    + _arange
                ).reshape(-1)
                expanded = get_dcp_local_seq_lens(
                    global_per_query,
                    self.dcp_world_size,
                    self.dcp_rank,
                    self.cp_kv_cache_interleave_size,
                )
            else:
                expanded = (
                    seq_lens_device.unsqueeze(1) - (qpr - 1) + _arange
                ).reshape(-1)
            self._cg_buf_seq_lens[:bt_rows].copy_(expanded)

            # Also produce per-query global seq_lens for dcp_tot (the kernel
            # itself does not read dcp_tot, but MLACommonDecodeMetadata carries
            # it and downstream code may expect shape[0]==num_decode_tokens).
            if dcp_tot_seq_lens_device is not None:
                dcp_tot_expanded = (
                    dcp_tot_seq_lens_device.unsqueeze(1) - (qpr - 1) + _arange
                ).reshape(-1)
            else:
                dcp_tot_expanded = None

            return MLACommonDecodeMetadata(
                block_table=self._cg_buf_block_table[:bt_rows],
                seq_lens=self._cg_buf_seq_lens[:bt_rows],
                dcp_tot_seq_lens=dcp_tot_expanded,
            )

        # Fast path: query_len==1 per request, no expansion needed.
        return MLACommonDecodeMetadata(
            block_table=block_table_tensor,
            seq_lens=seq_lens_device,
            dcp_tot_seq_lens=dcp_tot_seq_lens_device,
        )


class TritonMLAImpl(MLACommonImpl[MLACommonMetadata]):
    can_return_lse_for_decode: bool = True

    def __init__(
        self,
        num_heads: int,
        head_size: int,
        scale: float,
        num_kv_heads: int,
        alibi_slopes: list[float] | None,
        sliding_window: int | None,
        kv_cache_dtype: str,
        logits_soft_cap: float | None,
        attn_type: str,
        kv_sharing_target_layer_name: str | None,
        # MLA Specific Arguments
        **mla_args,
    ) -> None:
        super().__init__(
            num_heads,
            head_size,
            scale,
            num_kv_heads,
            alibi_slopes,
            sliding_window,
            kv_cache_dtype,
            logits_soft_cap,
            attn_type,
            kv_sharing_target_layer_name,
            **mla_args,
        )

        unsupported_features = [alibi_slopes, sliding_window, logits_soft_cap]
        if any(unsupported_features):
            raise NotImplementedError(
                "TritonMLAImpl does not support one of the following: "
                "alibi_slopes, sliding_window, logits_soft_cap"
            )

        if attn_type != AttentionType.DECODER:
            raise NotImplementedError(
                "Encoder self-attention and "
                "encoder/decoder cross-attention "
                "are not implemented for "
                "TritonMLAImpl"
            )

        # For FP8 KV cache, we dequantize to BF16 on load inside the
        # Triton kernel. Tell the common layer not to quantize queries
        # to FP8 — we handle FP8 KV cache with BF16 queries (Mode 1).
        if is_quantized_kv_cache(self.kv_cache_dtype):
            self.supports_quant_query_input = False

        self._sm_count = current_platform.num_compute_units()
        self._use_tuned_config = (
            current_platform.is_cuda()
            and current_platform.has_device_capability(120)
            and is_quantized_kv_cache(self.kv_cache_dtype)
            and _lookup_tuned_config is not None
        )

        # CG-safe persistent buffers are pulled from the SHARED module-level
        # pool on first forward_mqa call, so all 61 target layers + 1 draft
        # layer reuse the same attn_logits / o / lse storage instead of each
        # owning a 538 MB buffer.
        vllm_cfg = get_current_vllm_config_or_none()
        if vllm_cfg is not None:
            scheduler_cfg = vllm_cfg.scheduler_config
            # max_num_seqs * (1 + num_spec_tokens) covers spec verify.
            spec_cfg = vllm_cfg.speculative_config
            qpr_max = 1 + (spec_cfg.num_speculative_tokens if spec_cfg is not None
                           and spec_cfg.num_speculative_tokens is not None
                           else 0)
            self._cg_max_tokens: int = scheduler_cfg.max_num_seqs * qpr_max
            # Also honour the actual cudagraph_capture_sizes max if compilation
            # config is available (the scheduler max can exceed what CG
            # actually captures, see max_cudagraph_capture_size).
            try:
                cg_max = vllm_cfg.compilation_config.max_cudagraph_capture_size
                if cg_max is not None:
                    self._cg_max_tokens = min(self._cg_max_tokens, cg_max)
            except AttributeError:
                pass
            # Used as the tuning-table key (we store the configured max
            # model_len, since actual seq_len varies per-call and the table
            # rounds down to the nearest tuned bucket).
            self._tuning_max_model_len: int = (
                vllm_cfg.model_config.max_model_len
            )
        else:
            # conservative fallback; should not happen in a normal serve path
            self._cg_max_tokens = 512
            self._tuning_max_model_len = 262144

    def _flash_attn_varlen_diff_headdims(
        self, q, k, v, return_softmax_lse=False, softmax_scale=None, **kwargs
    ):
        return super()._flash_attn_varlen_diff_headdims(
            q,
            k,
            v,
            return_softmax_lse=return_softmax_lse,
            softmax_scale=softmax_scale,
            **kwargs,
        )

    def forward_mqa(
        self,
        q: torch.Tensor | tuple[torch.Tensor, torch.Tensor],
        kv_c_and_k_pe_cache: torch.Tensor,
        attn_metadata: MLACommonMetadata,
        layer: AttentionLayer,
    ) -> tuple[torch.Tensor, torch.Tensor | None]:
        assert kv_c_and_k_pe_cache.numel() > 0
        assert attn_metadata.decode is not None

        if type(q) is tuple:
            q = torch.cat(q, dim=-1)

        assert isinstance(q, torch.Tensor)
        B = q.shape[0]
        q_num_heads = q.shape[1]

        # Per-bucket tuned kernel config from triton_mla_tuning.TUNED_KV_CONFIGS
        # keyed on (q_num_heads, max_model_len, B). Falls back to the analytical
        # heuristic (old defaults) if not tuned. All values become Triton
        # `tl.constexpr` at kernel launch time → CG-safe (same compiled variant
        # per batch-size bucket).
        if envs.VLLM_BATCH_INVARIANT:
            kernel_cfg = {
                "num_kv_splits": 1,
                "BLOCK_N": 32, "BLOCK_H": 8,
                "num_stages": 2, "num_warps": 4,
            }
        else:
            kernel_cfg = None
            if self._use_tuned_config:
                kernel_cfg = _lookup_tuned_config(
                    q_num_heads, self._tuning_max_model_len, B
                )
            if kernel_cfg is None:
                kernel_cfg = {
                    "num_kv_splits": _pick_num_kv_splits(B, q_num_heads),
                    "BLOCK_N": 32, "BLOCK_H": 8,
                    "num_stages": 2, "num_warps": 4,
                }
        num_kv_splits = kernel_cfg["num_kv_splits"]

        # Pull CG-safe persistent buffers from the shared pool (one set per
        # (device, dtype, shape) tuple across ALL layers). attn_logits is
        # always allocated at MAX_NUM_KV_SPLITS so the same storage serves
        # every bucket; we pass a `[:num_kv_splits]` slice to the kernel.
        assert B <= self._cg_max_tokens, (
            f"forward_mqa: B={B} exceeds CG capture max {self._cg_max_tokens}"
        )
        o_buf = _get_shared_cg_buffer(
            "o",
            (self._cg_max_tokens, q_num_heads, self.kv_lora_rank),
            q.dtype,
            q.device,
        )
        lse_buf = _get_shared_cg_buffer(
            "lse",
            (self._cg_max_tokens, q_num_heads),
            q.dtype,
            q.device,
        )
        attn_logits_buf = _get_shared_cg_buffer(
            "attn_logits",
            (
                self._cg_max_tokens,
                q_num_heads,
                MAX_NUM_KV_SPLITS,
                # +1 stores the LSE that stage2 uses to merge partial outs
                self.kv_lora_rank + 1,
            ),
            torch.float32,
            q.device,
        )
        o = o_buf[:B]
        lse = lse_buf[:B]
        # Slice keeps parent strides — the kernel reads strides from this view
        # and ignores the rest of the pool. This is what makes bucket-dependent
        # num_kv_splits CG-safe.
        attn_logits = attn_logits_buf[:B, :, :num_kv_splits, :]

        # Add a head dim of 1
        kv_c_and_k_pe_cache = kv_c_and_k_pe_cache.unsqueeze(2)
        kv_c_cache = kv_c_and_k_pe_cache[..., : self.kv_lora_rank]
        PAGE_SIZE = kv_c_and_k_pe_cache.size(1)

        # Inlined stage-1 + stage-2 decode attention so we can pass tuned
        # BLOCK_N / BLOCK_H / num_stages / num_warps per bucket. block_table
        # and seq_lens are already per-query for spec verify (expanded by
        # TritonMLAMetadataBuilder._build_decode into CG-safe buffers) or
        # per-request for pure decode.
        Lk = kv_c_and_k_pe_cache.shape[-1]  # 576 for Kimi MLA
        Lv = kv_c_cache.shape[-1]  # 512
        BLOCK_DV = triton.next_power_of_2(Lv)
        kv_group_num = q_num_heads  # MLA: single latent KV head
        block_table = attn_metadata.decode.block_table
        seq_lens = attn_metadata.decode.seq_lens
        grid_s1 = (
            B,
            triton.cdiv(q_num_heads, min(kernel_cfg["BLOCK_H"], kv_group_num)),
            num_kv_splits,
        )
        _fwd_grouped_kernel_stage1[grid_s1](
            q, kv_c_and_k_pe_cache, kv_c_and_k_pe_cache, self.scale,
            block_table, seq_lens, attn_logits,
            block_table.stride(0),
            q.stride(0), q.stride(1),
            kv_c_and_k_pe_cache.stride(-3), kv_c_and_k_pe_cache.stride(-2),
            kv_c_and_k_pe_cache.stride(-3), kv_c_and_k_pe_cache.stride(-2),
            attn_logits.stride(0), attn_logits.stride(1), attn_logits.stride(2),
            layer._k_scale, layer._k_scale,
            kv_group_num=kv_group_num,
            q_head_num=q_num_heads,
            BLOCK_DMODEL=self.kv_lora_rank,
            BLOCK_DPE=self.qk_rope_head_dim,
            BLOCK_DV=BLOCK_DV,
            BLOCK_N=kernel_cfg["BLOCK_N"],
            BLOCK_H=kernel_cfg["BLOCK_H"],
            NUM_KV_SPLITS=num_kv_splits,
            PAGE_SIZE=PAGE_SIZE,
            logit_cap=0.0,
            num_warps=kernel_cfg["num_warps"],
            num_stages=kernel_cfg["num_stages"],
            Lk=Lk, Lv=Lv, IS_MLA=True,
        )
        # Stage 2 merge: defaults (num_warps=4, num_stages=2) are fine,
        # cost is ~10% of stage-1 so not a tuning target in phase 1.
        _decode_softmax_reducev_fwd(
            attn_logits, q, o, lse, kv_c_cache, seq_lens, num_kv_splits,
        )

        return o, lse
