group: Basic Correctness
depends_on:
  - image-build-xpu
steps:
- label: XPU Sleep Mode
  timeout_in_minutes: 45
  device: intel_gpu
  agent_tags:
    label: production
    gpu: 1+
    mem: 16+
  no_plugin: true
  working_dir: "."
  env:
    REGISTRY: "public.ecr.aws/q9t5s3a7"
    REPO: "vllm-ci-test-repo"
    VLLM_TEST_DEVICE: "xpu"
  source_file_dependencies:
  - vllm/
  - tests/basic_correctness/test_cumem.py
  commands:
    - >-
      bash .buildkite/scripts/hardware_ci/run-intel-test.sh
      'cd tests &&
      export VLLM_WORKER_MULTIPROC_METHOD=spawn &&
      pytest -v -s basic_correctness/test_cpu_offload.py &&
      pytest -v -s basic_correctness/test_mem.py::test_end_to_end'
