group: Benchmarks
depends_on: 
  - image-build-xpu
steps:
- label: Benchmarks CLI Test
  key: benchmarks-cli-test
  timeout_in_minutes: 40
  device: intel_gpu
  agent_tags:
    label: production
    gpu: 1+
    mem: 16+
  no_plugin: true
  working_dir: "."
  env:
    REGISTRY: "public.ecr.aws/q9t5s3a7"
    REPO: "vllm-ci-test-repo"
    VLLM_TEST_DEVICE: "xpu"
  source_file_dependencies:
  - vllm/
  - tests/benchmarks/
  # Remove VLLM_DISABLE_COMPILE_CACHE=1 once intel/intel-xpu-backend-for-triton#7682 is fixed
  commands:
    - >-
      bash .buildkite/scripts/hardware_ci/run-intel-test.sh
      'cd tests &&
      VLLM_DISABLE_COMPILE_CACHE=1 pytest -v -s benchmarks/'
