group: CUDA Intel
depends_on:
  - image-build-xpu
steps:
- label: Platform Tests (CUDA)
  timeout_in_minutes: 15
  device: intel_gpu
  no_plugin: true
  working_dir: .
  env:
    REGISTRY: public.ecr.aws/q9t5s3a7
    REPO: vllm-ci-test-repo
    VLLM_TEST_DEVICE: xpu
  agent_tags:
    label: debug
    gpu: 1+
  _raw_old_commands:
  - pytest -v -s cuda/test_cuda_context.py
  - pytest -v -s cuda/test_platform_no_cuda_init.py
  source_file_dependencies:
  - vllm/envs.py
  - vllm/logger.py
  - vllm/platforms/
  - vllm/plugins/
  - vllm/utils/
  - tests/cuda
  commands:
  - >-
    bash .buildkite/scripts/hardware_ci/run-intel-test.sh
    'cd tests && 
    pytest -v -s cuda/test_cuda_context.py &&
    pytest -v -s cuda/test_platform_no_cuda_init.py'
- label: Cudagraph
  timeout_in_minutes: 20
  device: intel_gpu
  no_plugin: true
  working_dir: .
  env:
    REGISTRY: public.ecr.aws/q9t5s3a7
    REPO: vllm-ci-test-repo
    VLLM_TEST_DEVICE: xpu
  agent_tags:
    label: debug
    gpu: 1+
  _raw_old_commands:
  - pytest -v -s v1/cudagraph/test_cudagraph_dispatch.py
  - pytest -v -s v1/cudagraph/test_cudagraph_mode.py
  - pytest -v -s v1/cudagraph/test_breakable_cudagraph.py
  source_file_dependencies:
  - tests/v1/cudagraph
  - vllm/v1/cudagraph_dispatcher.py
  - vllm/config/compilation.py
  - vllm/compilation
  commands:
  - >-
    bash .buildkite/scripts/hardware_ci/run-intel-test.sh
    'cd tests && 
    pytest -v -s v1/cudagraph/test_cudagraph_dispatch.py &&
    pytest -v -s v1/cudagraph/test_cudagraph_mode.py &&
    pytest -v -s v1/cudagraph/test_breakable_cudagraph.py'
