group: Distributed
depends_on:
  - image-build-xpu
steps:
- label: ":intel: (XPU) Distributed Torchrun + Shutdown"
  key: distributed-torchrun-shutdown-tests-2-gpus
  timeout_in_minutes: 30
  device: intel_gpu
  agent_tags:
    label: production
    gpu: 2+
    mem: 24+
  no_plugin: true
  working_dir: "."
  env:
    REGISTRY: "public.ecr.aws/q9t5s3a7"
    REPO: "vllm-ci-test-repo"
    VLLM_TEST_DEVICE: "xpu"
  source_file_dependencies:
  - vllm/distributed/
  - "!vllm/distributed/kv_transfer/"
  - vllm/engine/
  - vllm/executor/
  - vllm/worker/worker_base.py
  - vllm/v1/engine/
  - vllm/v1/worker/
  - tests/distributed/
  - tests/v1/shutdown
  - tests/v1/worker/test_worker_memory_snapshot.py
  commands:
    - >-
      bash .buildkite/scripts/hardware_ci/run-intel-test.sh
      'cd tests &&
      ZE_AFFINITY_MASK=0,1 pytest -v -s v1/shutdown'
