group: Entrypoints Intel
depends_on:
  - image-build-xpu
steps:
- label: Entrypoints Unit Tests
  timeout_in_minutes: 10
  working_dir: .
  device: intel_gpu
  no_plugin: true
  env:
    REGISTRY: public.ecr.aws/q9t5s3a7
    REPO: vllm-ci-test-repo
    VLLM_TEST_DEVICE: xpu
  agent_tags:
    label: debug
    gpu: 1+
  _raw_old_commands:
  - pytest -v -s entrypoints/unit_tests
  - pytest -v -s entrypoints/weight_transfer
  source_file_dependencies:
  - vllm/entrypoints
  - tests/entrypoints/unit_tests
  - tests/entrypoints/weight_transfer
  commands:
  - >-
    bash .buildkite/scripts/hardware_ci/run-intel-test.sh
    'cd tests && 
    pytest -v -s entrypoints/unit_tests &&
    pytest -v -s entrypoints/weight_transfer'
- label: Entrypoints Integration (LLM)
  timeout_in_minutes: 40
  working_dir: .
  device: intel_gpu
  no_plugin: true
  env:
    REGISTRY: public.ecr.aws/q9t5s3a7
    REPO: vllm-ci-test-repo
    VLLM_TEST_DEVICE: xpu
  agent_tags:
    label: debug
    gpu: 1+
  _raw_old_commands:
  - export VLLM_WORKER_MULTIPROC_METHOD=spawn
  - pytest -v -s entrypoints/llm --ignore=entrypoints/llm/test_generate.py --ignore=entrypoints/llm/test_collective_rpc.py --ignore=entrypoints/llm/offline_mode
  - pytest -v -s entrypoints/llm/test_generate.py
  - pytest -v -s entrypoints/llm/offline_mode
  source_file_dependencies:
  - vllm/
  - tests/entrypoints/llm
  commands:
  - >-
    bash .buildkite/scripts/hardware_ci/run-intel-test.sh
    'cd tests && 
    export VLLM_WORKER_MULTIPROC_METHOD=spawn &&
    pytest -v -s entrypoints/llm --ignore=entrypoints/llm/test_generate.py --ignore=entrypoints/llm/test_collective_rpc.py --ignore=entrypoints/llm/offline_mode &&
    pytest -v -s entrypoints/llm/test_generate.py &&
    pytest -v -s entrypoints/llm/offline_mode'
- label: Entrypoints Integration (API Server)
  device: intel_gpu
  timeout_in_minutes: 130
  working_dir: .
  no_plugin: true
  env:
    REGISTRY: public.ecr.aws/q9t5s3a7
    REPO: vllm-ci-test-repo
    VLLM_TEST_DEVICE: xpu
  agent_tags:
    label: debug
    gpu: 1+
  _raw_old_commands:
  - export VLLM_WORKER_MULTIPROC_METHOD=spawn
  - pytest -v -s entrypoints/serve --ignore=entrypoints/serve/dev/rpc
  - PYTHONPATH=/vllm-workspace pytest -v -s entrypoints/serve/dev/rpc
  source_file_dependencies:
  - vllm/
  - tests/entrypoints/serve
  commands:
  - >-
    bash .buildkite/scripts/hardware_ci/run-intel-test.sh
    'cd tests && 
    export VLLM_WORKER_MULTIPROC_METHOD=spawn &&
    pytest -v -s entrypoints/serve --ignore=entrypoints/serve/dev/rpc &&
    PYTHONPATH=/vllm-workspace pytest -v -s entrypoints/serve/dev/rpc'
- label: Entrypoints Integration (API Server OpenAI - Part 1)
  timeout_in_minutes: 50
  working_dir: .
  device: intel_gpu
  no_plugin: true
  env:
    REGISTRY: public.ecr.aws/q9t5s3a7
    REPO: vllm-ci-test-repo
    VLLM_TEST_DEVICE: xpu
  agent_tags:
    label: debug
    gpu: 1+
  _raw_old_commands:
  - export VLLM_WORKER_MULTIPROC_METHOD=spawn
  - pytest -v -s entrypoints/openai --ignore=entrypoints/openai/completion --ignore=entrypoints/openai/chat_completion --ignore=entrypoints/openai/responses --ignore=entrypoints/openai/correctness
  source_file_dependencies:
  - vllm/
  - tests/entrypoints/openai
  - tests/entrypoints/test_chat_utils
  commands:
  - >-
    bash .buildkite/scripts/hardware_ci/run-intel-test.sh
    'cd tests && 
    export VLLM_WORKER_MULTIPROC_METHOD=spawn &&
    pytest -v -s entrypoints/openai --ignore=entrypoints/openai/completion --ignore=entrypoints/openai/chat_completion --ignore=entrypoints/openai/responses --ignore=entrypoints/openai/correctness'
- label: Entrypoints Integration (API Server OpenAI - Part 2)
  timeout_in_minutes: 50
  working_dir: .
  device: intel_gpu
  no_plugin: true
  env:
    REGISTRY: public.ecr.aws/q9t5s3a7
    REPO: vllm-ci-test-repo
    VLLM_TEST_DEVICE: xpu
  agent_tags:
    label: debug
    gpu: 1+
  _raw_old_commands:
  - export VLLM_WORKER_MULTIPROC_METHOD=spawn
  - pytest -v -s entrypoints/openai/chat_completion
  - pytest -v -s entrypoints/openai/completion --ignore=entrypoints/openai/completion/test_tensorizer_entrypoint.py
  source_file_dependencies:
  - vllm/
  - tests/entrypoints/openai
  - tests/entrypoints/test_chat_utils
  commands:
  - >-
    bash .buildkite/scripts/hardware_ci/run-intel-test.sh
    'cd tests && 
    export VLLM_WORKER_MULTIPROC_METHOD=spawn &&
    pytest -v -s entrypoints/openai/chat_completion &&
    pytest -v -s entrypoints/openai/completion --ignore=entrypoints/openai/completion/test_tensorizer_entrypoint.py'
- label: Entrypoints Integration (API Server Generate)
  timeout_in_minutes: 50
  working_dir: .
  device: intel_gpu
  no_plugin: true
  env:
    REGISTRY: public.ecr.aws/q9t5s3a7
    REPO: vllm-ci-test-repo
    VLLM_TEST_DEVICE: xpu
  agent_tags:
    label: debug
    gpu: 1+
  _raw_old_commands:
  - pytest -v -s tool_use
  - pytest -v -s entrypoints/tool_parsers
  - pytest -v -s entrypoints/generate
  - pytest -v -s entrypoints/anthropic
  source_file_dependencies:
  - vllm/
  - tests/tool_use
  - tests/entrypoints/tool_parsers
  - tests/entrypoints/anthropic
  - tests/entrypoints/generate
  commands:
  - >-
    bash .buildkite/scripts/hardware_ci/run-intel-test.sh
    'cd tests && 
    pytest -v -s tool_use &&
    pytest -v -s entrypoints/tool_parsers &&
    pytest -v -s entrypoints/generate &&
    pytest -v -s entrypoints/anthropic'
- label: Entrypoints Integration (Responses API)
  timeout_in_minutes: 50
  working_dir: .
  device: intel_gpu
  no_plugin: true
  env:
    REGISTRY: public.ecr.aws/q9t5s3a7
    REPO: vllm-ci-test-repo
    VLLM_TEST_DEVICE: xpu
  agent_tags:
    label: debug
    gpu: 1+
  _raw_old_commands:
  - pytest -v -s entrypoints/openai/responses
  source_file_dependencies:
  - vllm/
  - tests/entrypoints/openai/responses
  commands:
  - >-
    bash .buildkite/scripts/hardware_ci/run-intel-test.sh
    'cd tests && 
    pytest -v -s entrypoints/openai/responses'
- label: Entrypoints Integration (Speech to Text)
  device: intel_gpu
  timeout_in_minutes: 50
  working_dir: .
  no_plugin: true
  env:
    REGISTRY: public.ecr.aws/q9t5s3a7
    REPO: vllm-ci-test-repo
    VLLM_TEST_DEVICE: xpu
  agent_tags:
    label: debug
    gpu: 1+
  _raw_old_commands:
  - export VLLM_WORKER_MULTIPROC_METHOD=spawn
  - pytest -v -s entrypoints/speech_to_text
  source_file_dependencies:
  - vllm/
  - tests/entrypoints/speech_to_text
  commands:
  - >-
    bash .buildkite/scripts/hardware_ci/run-intel-test.sh
    'cd tests && 
    export VLLM_WORKER_MULTIPROC_METHOD=spawn &&
    pytest -v -s entrypoints/speech_to_text'
- label: Entrypoints Integration (Multimodal)
  device: intel_gpu
  timeout_in_minutes: 50
  working_dir: .
  no_plugin: true
  env:
    REGISTRY: public.ecr.aws/q9t5s3a7
    REPO: vllm-ci-test-repo
    VLLM_TEST_DEVICE: xpu
  agent_tags:
    label: debug
    gpu: 1+
  _raw_old_commands:
  - export VLLM_WORKER_MULTIPROC_METHOD=spawn
  - pytest -v -s entrypoints/multimodal
  source_file_dependencies:
  - vllm/
  - tests/entrypoints/multimodal
  commands:
  - >-
    bash .buildkite/scripts/hardware_ci/run-intel-test.sh
    'cd tests && 
    export VLLM_WORKER_MULTIPROC_METHOD=spawn &&
    pytest -v -s entrypoints/multimodal'
- label: Entrypoints Integration (Pooling)
  timeout_in_minutes: 50
  working_dir: .
  device: intel_gpu
  no_plugin: true
  env:
    REGISTRY: public.ecr.aws/q9t5s3a7
    REPO: vllm-ci-test-repo
    VLLM_TEST_DEVICE: xpu
  agent_tags:
    label: debug
    gpu: 1+
  _raw_old_commands:
  - export VLLM_WORKER_MULTIPROC_METHOD=spawn
  - pytest -v -s entrypoints/pooling
  source_file_dependencies:
  - vllm/
  - tests/entrypoints/pooling
  commands:
  - >-
    bash .buildkite/scripts/hardware_ci/run-intel-test.sh
    'cd tests && 
    export VLLM_WORKER_MULTIPROC_METHOD=spawn &&
    pytest -v -s entrypoints/pooling'
- label: OpenAI API Correctness
  timeout_in_minutes: 30
  device: intel_gpu
  no_plugin: true
  working_dir: .
  env:
    REGISTRY: public.ecr.aws/q9t5s3a7
    REPO: vllm-ci-test-repo
    VLLM_TEST_DEVICE: xpu
  agent_tags:
    label: debug
    gpu: 1+
  _raw_old_commands:
  - pytest -s entrypoints/openai/correctness/
  source_file_dependencies:
  - csrc/
  - vllm/entrypoints/openai/
  commands:
  - >-
    bash .buildkite/scripts/hardware_ci/run-intel-test.sh
    'cd tests && 
    pytest -s entrypoints/openai/correctness/'
