group: Models - Basic
depends_on:
  - image-build-xpu
steps:
- label: Basic Models Tests (Initialization)
  key: basic-models-tests-initialization
  timeout_in_minutes: 45
  device: intel_gpu
  no_plugin: true
  working_dir: "."
  env:
    REGISTRY: "public.ecr.aws/q9t5s3a7"
    REPO: "vllm-ci-test-repo"
    VLLM_TEST_DEVICE: "xpu"
  source_file_dependencies:
  - vllm/
  - tests/models/test_initialization.py
  - tests/models/registry.py
  commands:
    # Run a subset of model initialization tests
    - >-
      bash .buildkite/scripts/hardware_ci/run-intel-test.sh
      'cd tests &&
      pytest -v -s models/test_initialization.py::test_can_initialize_small_subset
      --deselect "tests/models/test_initialization.py::test_can_initialize_small_subset[DeepSeekMTPModel]"
      --deselect "tests/models/test_initialization.py::test_can_initialize_small_subset[Llama4ForConditionalGeneration]"'
    
- label: Basic Models Tests (Extra Initialization) %N
  key: basic-models-tests-extra-initialization
  timeout_in_minutes: 45
  device: intel_gpu
  no_plugin: true
  working_dir: "."
  env:
    REGISTRY: "public.ecr.aws/q9t5s3a7"
    REPO: "vllm-ci-test-repo"
    VLLM_TEST_DEVICE: "xpu"
  source_file_dependencies:
  - vllm/model_executor/models/
  - tests/models/test_initialization.py
  - tests/models/registry.py
  commands:
    # Only when vLLM model source is modified - test initialization of a large
    # subset of supported models (the complement of the small subset in the above
    # test.) Also run if model initialization test file is modified
    - >-
      bash .buildkite/scripts/hardware_ci/run-intel-test.sh
      'cd tests &&
      pip install matplotlib ftfy &&
      pip install open-clip-torch --no-deps &&
      pytest -v -s models/test_initialization.py -k "not test_can_initialize_small_subset"
      --deselect "tests/models/test_initialization.py::test_can_initialize_large_subset[ArcticForCausalLM]"
      --deselect "tests/models/test_initialization.py::test_can_initialize_large_subset[Cheers]"
      --deselect "tests/models/test_initialization.py::test_can_initialize_large_subset[ColQwen3]"
      --deselect "tests/models/test_initialization.py::test_can_initialize_large_subset[DeepseekV32ForCausalLM]"
      --deselect "tests/models/test_initialization.py::test_can_initialize_large_subset[DeepseekV3ForCausalLM]"
      --deselect "tests/models/test_initialization.py::test_can_initialize_large_subset[Eagle3DeepseekV2ForCausalLM]"
      --deselect "tests/models/test_initialization.py::test_can_initialize_large_subset[Eagle3DeepseekV3ForCausalLM]"
      --deselect "tests/models/test_initialization.py::test_can_initialize_large_subset[Eagle3MiniMaxM2ForCausalLM]"
      --deselect "tests/models/test_initialization.py::test_can_initialize_large_subset[Eagle3Qwen2_5vlForCausalLM]"
      --deselect "tests/models/test_initialization.py::test_can_initialize_large_subset[EagleDeepSeekMTPModel]"
      --deselect "tests/models/test_initialization.py::test_can_initialize_large_subset[EagleMiniCPMForCausalLM]"
      --deselect "tests/models/test_initialization.py::test_can_initialize_large_subset[GraniteVision]"
      --deselect "tests/models/test_initialization.py::test_can_initialize_large_subset[H2OVLChatModel]"
      --deselect "tests/models/test_initialization.py::test_can_initialize_large_subset[HfMoondream]"
      --deselect "tests/models/test_initialization.py::test_can_initialize_large_subset[InternS1ProForConditionalGeneration]"
      --deselect "tests/models/test_initialization.py::test_can_initialize_large_subset[KimiK25ForConditionalGeneration]"
      --deselect "tests/models/test_initialization.py::test_can_initialize_large_subset[Llama4ForCausalLM]"
      --deselect "tests/models/test_initialization.py::test_can_initialize_large_subset[LongcatFlashForCausalLM]"
      --deselect "tests/models/test_initialization.py::test_can_initialize_large_subset[LongCatFlashMTPModel]"
      --deselect "tests/models/test_initialization.py::test_can_initialize_large_subset[MiniCPMO]"
      --deselect "tests/models/test_initialization.py::test_can_initialize_large_subset[MiniMaxM2ForCausalLM]"
      --deselect "tests/models/test_initialization.py::test_can_initialize_large_subset[MistralLarge3ForCausalLM]"
      --deselect "tests/models/test_initialization.py::test_can_initialize_large_subset[Molmo2ForConditionalGeneration]"
      --deselect "tests/models/test_initialization.py::test_can_initialize_large_subset[Moondream3ForCausalLM]"
      --deselect "tests/models/test_initialization.py::test_can_initialize_large_subset[OpsColQwen3Model]"
      --deselect "tests/models/test_initialization.py::test_can_initialize_large_subset[PEagleDraftModel]"
      --deselect "tests/models/test_initialization.py::test_can_initialize_large_subset[PeagleLlamaForCausalLM]"
      --deselect "tests/models/test_initialization.py::test_can_initialize_large_subset[Qwen2_5OmniForConditionalGeneration]"
      --deselect "tests/models/test_initialization.py::test_can_initialize_large_subset[Qwen3OmniMoeForConditionalGeneration]"
      --deselect "tests/models/test_initialization.py::test_can_initialize_large_subset[Qwen3VLNemotronEmbedModel]"
      --deselect "tests/models/test_initialization.py::test_can_initialize_large_subset[TransformersMultiModalMoEForCausalLM]"
      --num-shards=$$BUILDKITE_PARALLEL_JOB_COUNT --shard-id=$$BUILDKITE_PARALLEL_JOB'
  parallelism: 16
