group: Samplers Intel
depends_on:
  - image-build-xpu
steps:
- label: Samplers Test (FlashInfer)
  key: samplers-test-flashinfer-intel
  timeout_in_minutes: 40
  device: intel_gpu
  agent_tags:
    label: production
    gpu: 1+
    mem: 16+
  no_plugin: true
  working_dir: "."
  env:
    REGISTRY: "public.ecr.aws/q9t5s3a7"
    REPO: "vllm-ci-test-repo"
    VLLM_TEST_DEVICE: "xpu"
  source_file_dependencies:
  - vllm/model_executor/layers
  - vllm/sampling_metadata.py
  - tests/samplers
  - tests/conftest.py
  - vllm/entrypoints/generate/beam_search
  commands:
    - >-
      bash .buildkite/scripts/hardware_ci/run-intel-test.sh
      'cd tests &&
      VLLM_USE_FLASHINFER_SAMPLER=1 pytest -v -s samplers'