{
 "title": "Query Statistics_New",
 "description": "High-level overview of VLLM model deployment behavior and key performance indicators. Designed for Data Scientists and Product Managers to monitor request volume, token throughput, and latency",
 "time": { "from": "now/d+10h", "to": "now/d+16h" },
 "templating": {
  "list": [
   {
    "name": "Deployment_id",
    "label": "Deployment_ID",
    "query": {
     "query": "label_values(vllm:request_success_total,model_name)"
    }
   },
   {
    "name": "rush_hours",
    "label": "Rush Hours Only",
    "query": "false : All hours, true : Rush hours"
   },
   {
    "name": "rush_hours_type",
    "label": "Rush Hours Type",
    "query": "^All__.*$ : All, ^Static__.*$ : Static, ^Dynamic__.*$ : Dynamic"
   },
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "Request Over Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Successful Requests Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Requests/sec" } },
   "targets": [
    {
     "expr": "sum by (model_name) (\r\n  rate(vllm:request_success_total{model_name=~\"${Deployment_id}\"}[$__interval])\r\n)",
     "legendFormat": "{{model_name}}"
    }
   ]
  },
  {
   "title": "Requests Avg Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Requests/sec" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rate(vllm:request_success_total{model_name=~\"$Deployment_id\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p50 Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by(le, model_name) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=~\"$Deployment_id\"}[$__interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p90 Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by(le, model_name) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=~\"$Deployment_id\"}[$__interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p99 Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, model_name) (rate(vllm:e2e_request_latency_seconds_bucket{model_name=~\"$Deployment_id\"}[$__interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Size Distribution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Input Token Size Distribution",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (le, model_name) (rate(vllm:request_prompt_tokens_bucket{model_name=~\"$Deployment_id\"}[$__interval]))",
     "legendFormat": "{{model_name}} le={{le}}"
    }
   ]
  },
  {
   "title": "Input Token Size p90",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.90, # Calculate the 90th percentile\r\n  sum by(le, model_name) ( # Aggregate the bucket rates, keeping 'le' (bucket boundary) and 'model_name' labels\r\n    rate(\r\n      vllm:request_prompt_tokens_bucket{model_name=~\"$Deployment_id\"}[$__interval] # Get the per-second rate of tokens falling into each bucket\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input Token Size p50",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.50, # Calculate the 50th percentile (median)\r\n  sum by(le, model_name) ( # Aggregate the bucket rates, keeping 'le' (bucket boundary) and 'model_name' labels\r\n    rate(\r\n      vllm:request_prompt_tokens_bucket{model_name=~\"$Deployment_id\"}[$__interval] # Get the per-second rate of tokens falling into each bucket\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input Token Size Avg",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# Calculate the sum of the rate of prompt tokens per second\r\nsum(rate(vllm:prompt_tokens_total{model_name=~\"$Deployment_id\"}[$__interval]))\r\n/\r\n# Divide by the sum of the rate of successful requests per second\r\nsum(rate(vllm:request_success_total{model_name=~\"$Deployment_id\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input Token Size p99",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99, # Calculate the 99th percentile\r\n  sum by(le, model_name) ( # Aggregate the bucket rates, keeping 'le' (bucket boundary) and 'model_name' labels\r\n    rate(\r\n      vllm:request_prompt_tokens_bucket{model_name=~\"$Deployment_id\"}[$__interval] # Get the per-second rate of tokens falling into each bucket\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input Token Over Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true
  },
  {
   "title": "Input Tokens Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "# Calculates the rate of input tokens per second over time\r\nsum by (model_name) (rate(vllm:prompt_tokens_total{model_name=~\"$Deployment_id\"}[$__interval]))",
     "legendFormat": "{{model_name}}"
    }
   ]
  },
  {
   "title": "Input Tokens/Sec Avg",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "#Calculates average prompt tokens per second over the selected time range and Divide by the total number of seconds in the time range (provided by Grafana)\r\nsum(increase(vllm:prompt_tokens_total{model_name=~\"$Deployment_id\"}[$__range]))\r\n/ \r\n$__range_s\r\n\r\n#This is not working, for reference\r\n# Calculates total output tokens over period, divided by total seconds in period\r\n#sum(increase(vllm:generation_tokens_total{model_name=~\"$Deployment_id\"}[$__range]))\r\n#/\r\n#(max_over_time(time()[1s] offset $__range) - min_over_time(time()[1s] offset $__range))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Output Token Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Output Tokens Over Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "# Calculates the rate of output tokens per second over time\r\nsum by (model_name) (rate(vllm:generation_tokens_total{model_name=~\"$Deployment_id\"}[$__interval]))",
     "legendFormat": "{{model_name}}"
    }
   ]
  },
  {
   "title": "Output Tokens/Sec Avg",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 10, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "# Calculates total output tokens over period, divided by total seconds in period\r\nsum(increase(vllm:generation_tokens_total{model_name=~\"$Deployment_id\"}[$__range]))\r\n/\r\n$__range_s # Grafana variable: total seconds in the selected dashboard time range",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}