#set -x
BASH_DIR=$(dirname "${BASH_SOURCE[0]}")
source "$BASH_DIR"/pd_bucket.sh

source ./pd_xpyd/pd_env.sh

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

model_path=/mnt/disk2/hf_models/DeepSeek-R1-BF16-w8afp8-static-no-ste-G2/

export VLLM_GPU_MEMORY_UTILIZATION=0.9
export VLLM_GRAPH_RESERVED_MEM=0.2
export VLLM_GRAPH_PROMPT_RATIO=0

# enable delayed samping on decode
export VLLM_DELAYED_SAMPLING="true"

# params
model_len=8192
max_num_batched_tokens=8192
max_num_seqs=16
input_min=800
input_max=4096
output_max=4096

unset VLLM_PROMPT_BS_BUCKET_MIN VLLM_PROMPT_BS_BUCKET_STEP VLLM_PROMPT_BS_BUCKET_MAX
unset VLLM_PROMPT_SEQ_BUCKET_MIN VLLM_PROMPT_SEQ_BUCKET_STEP VLLM_PROMPT_SEQ_BUCKET_MAX
unset VLLM_DECODE_BS_BUCKET_MIN VLLM_DECODE_BS_BUCKET_STEP VLLM_DECODE_BS_BUCKET_MAX
unset VLLM_DECODE_BLOCK_BUCKET_MIN VLLM_DECODE_BLOCK_BUCKET_STEP VLLM_DECODE_BLOCK_BUCKET_MAX

set_bucketing

export VLLM_PROMPT_BS_BUCKET_MIN=1
export VLLM_PROMPT_BS_BUCKET_STEP=1
export VLLM_PROMPT_BS_BUCKET_MAX=1
export VLLM_PROMPT_SEQ_BUCKET_MIN=1
export VLLM_PROMPT_SEQ_BUCKET_STEP=128
export VLLM_PROMPT_SEQ_BUCKET_MAX=1

#export VLLM_DECODE_BLOCK_BUCKET_MIN=2048
#export VLLM_DECODE_BS_BUCKET_STEP=512
#export VLLM_DECODE_BLOCK_BUCKET_STEP=2048

echo " environments are reseted "

env | grep VLLM_PROMPT_BS
env | grep VLLM_PROMPT_SEQ
env | grep VLLM_DECODE_BS
env | grep VLLM_DECODE_BLOCK

export VLLM_SKIP_WARMUP=True
#unset VLLM_SKIP_WARMUP

export VLLM_DP_SIZE=2
export VLLM_USE_V1=0
export VLLM_DP_MASTER_IP=10.239.129.81
export VLLM_DP_MASTER_PORT=25940
export VLLM_EP_SIZE=16

