name: vllm_intel_ci
job_dirs:
  - ".buildkite/intel_jobs"
run_all_patterns:
  - "docker/Dockerfile"
  - "CMakeLists.txt"
  - "requirements/common.txt"
  - "requirements/xpu.txt"
  - "requirements/build/cuda.txt"
  - "requirements/test/cuda.txt"
  - "setup.py"
  - "csrc/"
  - "cmake/"
run_all_exclude_patterns:
  - "docker/Dockerfile."
  - "csrc/cpu/"
  - "csrc/rocm/"
  - "cmake/hipify.py"
  - "cmake/cpu_extension.cmake"
registries: public.ecr.aws/q9t5s3a7
repositories:
  main: "vllm-ci-test-repo"
  premerge: "vllm-ci-test-repo"
