{
  "name": "gpu_telemetry_canary",
  "github_repo_name": "vllm-project/vllm",
  "job_dirs": [
    ".buildkite/gpu-canary/jobs"
  ],
  "registries": "public.ecr.aws/q9t5s3a7",
  "repositories": {
    "main": "vllm-ci-postmerge-repo",
    "premerge": "vllm-ci-test-repo"
  }
}
