# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
# This file is generated by scripts/generate_helion_kernels.py.
# ruff: noqa
# mypy: ignore-errors
# fmt: off
from __future__ import annotations

import torch
import triton
import triton.language as tl

def _get_num_sm(device: torch.device) -> int:
    return torch.cuda.get_device_properties(device).multi_processor_count


def _default_launcher(
    triton_kernel: object,
    grid: tuple[int, ...],
    *args: object,
    num_warps: int,
    num_stages: int,
    ptx_options: str | None = None,
    launch_cooperative_grid: bool = False,
    **kwargs: object,
) -> object:
    run_kwargs = {
        "grid": grid,
        "warmup": False,
        "num_warps": num_warps,
        "num_stages": num_stages,
        "launch_cooperative_grid": launch_cooperative_grid,
        **kwargs,
    }
    if ptx_options is not None:
        run_kwargs["ptx_options"] = ptx_options
    return triton_kernel.run(*args, **run_kwargs)


def _get_fp8_dtype() -> torch.dtype:
    return torch.float8_e4m3fn


def _get_fp8_min_max() -> tuple[float, float]:
    info = torch.finfo(_get_fp8_dtype())
    return info.min, info.max


def _get_int8_min_max() -> tuple[int, int]:
    info = torch.iinfo(torch.int8)
    return info.min, info.max


def _get_int8_min_scaling_factor() -> float:
    return torch.finfo(torch.float32).eps

_BLOCK_SIZE_0 = tl.constexpr(1)
_BLOCK_SIZE_1 = tl.constexpr(2048)
_BLOCK_SIZE_3 = tl.constexpr(128)
_BLOCK_SIZE_2 = tl.constexpr(16)

@triton.jit
def _triton_rms_norm_per_block_quant(input_1, weight, scale, result, input_1_stride_0, input_1_stride_1, result_stride_0, result_stride_1, scale_stride_0, scale_stride_1, weight_stride_0, epsilon):
    pid_0 = tl.program_id(0)
    offset_0 = pid_0
    indices_0 = offset_0 + tl.zeros([1], tl.int32)
    rms = tl.full([_BLOCK_SIZE_0], 0.0, tl.float32)
    for offset_1 in tl.range(0, 2048, _BLOCK_SIZE_1, flatten=False):
        indices_1 = offset_1 + tl.arange(0, _BLOCK_SIZE_1).to(tl.int32)
        rms_copy = rms
        rms_copy_0 = rms_copy
        load = tl.load(input_1 + (indices_0[:, None] * input_1_stride_0 + indices_1[None, :] * input_1_stride_1), None)
        v_0 = tl.cast(load, tl.float32)
        v_1 = v_0 * v_0
        sum_1 = tl.cast(tl.sum(v_1, 1), tl.float32)
        rms = rms_copy_0 + sum_1
    v_3 = tl.full([], 0.00048828125, tl.float32)
    v_4 = rms * v_3
    v_5 = v_4 + epsilon
    v_6 = tl.rsqrt(v_5)
    iota = tl.arange(0, _BLOCK_SIZE_0)
    v_7 = tl.cast(offset_0, tl.int32)
    v_8 = iota + v_7
    m_blk = v_8[:, None, None]
    tl.debug_barrier()
    for offset_2 in tl.range(0, 16, _BLOCK_SIZE_2, disallow_acc_multi_buffer=False, flatten=False):
        indices_2 = offset_2 + tl.arange(0, _BLOCK_SIZE_2).to(tl.int32)
        for offset_3 in tl.range(0, 128, _BLOCK_SIZE_3):
            indices_3 = offset_3 + tl.arange(0, _BLOCK_SIZE_3).to(tl.int32)
            m_blk_copy = m_blk
            v_6_copy = v_6
            m_blk_copy_0 = m_blk_copy
            v_6_copy_0 = v_6_copy
            subscript = indices_2[:, None]
            v_9 = tl.full([], 128, tl.int32)
            v_10 = tl.cast(subscript * v_9, tl.int32)
            subscript_1 = indices_3[None, :]
            v_11 = v_10 + subscript_1
            n_blk = v_11[None, :, :]
            v_12 = tl.full([], 16, tl.int32)
            v_13 = indices_2 < v_12
            mask = v_13[None, :, None]
            load_1 = tl.load(input_1 + (m_blk_copy_0 * input_1_stride_0 + n_blk * input_1_stride_1), mask, other=0)
            v_14 = tl.cast(load_1, tl.float32)
            w_blk = tl.load(weight + n_blk * weight_stride_0, mask, other=0, eviction_policy='evict_first')
            subscript_4 = v_6_copy_0[:, None, None]
            v_15 = v_14 * subscript_4
            v_16 = tl.cast(v_15, tl.bfloat16)
            v_17 = v_16 * w_blk
            v_18 = tl.abs(v_17)
            amax = tl.cast(tl.max(v_18, 2), tl.bfloat16)
            v_19 = tl.cast(amax, tl.float32)
            v_20 = tl.full([], 0.002232142857142857, tl.float32)
            v_21 = v_19 * v_20
            v_22 = tl.full([], 4.359654017857143e-06, tl.float32)
            v_23 = tl.maximum(v_21, v_22, tl.PropagateNan.ALL)
            tl.store(scale + (indices_0[:, None] * scale_stride_0 + indices_2[None, :] * scale_stride_1), v_23, None)
            subscript_5 = v_23[:, :, None]
            v_24 = tl.cast(v_17, tl.float32)
            v_25 = v_24 / subscript_5
            v_26 = tl.full([], -448.0, tl.float32)
            v_27 = tl.maximum(v_25, v_26, tl.PropagateNan.ALL)
            v_28 = tl.full([], 448.0, tl.float32)
            v_29 = tl.minimum(v_27, v_28, tl.PropagateNan.ALL)
            v_30 = tl.cast(v_29, tl.float8e4nv)
            tl.store(result + (m_blk_copy_0 * result_stride_0 + n_blk * result_stride_1), v_30, mask)

def call(result: torch.Tensor, input: torch.Tensor, weight: torch.Tensor, scale: torch.Tensor, epsilon: float, scale_ub: torch.Tensor | None, residual: torch.Tensor | None, group_size: int, is_scale_transposed: bool, *, _launcher=_default_launcher):
    assert input.ndim == 2
    num_tokens, hidden_size = input.shape
    groups_per_row = scale.shape[1]
    assert hidden_size % group_size == 0 and hidden_size // group_size == groups_per_row
    assert scale.shape[0] == num_tokens
    assert scale.dtype == torch.float32
    if scale.stride(1) > 1:
        assert is_scale_transposed
    fp8_dtype = _get_fp8_dtype()
    assert result.dtype in [fp8_dtype, torch.int8]
    assert result.is_contiguous() and input.is_contiguous()
    if scale_ub is not None:
        assert result.dtype == fp8_dtype
        assert scale_ub.dtype == torch.float32
    assert input.dtype == weight.dtype
    if residual is not None:
        assert residual.dtype == input.dtype
    assert group_size in [64, 128]
    quant_dtype = result.dtype
    qtype_traits_min: int | float
    qtype_traits_max: int | float
    if quant_dtype == torch.int8:
        qtype_traits_min, qtype_traits_max = get_int8_min_max()
        min_scaling_factor = get_int8_min_scaling_factor()
    else:
        qtype_traits_min, qtype_traits_max = _get_fp8_min_max()
        min_scaling_factor = 1.0 / (qtype_traits_max * 512.0)
    qtype_max = float(qtype_traits_max)
    _launcher(_triton_rms_norm_per_block_quant, (num_tokens,), input, weight, scale, result, input.stride(0), input.stride(1), result.stride(0), result.stride(1), scale.stride(0), scale.stride(1), weight.stride(0), epsilon, num_warps=8, num_stages=3)
