# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
import ast
import contextlib
import json
from collections.abc import Sequence
from typing import Any
from xml.parsers.expat import ParserCreate

import regex as re

from vllm.entrypoints.chat_utils import make_tool_call_id
from vllm.entrypoints.openai.chat_completion.protocol import (
    ChatCompletionRequest,
)
from vllm.entrypoints.openai.engine.protocol import (
    DeltaFunctionCall,
    DeltaMessage,
    DeltaToolCall,
    ExtractedToolCallInformation,
    FunctionCall,
    ToolCall,
)
from vllm.logger import init_logger
from vllm.tokenizers import TokenizerLike
from vllm.tool_parsers.abstract_tool_parser import (
    Tool,
    ToolParser,
)
from vllm.tool_parsers.structural_tag_registry import (
    get_enable_structured_outputs_in_reasoning,
    get_model_structural_tag,
)
from vllm.tool_parsers.utils import find_tool_properties

logger = init_logger(__name__)


def _is_valid_function_name(name: str) -> bool:
    """Return True when ``name`` looks like a real function identifier and
    not a stray template token, malformed tag, or freeform text.

    Rejects names that contain template-syntax characters (``{``, ``}``,
    ``<``, ``>``), whitespace, quotes, or are empty.
    """
    if not name:
        return False
    forbidden = set("{}<>\"' \t\n\r")
    return not any(c in forbidden for c in name)


class StreamingXMLToolCallParser:
    """
    Simplified streaming XML tool call parser
    Supports streaming input, parsing, and output
    """

    def __init__(self):
        self.reset_streaming_state()

        # Tool configuration information
        self.tools: list[Tool] | None = None
        self.tool_call_start_token: str = "<tool_call>"
        self.tool_call_end_token: str = "</tool_call>"
        self.function_start_token: str = "<function="
        self.function_end_token: str = "</function>"
        self.parameter_start_token: str = "<parameter="
        self.parameter_end_token: str = "</parameter>"

    def reset_streaming_state(self):
        """Reset streaming parsing state"""

        self.deltas = []
        # When True (delta-by-delta streaming), _process_complete_xml_elements
        # holds off on </parameter> when nothing follows in the buffer yet —
        # that would be ambiguous since more tokens may still arrive.  When
        # False (full output passed at once), an empty lookahead is a
        # genuine end.
        self._streaming_mode: bool = False
        # state for streaming
        self.tool_call_index = 0
        self.current_call_id = None
        self.id_emitted = False
        self.last_completed_call_id = None
        self.current_function_name = None
        self.current_function_open = False
        self.parameters = {}
        self.current_param_name = None
        self.current_param_value = ""
        self.current_param_value_converted = ""
        self.current_param_is_first = False
        self.should_emit_end_newline = False
        self.start_quote_emitted = False

        self.streaming_buffer = ""
        self.last_processed_pos = 0

        self.text_content_buffer = ""

        # state for preprocessing and deferred parsing
        self._pre_inside_parameter = False
        self._pre_param_buffer = ""
        self._pre_current_param_name = None
        self.defer_current_parameter = False
        self.deferred_param_raw_value = ""

        # Depth of LITERAL nested ``<tool_call>``/``<function=...>`` opens
        # encountered inside the current parameter's value.  Each literal
        # opener bumps the depth; each ``</tool_call>``/``</function>``
        # encountered while depth > 0 is also literal (decrements the
        # depth) and must not be treated as a structural close.  Reset
        # to 0 when leaving a parameter.
        self._literal_tag_depth = 0
        # Number of literal tool_call/function open or close events seen
        # in the current ``parse_single_streaming_chunks`` call.  Used to
        # suppress the post-processing structural-close fallback when
        # the chunk contained literal nested-tag events: those events
        # are already handled (escaped) by the preprocess pass and must
        # not trigger ``_end_element`` calls.
        self._literal_events_this_chunk = 0

        # recreate parser
        self.parser = ParserCreate()
        self.setup_parser()

    def parse_single_streaming_chunks(self, xml_chunk: str) -> DeltaMessage:
        """
        Parse single streaming XML chunk and return Delta response
        This is the actual streaming interface that receives chunks
        one by one and maintains internal state

        Args:
            xml_chunk: Single XML chunk string
        Returns:
            DeltaMessage: Contains delta information generated by this chunk,
            returns empty response if no complete elements
        """
        # Record delta count before processing
        initial_delta_count = len(self.deltas)

        # Reset literal-event counter for this chunk: it will be
        # incremented by the preprocess pass whenever it encounters a
        # literal nested ``<tool_call>``/``<function=...>`` open or
        # the matching close inside a parameter value.
        self._literal_events_this_chunk = 0

        self.streaming_buffer += xml_chunk

        found_elements = self._process_complete_xml_elements()

        if found_elements:
            # If complete elements found, check if end events were missed
            # some tags may not have been triggered.  Use structural-aware
            # checks so that </function>/</tool_call> appearing as literal
            # text inside a parameter value (e.g. file content) does NOT
            # trigger a spurious close that emits a duplicate '}' or ''.
            # When ``_literal_tag_depth > 0`` we are still inside a
            # literal nested ``<tool_call>``/``<function=...>`` block in
            # the current parameter's value — the chunk's `</function>`
            # or `</tool_call>` matches a literal opener, not a real
            # structural close, so skip the fallback close events.
            try:
                # Skip the fallback close events when this chunk
                # contained any literal nested-tag event: those
                # ``</function>``/``</tool_call>`` strings are matched
                # to literal openers in the param value and have
                # already been escaped — firing ``_end_element`` here
                # would prematurely close the OUTER parameter and
                # truncate its value.
                literals_in_chunk = self._literal_events_this_chunk > 0
                if (
                    self.current_call_id is not None
                    and not literals_in_chunk
                    and self._literal_tag_depth == 0
                    and self._chunk_has_structural_function_end(xml_chunk)
                    and self.current_function_open
                ):
                    if self.current_param_name:
                        self._end_element("parameter")
                    if self.current_function_name:
                        self._end_element("function")
                if (
                    self.current_call_id is not None
                    and not literals_in_chunk
                    and self._literal_tag_depth == 0
                    and self._chunk_has_structural_tool_call_end(xml_chunk)
                ):
                    if self.current_param_name:
                        self._end_element("parameter")
                    if self.current_function_open:
                        self._end_element("function")
                    self._end_element("tool_call")
            except Exception as e:
                logger.warning("Error with fallback parsing: %s", e)
            # Merge newly generated deltas into single response
            result_delta = self._merge_new_deltas_to_single_response(
                initial_delta_count
            )
            return result_delta
        else:
            # No complete elements, check if there's unoutput text content
            if self.text_content_buffer:
                # Output buffered text content
                text_delta = DeltaMessage(content=self.text_content_buffer)
                self._emit_delta(text_delta)
                # Clear buffer to avoid duplicate output
                self.text_content_buffer = ""
                return text_delta

            # If this chunk contains structural end tags but wasn't
            # triggered by parser, manually complete end events. Only
            # execute when still on the same call as when entered, to
            # prevent accidentally closing new calls in multi-<tool_call>
            # scenarios.  Also skip when ``_literal_tag_depth > 0``: the
            # chunk's `</function>`/`</tool_call>` matches a literal
            # opener inside the current parameter's value.
            if (
                self.current_call_id is not None
                and self._literal_tag_depth == 0
                and (
                    self._chunk_has_structural_function_end(xml_chunk)
                    or self._chunk_has_structural_tool_call_end(xml_chunk)
                )
            ):
                if self.current_param_name:
                    self._end_element("parameter")
                if (
                    self._chunk_has_structural_function_end(xml_chunk)
                    and self.current_function_name
                ):
                    self._end_element("function")
                if self._chunk_has_structural_tool_call_end(xml_chunk):
                    self._end_element("tool_call")
                # Return the merged delta result generated by this fallback
                result_delta = self._merge_new_deltas_to_single_response(
                    initial_delta_count
                )
                return result_delta

            # No complete elements, return empty response
            return DeltaMessage(content=None)

    def _escape_xml_special_chars(self, text: str) -> str:
        """
        Escape XML special characters
        Args:
            text: Original text
        Returns:
            Escaped text
        """
        xml_escapes = {
            "&": "&amp;",
            "<": "&lt;",
            ">": "&gt;",
            '"': "&quot;",
            "'": "&apos;",
        }

        for char, escape in xml_escapes.items():
            text = text.replace(char, escape)

        return text

    def _is_structural_tag_position(self) -> bool:
        """Return True when the current element is at a structural position.

        A structural opening tag (e.g. <parameter=...>) must appear at the
        beginning of a line in the raw output — i.e. the character
        immediately before it in the streaming buffer is a newline (or it
        is at position 0).  Opening tags inside parameter content (e.g.
        '"<parameter=query>"') are preceded by a non-newline character
        such as a quote.
        """
        if self.last_processed_pos == 0:
            return True
        return self.streaming_buffer[self.last_processed_pos - 1] == "\n"

    def _get_valid_param_names(self) -> set[str] | None:
        """Return the set of parameter names defined in the schema for the
        current function, or None when the schema is not available.

        Used to filter structural-looking <parameter=NAME> tokens that
        appear as literal text inside a parameter value (e.g. Jinja2
        templates, test fixtures, or files that document the tool-call
        format).
        """
        if not self.tools or not self.current_function_name:
            return None
        props = find_tool_properties(self.tools, self.current_function_name)
        return set(props.keys()) if props else None

    def _is_already_emitted_param(self, name: str) -> bool:
        """Return True when ``name`` has already appeared as a parameter
        of the current tool call (either fully closed or currently open).

        A ``<parameter=NAME>`` whose NAME is already used for the same
        tool is almost always literal text inside another parameter's
        value (e.g. a parser fixture or a file that documents the
        tool-call format).  Treating it as a real structural opening
        causes silent value truncation and spurious extra params.
        """
        if name == self.current_param_name:
            return True
        return name in self.parameters

    def _is_structural_closing_tag(self, chunk: str) -> bool:
        """Return True when a closing tag at the current buffer position is
        a real structural delimiter rather than literal text content.

        A closing tag is structural when the text that follows it in the
        streaming buffer (after stripping leading whitespace) begins with
        another structural token or is empty (end of buffered output).

        When the schema is available, a following <parameter=NAME> is only
        considered structural if NAME is a known parameter of the current
        function.  This prevents literal lines like ``<parameter=new_string>``
        in file content from being mistaken for real structural boundaries.
        """
        after_pos = self.last_processed_pos + len(chunk)
        rest = self.streaming_buffer[after_pos:].lstrip()

        structural_param_follows = False
        if rest.startswith(self.parameter_start_token):
            valid_names = self._get_valid_param_names()
            name_start = len(self.parameter_start_token)
            name_end = rest.find(">", name_start)
            if name_end != -1:
                candidate = rest[name_start:name_end]
                if valid_names is not None:
                    structural_param_follows = (
                        candidate in valid_names
                        and not self._is_already_emitted_param(candidate)
                    )
                else:
                    # Fallback (no schema): trust the name unless it is a
                    # repeat of the current/already-emitted param, which
                    # is almost always a literal in a parser fixture.
                    structural_param_follows = not self._is_already_emitted_param(
                        candidate
                    )

        # Return True when rest is an incomplete prefix of a structural
        # closing token (e.g. rest="</" when "</function>" hasn't fully
        # arrived yet). The empty-rest case is handled by the deferral in
        # _process_complete_xml_elements; this guards against the
        # partial-tag scenario where the deferral does not fire (rest is
        # non-empty) but the token is still incomplete.
        is_partial_structural_prefix = any(
            tok.startswith(rest)
            for tok in (
                self.parameter_end_token,
                self.function_end_token,
                self.tool_call_end_token,
            )
        )

        return (
            not rest
            or is_partial_structural_prefix
            or structural_param_follows
            or rest.startswith(self.parameter_end_token)
            or rest.startswith(self.function_end_token)
            or rest.startswith(self.tool_call_end_token)
        )

    def _chunk_has_structural_function_end(self, chunk: str) -> bool:
        """Return True if `chunk` contains a structural </function> tag.

        A structural </function> is followed (after optional whitespace)
        by </tool_call> or end-of-string — not inside parameter content
        such as a file whose body contains '</function>'.
        """
        search = 0
        token = self.function_end_token
        end_token = self.tool_call_end_token
        while True:
            idx = chunk.find(token, search)
            if idx == -1:
                return False
            rest = chunk[idx + len(token) :].lstrip()
            if not rest or rest.startswith(end_token):
                return True
            search = idx + len(token)

    def _chunk_has_structural_tool_call_end(self, chunk: str) -> bool:
        """Return True if `chunk` contains a structural </tool_call> tag."""
        search = 0
        token = self.tool_call_end_token
        start_token = self.tool_call_start_token
        while True:
            idx = chunk.find(token, search)
            if idx == -1:
                return False
            rest = chunk[idx + len(token) :].lstrip()
            if not rest or rest.startswith(start_token):
                return True
            search = idx + len(token)

    def _process_complete_xml_elements(self) -> bool:
        """
        Process complete XML elements in buffer

        Returns:
            bool: Whether complete elements were found and processed
        """
        found_any = False

        while self.last_processed_pos < len(self.streaming_buffer):
            # Find next complete xml element
            element, end_pos = self._find_next_complete_element(self.last_processed_pos)
            if element is None:
                # No complete element found, wait for more data
                break

            # In streaming mode, hold off on </parameter> when nothing
            # follows in the buffer yet.  We need the lookahead to
            # distinguish a real structural close (followed by
            # </function> or a schema-known <parameter=NAME>) from
            # literal text content that happens to be ``</parameter>`` on
            # its own line (e.g. Jinja2 template files). When not in
            # _pre_inside_parameter mode the SAX-level decision is made
            # here; skip for now and re-evaluate on the next delta.
            if (
                self._streaming_mode
                and element == self.parameter_end_token
                and self.current_param_name is not None
                and not self._pre_inside_parameter
                and not self.streaming_buffer[end_pos:].lstrip()
            ):
                break

            # Check if this element should be skipped
            if self._should_skip_element(element):
                self.last_processed_pos = end_pos
                continue

            # Found complete XML element, process it
            try:
                preprocessed_element = self._preprocess_xml_chunk(element)
                # Check if a new tool_call starts and we have buffered text content
                if (
                    preprocessed_element.strip().startswith("<tool_call>")
                    or preprocessed_element.strip().startswith("<function name=")
                ) and self.text_content_buffer:
                    # Output previously collected text content first
                    text_delta = DeltaMessage(content=self.text_content_buffer)
                    self._emit_delta(text_delta)
                    # Clear buffer for potential subsequent text content
                    self.text_content_buffer = ""

                # If a new tool_call starts and
                # there are already completed tool_calls
                if (
                    preprocessed_element.strip().startswith("<tool_call>")
                    and self.tool_call_index > 0
                    and self.current_call_id
                ):
                    # Reset parser state but preserve generated deltas
                    if self.current_param_name:
                        self._end_element("parameter")
                    if self.current_function_open or self.current_function_name:
                        self._end_element("function")
                    # Output final tool_call tail delta
                    final_delta = DeltaMessage(
                        role=None,
                        content=None,
                        reasoning=None,
                        tool_calls=[
                            DeltaToolCall(
                                index=self.tool_call_index - 1,
                                id=self._get_call_id_for_delta(),
                                type="function",
                                function=DeltaFunctionCall(name=None, arguments=""),
                            )
                        ],
                    )
                    self._emit_delta(final_delta)
                    # Reset XML parser and current call state
                    self._reset_xml_parser_after_tool_call()
                # Parse preprocessed element
                self.parser.Parse(preprocessed_element, False)
                found_any = True

            except Exception as e:
                logger.warning("Error when parsing XML elements: %s", e)

            # Update processed position
            self.last_processed_pos = end_pos

        # Flush any text accumulated AFTER the last </tool_call> processed
        # in this batch. Without this, trailing free text that arrives in
        # the SAME delta as the closing </tool_call> (MTP / speculative
        # decoding) is buffered but never emitted — and is lost entirely
        # if EOS comes before any subsequent delta.
        if found_any and self.text_content_buffer and self.current_call_id is None:
            text_delta = DeltaMessage(content=self.text_content_buffer)
            self._emit_delta(text_delta)
            self.text_content_buffer = ""

        return found_any

    def _should_skip_element(self, element: str) -> bool:
        """
        Determine whether an element should be skipped

        Args:
            element: Element to evaluate

        Returns:
            bool: True means should skip, False means should process
        """

        # If it's a tool_call XML tag, don't skip
        if (
            element.startswith(self.tool_call_start_token)
            or element.startswith(self.function_start_token)
            or element.startswith(self.parameter_start_token)
        ):
            return False

        # If currently not parsing tool calls and not blank,
        # collect this text instead of skipping
        # Only process other XML elements after tool_call appears,
        # otherwise treat as plain text
        if self.current_call_id is None and element:
            # Collect text content to buffer
            self.text_content_buffer += element
            return True  # Still skip, but content has been collected

        # If currently parsing tool calls,
        # this might be parameter value, don't skip
        if self.current_call_id is not None:
            return False

        # Skip blank content
        return not element

    def _find_next_complete_element(self, start_pos: int) -> tuple[str | None, int]:
        """
        Find next complete XML element from specified position

        Args:
            start_pos: Position to start searching

        Returns:
            (Complete element string, element end position),
            returns (None, start_pos) if no complete element found
        """
        buffer = self.streaming_buffer[start_pos:]

        if not buffer:
            return None, start_pos

        if buffer.startswith("<"):
            # Need to ensure no new < appears,
            # find the nearest one between < and >
            tag_end = buffer.find("<", 1)
            tag_end2 = buffer.find(">", 1)
            if tag_end != -1 and tag_end2 != -1:
                # Next nearest is <
                if tag_end < tag_end2:
                    return buffer[:tag_end], start_pos + tag_end
                # Next nearest is >, means found XML element
                else:
                    return buffer[: tag_end2 + 1], start_pos + tag_end2 + 1
            elif tag_end != -1:
                return buffer[:tag_end], start_pos + tag_end
            elif tag_end2 != -1:
                return buffer[: tag_end2 + 1], start_pos + tag_end2 + 1
            else:
                # If currently not parsing tool calls (entering a tool_call),
                # check if starts with <tool_call> or <function=
                if self.current_call_id is None:
                    # Check if might be start of <tool_call>
                    if buffer == "<tool_call>"[: len(buffer)]:
                        # Might be start of <tool_call>, wait for more data
                        return None, start_pos
                    elif (
                        buffer.startswith("<function=")
                        or buffer == "<function="[: len(buffer)]
                    ):
                        # Might be start of <function=, wait for more data
                        # to get the complete function tag
                        return None, start_pos
                    else:
                        # Not start of <tool_call> or <function=, treat as text
                        return buffer, start_pos + len(buffer)
                else:
                    # When parsing tool calls,
                    # wait for more data to get complete tag
                    return None, start_pos
        else:
            # Find text content (until next < or buffer end)
            next_tag_pos = buffer.find("<")
            if next_tag_pos != -1:
                # Found text content
                text_content = buffer[:next_tag_pos]
                return text_content, start_pos + next_tag_pos
            else:
                # Buffer end is all text, process
                # (no longer wait for more data)
                remaining = buffer
                return remaining, start_pos + len(remaining)

    def _merge_new_deltas_to_single_response(self, initial_count: int) -> DeltaMessage:
        """
        Merge newly generated deltas from this processing
        into a single DeltaMessage

        Args:
            initial_count: Delta count before processing

        Returns:
            Merged DeltaMessage containing all newly generated delta information
        """
        if len(self.deltas) <= initial_count:
            return DeltaMessage(content=None)

        # Get newly generated deltas
        new_deltas = self.deltas[initial_count:]

        if len(new_deltas) == 1:
            # Only one new delta, return directly
            return new_deltas[0]

        # Merge multiple new deltas
        merged_tool_calls: list[DeltaToolCall] = []
        merged_content: str = ""

        for delta in new_deltas:
            if delta.content:
                merged_content += delta.content
            if delta.tool_calls:
                # For tool_calls, we need to intelligently merge arguments
                for tool_call in delta.tool_calls:
                    # Find if there's already a tool_call with the same index
                    existing_call = None
                    for existing in merged_tool_calls:
                        if existing.index == tool_call.index:
                            existing_call = existing
                            break

                    if existing_call and existing_call.function:
                        # Merge to existing tool_call
                        if tool_call.function and tool_call.function.name:
                            existing_call.function.name = tool_call.function.name
                        if (
                            tool_call.function
                            and tool_call.function.arguments is not None
                        ):
                            if existing_call.function.arguments is None:
                                existing_call.function.arguments = ""

                            # For streaming JSON parameters,
                            # simply concatenate in order
                            new_args = tool_call.function.arguments
                            existing_call.function.arguments += new_args
                        if tool_call.type:
                            existing_call.type = tool_call.type
                    else:
                        # Add new tool_call
                        merged_tool_calls.append(tool_call)

        return DeltaMessage(
            content=merged_content if merged_content else None,
            tool_calls=merged_tool_calls,
        )

    def _preprocess_xml_chunk(self, chunk: str) -> str:
        """
        Preprocess XML chunk, handle non-standard formats,
        and escape special characters

        Args:
            chunk: Original XML chunk

        Returns:
            Processed XML chunk
        """

        # Check if this is a tool_call related element
        is_tool_call = False
        if chunk.startswith(self.tool_call_start_token) or chunk.startswith(
            self.tool_call_end_token
        ):
            is_tool_call = True
        if chunk.startswith(self.function_start_token) or chunk.startswith(
            self.function_end_token
        ):
            is_tool_call = True
        if chunk.startswith(self.parameter_start_token) or chunk.startswith(
            self.parameter_end_token
        ):
            is_tool_call = True
        # Handle <function=name> format -> <function name="name">
        processed = re.sub(r"<function=([^>]+)>", r'<function name="\1">', chunk)
        # Handle <parameter=name> format -> <parameter name="name">
        processed = re.sub(r"<parameter=([^>]+)>", r'<parameter name="\1">', processed)

        original_chunk = chunk
        # If in parameter value accumulation mode
        if self._pre_inside_parameter:
            # Parameter end: output accumulated raw text
            # safely then return </parameter>
            if processed.startswith("</parameter>"):
                body_text = self._pre_param_buffer
                # Trigger deferred parsing mode
                # literal_eval+json output in end_element
                self.defer_current_parameter = True
                self.deferred_param_raw_value = body_text
                # Clean up state
                self._pre_inside_parameter = False
                self._pre_param_buffer = ""
                self._pre_current_param_name = None
                safe_text = self._escape_xml_special_chars(body_text)
                return f"{safe_text}</parameter>"
            else:
                # If this is the first block of content after entering parameter
                # evaluate if deferred parsing is needed;
                # If not needed, exit accumulation mode
                # and pass through directly
                if self._pre_param_buffer == "":
                    # Get current parameter type
                    param_type = (
                        self._get_param_type(self._pre_current_param_name)
                        if self._pre_current_param_name
                        else "string"
                    )
                    # Container types always need deferred parsing so the
                    # full value is available for json.loads /
                    # ast.literal_eval — even when the first streaming
                    # token is just "\n".
                    is_object_type = param_type == "object"
                    is_complex_type = (
                        param_type in ["array", "arr", "sequence"]
                        or param_type.startswith("dict")
                        or param_type.startswith("list")
                    )
                    # Boolean also needs deferral: streaming "t" as the
                    # first char would otherwise be converted to False and
                    # emit "false", shadowing the real "true" that follows.
                    is_bool_type = param_type in ["boolean", "bool", "binary"]
                    # Numeric types need deferral too: a nullable
                    # parameter rendered as the literal "None" (Qwen3.5
                    # template) or "null" (Qwen3.6 template) flips from
                    # the partial-string fallback to JSON ``null`` only
                    # when the FULL value is in.  Without deferral the
                    # diff-based char emission would interleave the
                    # partial string ("Non") with the JSON literal
                    # ("null") and produce invalid output ("Nonl").
                    is_numeric_type = (
                        param_type.startswith("int")
                        or param_type.startswith("uint")
                        or param_type.startswith("long")
                        or param_type.startswith("short")
                        or param_type.startswith("unsigned")
                        or param_type.startswith("num")
                        or param_type.startswith("float")
                    )

                    # Nullable string params (``anyOf: [string, null]``)
                    # must defer too: the literal ``null`` / ``None`` is
                    # only recognisable when the full value is in.
                    # Without deferral, the streaming string path emits
                    # ``"`` + chars + ``"`` and the literal stays
                    # quoted.
                    is_nullable_string = param_type in [
                        "string",
                        "str",
                        "text",
                        "varchar",
                        "char",
                        "enum",
                    ] and self._param_allows_null(self._pre_current_param_name)
                    need_defer = (
                        is_complex_type
                        or is_object_type
                        or is_bool_type
                        or is_numeric_type
                        or is_nullable_string
                    )

                    if not need_defer:
                        # No need for deferred parsing,
                        # exit parameter mode directly
                        self._pre_inside_parameter = False
                        return self._escape_xml_special_chars(original_chunk)
                self._pre_param_buffer += original_chunk
                return ""

        # When a parameter value is being streamed (SAX state says we are
        # inside a <parameter>), structural-looking tokens that arrive as
        # subsequent elements are literal text — e.g. a file whose content
        # describes the tool-call format.  Escape them unless they are
        # genuine structural delimiters.
        if self.current_param_name is not None:
            if chunk.startswith(self.tool_call_start_token) or chunk.startswith(
                self.function_start_token
            ):
                # Opening tool_call/function tags are always literal inside
                # a parameter value.  Track nesting depth so that the
                # matching ``</function>`` / ``</tool_call>`` is also
                # treated as literal even when its lookahead would
                # otherwise satisfy the structural heuristic.
                self._literal_tag_depth += 1
                self._literal_events_this_chunk += 1
                return self._escape_xml_special_chars(chunk)
            if chunk.startswith(self.parameter_start_token):
                # A structural <parameter=NAME> always follows a newline in
                # the buffer.  When a schema is available, also require
                # NAME to be a known parameter of the current function so
                # that literal ``<parameter=new_string>`` inside file
                # content is treated as text.  A NAME already emitted
                # for this tool (or equal to the param currently being
                # parsed) is also literal text — a parser fixture or a
                # file that documents the tool-call format.
                if not self._is_structural_tag_position():
                    return self._escape_xml_special_chars(chunk)
                name_start = len(self.parameter_start_token)
                name_end = chunk.find(">", name_start)
                if name_end != -1:
                    candidate = chunk[name_start:name_end]
                    if self._is_already_emitted_param(candidate):
                        return self._escape_xml_special_chars(chunk)
                    valid_names = self._get_valid_param_names()
                    if valid_names is not None and candidate not in valid_names:
                        return self._escape_xml_special_chars(chunk)
            if (
                chunk.startswith(self.parameter_end_token)
                or chunk.startswith(self.function_end_token)
                or chunk.startswith(self.tool_call_end_token)
            ):
                # Inside a literal nested tool_call/function (depth > 0),
                # any closing tag pairs with the literal opener and is
                # itself literal — regardless of what the lookahead says.
                # ``</parameter>`` does not affect depth (parameters do
                # not nest in the Qwen format).
                if self._literal_tag_depth > 0:
                    if chunk.startswith(self.function_end_token) or (
                        chunk.startswith(self.tool_call_end_token)
                    ):
                        self._literal_tag_depth -= 1
                        self._literal_events_this_chunk += 1
                    else:
                        # Literal `</parameter>` inside a nested literal
                        # block — count it as a literal event so the
                        # post-processing fallback knows the chunk
                        # contained literals and skips spurious closes.
                        self._literal_events_this_chunk += 1
                    return self._escape_xml_special_chars(chunk)
                if not self._is_structural_closing_tag(chunk):
                    return self._escape_xml_special_chars(chunk)

        # Parameter start: enable accumulation
        if processed.startswith("<parameter name="):
            m = re.match(r'<parameter name="([^"]+)">', processed)
            if m:
                self._pre_current_param_name = m.group(1)
            self._pre_inside_parameter = True
            self._pre_param_buffer = ""
            return processed

        # If processed doesn't contain special_token, escape processed
        # This is because XML parsing encounters special characters
        # and reports errors, so escaping is needed
        if not is_tool_call:
            processed = self._escape_xml_special_chars(processed)
        return processed

    def _emit_delta(self, delta: DeltaMessage):
        """Emit Delta response (streaming output)"""
        self.deltas.append(delta)

    def _get_call_id_for_delta(self) -> str | None:
        if not self.id_emitted:
            self.id_emitted = True
            return self.current_call_id
        return None

    def _auto_close_open_parameter_if_needed(self, incoming_tag: str | None = None):
        """Before starting to process new elements,
        if there are unclosed tags from before,
        automatically complete their endings to the parser.
        - If there are unclosed parameters,
        it's equivalent to feeding `</parameter>`
        - When about to start a new function or tool_call,
        if there are unclosed functions, complete `</function>`.
        - When about to start a new tool_call,
        if there are unclosed tool_calls, complete `</tool_call>`.
        """
        # First close unclosed parameters
        if self.current_param_name:
            self._end_element("parameter")

        # If about to start new function or tool_call,
        # and there are unclosed functions, close function first
        if incoming_tag in ("function", "tool_call") and self.current_function_name:
            self._end_element("function")

        # If about to start new tool_call,
        # and there are unclosed tool_calls, close tool_call first
        if incoming_tag == "tool_call" and self.current_call_id:
            self._end_element("tool_call")

    def _start_element(self, name: str, attrs: dict[str, str]):
        """Handle XML start element events"""

        if name == "root":
            return

        if name == "tool_call":
            # Before opening new tool_call,
            # automatically complete previous unclosed tags
            self._auto_close_open_parameter_if_needed("tool_call")

            self.parameters = {}
            self.current_call_id = make_tool_call_id()
            self.current_param_is_first = True
            self.tool_call_index += 1
        elif name.startswith("function") or (name == "function"):
            # If missing tool_call, manually complete
            if not self.current_call_id:
                self._start_element("tool_call", {})
            # Before opening new function,
            # automatically complete previous unclosed tags (parameter/function)
            self._auto_close_open_parameter_if_needed("function")
            function_name = self._extract_function_name(name, attrs)
            self.current_function_name = function_name
            self.current_function_open = True
            if function_name:
                delta = DeltaMessage(
                    tool_calls=[
                        DeltaToolCall(
                            index=self.tool_call_index - 1,
                            id=self._get_call_id_for_delta(),
                            type="function",
                            function=DeltaFunctionCall(
                                name=function_name, arguments=""
                            ),
                        )
                    ]
                )
                self._emit_delta(delta)
        elif name.startswith("parameter") or (name == "parameter"):
            # If previous parameter hasn't ended normally,
            # complete its end first, then start new parameter
            self._auto_close_open_parameter_if_needed("parameter")
            param_name = self._extract_parameter_name(name, attrs)
            self.current_param_name = param_name
            self.current_param_value = ""
            self.current_param_value_converted = ""
            self.start_quote_emitted = False  # Reset start quote flag

            # Only output parameter name and colon,
            # don't output quotes
            # decide after parameter value type is determined
            if param_name:
                if not self.parameters:
                    # First parameter
                    # start JSON, only output parameter name and colon
                    json_start = f'{{"{param_name}": '
                    delta = DeltaMessage(
                        tool_calls=[
                            DeltaToolCall(
                                index=self.tool_call_index - 1,
                                id=self._get_call_id_for_delta(),
                                type="function",
                                function=DeltaFunctionCall(
                                    name=None, arguments=json_start
                                ),
                            )
                        ]
                    )
                    self._emit_delta(delta)
                    self.current_param_is_first = True
                else:
                    # Subsequent parameters
                    # add comma and parameter name, no quotes
                    json_continue = f', "{param_name}": '
                    delta = DeltaMessage(
                        tool_calls=[
                            DeltaToolCall(
                                index=self.tool_call_index - 1,
                                id=self._get_call_id_for_delta(),
                                type="function",
                                function=DeltaFunctionCall(
                                    name=None, arguments=json_continue
                                ),
                            )
                        ]
                    )
                    self._emit_delta(delta)
                    self.current_param_is_first = False

    def _char_data(self, data: str):
        """Handle XML character data events"""
        if data and self.current_param_name:
            # If preprocessing stage determines deferred parsing is needed,
            # only cache character data, no streaming output
            if self.defer_current_parameter:
                original_data = data
                if self.should_emit_end_newline:
                    original_data = "\n" + original_data
                    self.should_emit_end_newline = False
                if original_data.endswith("\n"):
                    self.should_emit_end_newline = True
                    original_data = original_data[:-1]
                self.current_param_value += original_data
                return

            param_type = self._get_param_type(self.current_param_name)

            # Check if this is the first time receiving data for this parameter
            # If this is the first packet of data and starts with \n, remove \n
            if not self.current_param_value and data.startswith("\n"):
                data = data[1:]

            # Output start quote for string type (if not already output)
            if (
                param_type in ["string", "str", "text", "varchar", "char", "enum"]
                and not self.start_quote_emitted
            ):
                quote_delta = DeltaMessage(
                    tool_calls=[
                        DeltaToolCall(
                            index=self.tool_call_index - 1,
                            id=self._get_call_id_for_delta(),
                            type="function",
                            function=DeltaFunctionCall(name=None, arguments='"'),
                        )
                    ]
                )
                self._emit_delta(quote_delta)
                self.start_quote_emitted = True

            if not data:
                return

            original_data = data
            # Delay output of trailing newline
            if self.should_emit_end_newline:
                original_data = "\n" + original_data
                self.should_emit_end_newline = False
            if original_data.endswith("\n"):
                self.should_emit_end_newline = True
                original_data = original_data[:-1]
            self.current_param_value += original_data

            # convert parameter value by param_type
            converted_value = self._convert_param_value(
                self.current_param_value, param_type
            )
            output_data = self._convert_for_json_streaming(converted_value, param_type)

            delta_data = output_data[len(self.current_param_value_converted) :]
            self.current_param_value_converted = output_data

            delta = DeltaMessage(
                tool_calls=[
                    DeltaToolCall(
                        index=self.tool_call_index - 1,
                        id=self._get_call_id_for_delta(),
                        type="function",
                        function=DeltaFunctionCall(name=None, arguments=delta_data),
                    )
                ]
            )
            self._emit_delta(delta)

    def _end_element(self, name: str):
        """Handle XML end element events"""

        if name == "root":
            return

        # If function or tool_call ends and there are still unclosed parameters,
        # complete parameter end first
        if (
            name.startswith("function") or name == "function" or name == "tool_call"
        ) and self.current_param_name:
            self._auto_close_open_parameter_if_needed()

        if (
            name.startswith("parameter") or name == "parameter"
        ) and self.current_param_name:
            # End current parameter; reset literal-tag depth tracker
            # since we are leaving the param's value scope.
            self._literal_tag_depth = 0
            param_name = self.current_param_name
            param_value = self.current_param_value

            # If in deferred parsing mode,
            # perform overall parsing on raw content
            # accumulated in preprocessing stage and output once
            if self.defer_current_parameter:
                raw_text = (
                    self.deferred_param_raw_value
                    if self.deferred_param_raw_value
                    else param_value
                )
                parsed_value: Any = None
                output_arguments: str | None = None
                if self.should_emit_end_newline:
                    raw_for_parse = raw_text + "\n"
                else:
                    raw_for_parse = raw_text
                # Nullable-string short-circuit: when the schema is
                # ``anyOf: [string, null]``, ``"null"`` and Python's
                # ``"None"`` map to JSON null.  Any other value is
                # kept verbatim as a string — never parsed as int,
                # float, JSON, etc., even if it LOOKS like one.
                _param_type_for_check = self._get_param_type(param_name)
                if _param_type_for_check in [
                    "string",
                    "str",
                    "text",
                    "varchar",
                    "char",
                    "enum",
                ] and self._param_allows_null(param_name):
                    if raw_for_parse.strip().lower() in ("null", "none"):
                        parsed_value = None
                        output_arguments = "null"
                    else:
                        parsed_value = raw_for_parse
                        output_arguments = json.dumps(raw_for_parse, ensure_ascii=False)
                    delta = DeltaMessage(
                        tool_calls=[
                            DeltaToolCall(
                                index=self.tool_call_index - 1,
                                id=self._get_call_id_for_delta(),
                                type="function",
                                function=DeltaFunctionCall(
                                    name=None, arguments=output_arguments
                                ),
                            )
                        ]
                    )
                    self._emit_delta(delta)
                    self.parameters[param_name] = parsed_value
                    self.current_param_name = None
                    self.current_param_value = ""
                    self.current_param_value_converted = ""
                    self.start_quote_emitted = False
                    self.should_emit_end_newline = False
                    self.defer_current_parameter = False
                    self.deferred_param_raw_value = ""
                    return
                raw_lower = raw_for_parse.strip().lower()
                # Handle JSON literals that ast.literal_eval cannot parse
                # (true/false/null are JSON, not Python).
                if raw_lower == "null":
                    parsed_value = None
                    output_arguments = "null"
                elif raw_lower == "true":
                    parsed_value = True
                    output_arguments = "true"
                elif raw_lower == "false":
                    parsed_value = False
                    output_arguments = "false"
                else:
                    # Try JSON first: handles arrays/objects that use JSON
                    # native tokens (true, false, null) which
                    # ast.literal_eval cannot parse.
                    try:
                        parsed_value = json.loads(raw_for_parse)
                        # A model trained with a buggy template
                        # (json.dumps(str(dict))) may output a JSON-encoded
                        # Python repr like "\"{'k': 'v'}\"". json.loads
                        # returns a str in that case — try one more level.
                        if isinstance(parsed_value, str):
                            try:
                                parsed_value = ast.literal_eval(parsed_value)
                            except (ValueError, SyntaxError, TypeError):
                                with contextlib.suppress(
                                    json.JSONDecodeError, ValueError
                                ):
                                    parsed_value = json.loads(parsed_value)
                        output_arguments = json.dumps(parsed_value, ensure_ascii=False)
                    except (json.JSONDecodeError, ValueError):
                        try:
                            parsed_value = ast.literal_eval(raw_for_parse)
                            # A model trained with a buggy template
                            # (json.dumps(str(dict))) may output a
                            # JSON-encoded Python repr like "{'k': 'v'}".
                            # ast.literal_eval returns a str in that
                            # case — try one more level.
                            if isinstance(parsed_value, str):
                                try:
                                    parsed_value = ast.literal_eval(parsed_value)
                                except (
                                    ValueError,
                                    SyntaxError,
                                    TypeError,
                                ):
                                    with contextlib.suppress(
                                        json.JSONDecodeError, ValueError
                                    ):
                                        parsed_value = json.loads(parsed_value)
                            output_arguments = json.dumps(
                                parsed_value, ensure_ascii=False
                            )
                        except (ValueError, SyntaxError, TypeError):
                            # Fallback: output as string as-is
                            output_arguments = json.dumps(raw_text, ensure_ascii=False)
                            parsed_value = raw_text

                delta = DeltaMessage(
                    tool_calls=[
                        DeltaToolCall(
                            index=self.tool_call_index - 1,
                            id=self._get_call_id_for_delta(),
                            type="function",
                            function=DeltaFunctionCall(
                                name=None, arguments=output_arguments
                            ),
                        )
                    ]
                )
                self._emit_delta(delta)

                # Clean up and store
                self.should_emit_end_newline = False
                self.parameters[param_name] = parsed_value
                self.current_param_name = None
                self.current_param_value = ""
                self.current_param_value_converted = ""
                self.start_quote_emitted = False
                self.defer_current_parameter = False
                self.deferred_param_raw_value = ""
                return

            param_type = self._get_param_type(param_name)

            # convert complete parameter value by param_type
            converted_value = self._convert_param_value(param_value, param_type)

            # Decide whether to add end quote based on parameter type
            if param_type in ["string", "str", "text", "varchar", "char", "enum"]:
                # For empty string parameters, need special handling
                if not param_value and not self.start_quote_emitted:
                    # No start quote output,
                    # directly output complete empty string
                    delta = DeltaMessage(
                        tool_calls=[
                            DeltaToolCall(
                                index=self.tool_call_index - 1,
                                id=self._get_call_id_for_delta(),
                                type="function",
                                function=DeltaFunctionCall(name=None, arguments='""'),
                            )
                        ]
                    )
                    self._emit_delta(delta)
                else:
                    # Non-empty parameter value, output end quote
                    delta = DeltaMessage(
                        tool_calls=[
                            DeltaToolCall(
                                index=self.tool_call_index - 1,
                                id=self._get_call_id_for_delta(),
                                type="function",
                                function=DeltaFunctionCall(name=None, arguments='"'),
                            )
                        ]
                    )
                    self._emit_delta(delta)

            self.should_emit_end_newline = False
            # Store converted value
            self.parameters[param_name] = converted_value
            self.current_param_name = None
            self.current_param_value = ""
            self.current_param_value_converted = ""
            self.start_quote_emitted = False

        elif name.startswith("function") or name == "function":
            # if there are parameters, close JSON object
            if self.parameters:
                delta = DeltaMessage(
                    tool_calls=[
                        DeltaToolCall(
                            index=self.tool_call_index - 1,
                            id=self._get_call_id_for_delta(),
                            type="function",
                            function=DeltaFunctionCall(name=None, arguments="}"),
                        )
                    ]
                )
                self._emit_delta(delta)
            # return empty object
            else:
                delta = DeltaMessage(
                    tool_calls=[
                        DeltaToolCall(
                            index=self.tool_call_index - 1,
                            id=self._get_call_id_for_delta(),
                            type="function",
                            function=DeltaFunctionCall(name=None, arguments="{}"),
                        )
                    ]
                )
                self._emit_delta(delta)
            self.current_function_open = False

        elif name == "tool_call":
            # Before ending tool_call,
            # ensure function is closed to complete missing right brace
            if self.current_function_open:
                # If there are still unclosed parameters, close them first
                if self.current_param_name:
                    self._end_element("parameter")
                # Close function, ensure output '}' or '{}'
                self._end_element("function")
            # Final Delta
            delta = DeltaMessage(
                tool_calls=[
                    DeltaToolCall(
                        index=self.tool_call_index - 1,
                        id=self._get_call_id_for_delta(),
                        type="function",
                        function=DeltaFunctionCall(name=None, arguments=""),
                    )
                ]
            )
            self._emit_delta(delta)

            # Check if there's text content to output (between tool_calls)
            if self.text_content_buffer.strip():
                text_delta = DeltaMessage(content=self.text_content_buffer)
                self._emit_delta(text_delta)

            self._reset_xml_parser_after_tool_call()

    def setup_parser(self):
        """Set up XML parser event handlers"""
        self.parser.buffer_text = True
        self.parser.StartElementHandler = self._start_element
        self.parser.EndElementHandler = self._end_element
        self.parser.CharacterDataHandler = self._char_data

    def set_tools(self, tools: list[Tool] | None):
        """Set tool configuration information"""
        self.tools = tools

    def _extract_function_name(self, name: str, attrs: dict[str, str]) -> str | None:
        """Extract function name from various formats"""
        if attrs and "name" in attrs:
            return attrs["name"]

        if "=" in name:
            parts = name.split("=", 1)
            if len(parts) == 2 and parts[0] == "function":
                return parts[1]

        return None

    def _extract_parameter_name(self, name: str, attrs: dict[str, str]) -> str | None:
        """Extract parameter name from various formats"""
        if attrs and "name" in attrs:
            return attrs["name"]

        if "=" in name:
            parts = name.split("=", 1)
            if len(parts) == 2 and parts[0] == "parameter":
                return parts[1]

        return None

    def _get_param_type(self, param_name: str) -> str:
        """Get parameter type based on tool configuration, defaults to string
        Args:
            param_name: Parameter name

        Returns:
            Parameter type
        """
        if not self.tools or not self.current_function_name:
            return "string"

        properties = find_tool_properties(self.tools, self.current_function_name)
        if param_name in properties and isinstance(properties[param_name], dict):
            prop = properties[param_name]
            param_type = prop.get("type")
            if isinstance(param_type, list):
                # JSON-Schema list-form type, e.g.
                # {"type": ["integer", "null"]}. Pick the first non-null
                # type, mirroring the anyOf handling below.
                for option_type in param_type:
                    if str(option_type).lower() != "null":
                        return self.repair_param_type(str(option_type))
                return "string"
            if param_type is None and "anyOf" in prop:
                # Handle anyOf schemas (e.g. nullable types like
                # anyOf: [{type: "integer"}, {type: "null"}]).
                # Pick the first non-null type; fall back to "string".
                for option in prop["anyOf"]:
                    if isinstance(option, dict) and "type" in option:
                        opt_type = str(option["type"])
                        if opt_type != "null":
                            return self.repair_param_type(opt_type)
                return "string"

            return self.repair_param_type(str(param_type or "string"))
        return "string"

    def _param_allows_null(self, param_name: str | None) -> bool:
        """Return True when the schema for ``param_name`` admits a null
        value — either via ``"type": "null"`` or as one alternative in
        an ``anyOf`` union.  Used to recognise the literal ``"null"`` /
        ``"None"`` as JSON null even when the primary type is string.
        """
        if not self.tools or not self.current_function_name or not param_name:
            return False
        properties = find_tool_properties(self.tools, self.current_function_name)
        if param_name not in properties or not isinstance(properties[param_name], dict):
            return False
        prop = properties[param_name]
        if str(prop.get("type", "")).lower() == "null":
            return True
        for option in prop.get("anyOf", []) or []:
            if (
                isinstance(option, dict)
                and str(option.get("type", "")).lower() == "null"
            ):
                return True
        return False

    def repair_param_type(self, param_type: str) -> str:
        """Repair unknown parameter types by treating them as string
        Args:
            param_type: Parameter type

        Returns:
            Repaired parameter type
        """
        if (
            param_type in ["string", "str", "text", "varchar", "char", "enum"]
            or param_type.startswith("int")
            or param_type.startswith("uint")
            or param_type.startswith("long")
            or param_type.startswith("short")
            or param_type.startswith("unsigned")
            or param_type.startswith("num")
            or param_type.startswith("float")
            or param_type in ["boolean", "bool", "binary"]
            or (
                param_type in ["object", "array", "arr", "sequence"]
                or param_type.startswith("dict")
                or param_type.startswith("list")
            )
        ):
            return param_type
        else:
            return "string"

    def _convert_param_value(self, param_value: str, param_type: str) -> Any:
        """Convert value based on parameter type
        Args:
            param_value: Parameter value
            param_type: Parameter type

        Returns:
            Converted value
        """
        param_type = param_type.strip().lower()
        # Nullable schemas (``anyOf: [string, null]`` or similar): the
        # primary type may be string but the literal ``"null"`` /
        # ``"None"`` must still convert to JSON null.  Caller passes the
        # current parameter name via the parser state so we can query
        # the schema.
        if self._param_allows_null(self.current_param_name) and param_value.lower() in (
            "null",
            "none",
        ):
            return None
        # String type takes precedence: the literal value "null" must remain
        # the string "null" instead of being converted to Python None.
        if param_type in ["string", "str", "text", "varchar", "char", "enum"]:
            return param_value
        # Non-string: "null" → Python None → JSON null.  Also accept the
        # Python literal "None" so that Qwen3.5-trained models — whose
        # chat template renders null args via ``| string`` (yielding the
        # literal "None" in the prompt) — round-trip nullable values
        # correctly.
        if param_value.lower() in ("null", "none"):
            return None
        if (
            param_type.startswith("int")
            or param_type.startswith("uint")
            or param_type.startswith("long")
            or param_type.startswith("short")
            or param_type.startswith("unsigned")
        ):
            try:
                return int(param_value)
            except (ValueError, TypeError):
                logger.warning(
                    "Parsed value '%s' is not an integer, degenerating to string.",
                    param_value,
                )
                return param_value
        elif param_type.startswith("num") or param_type.startswith("float"):
            try:
                float_param_value: float = float(param_value)
                return (
                    float_param_value
                    if float_param_value - int(float_param_value) != 0
                    else int(float_param_value)
                )
            except (ValueError, TypeError):
                logger.warning(
                    "Parsed value '%s' is not a float, degenerating to string.",
                    param_value,
                )
                return param_value
        elif param_type in ["boolean", "bool", "binary"]:
            return param_value.lower() == "true"
        else:
            return param_value

    def _convert_for_json_streaming(self, converted_value: Any, param_type: str) -> str:
        """Convert converted_value based on
        whether it's empty and if type is string
        Args:
            converted_value: Converted value
            param_type: Parameter type

        Returns:
            Converted string for streaming output
        """
        # Empty string: no output.
        if converted_value == "":
            return ""
        # None → JSON null literal (e.g. for nullable integer/object params).
        if converted_value is None:
            return "null"

        if param_type in ["string", "str", "text", "varchar", "char", "enum"]:
            # String type, remove double quotes
            return json.dumps(converted_value, ensure_ascii=False)[1:-1]
        else:
            # Non-string type, return complete JSON string
            if not isinstance(converted_value, str):
                return json.dumps(converted_value, ensure_ascii=False)
            else:
                return converted_value

    def _reset_xml_parser_after_tool_call(self):
        """
        Each tool_call is treated as a separate XML document,
        so we need to reset the parser after each tool_call.
        """

        # recreate XML parser
        self.parser = ParserCreate()
        self.setup_parser()

        # Reset current tool_call state
        if self.current_call_id:
            self.last_completed_call_id = self.current_call_id
        self.current_call_id = None
        self.id_emitted = False
        self.current_function_name = None
        self.current_function_open = False
        self.parameters = {}
        self.current_param_name = None
        self.current_param_value = ""
        self.current_param_value_converted = ""
        self.current_param_is_first = False
        self.should_emit_end_newline = False
        self.start_quote_emitted = False
        self.text_content_buffer = ""

        # Reset preprocessing and deferred parsing state
        self._pre_inside_parameter = False
        self._pre_param_buffer = ""
        self._pre_current_param_name = None
        self.defer_current_parameter = False
        self.deferred_param_raw_value = ""


class Qwen3XMLToolParser(ToolParser):
    def __init__(self, tokenizer: TokenizerLike, tools: list[Tool] | None = None):
        super().__init__(tokenizer, tools)
        self.parser = StreamingXMLToolCallParser()

        # Add missing attributes for compatibility with serving_chat.py
        self.prev_tool_call_arr: list[dict] = []
        self.streamed_args_for_tool: list[str] = []

        logger.info(
            "vLLM Successfully import tool parser %s !", self.__class__.__name__
        )

    def extract_tool_calls(
        self,
        model_output: str,
        request: ChatCompletionRequest,
    ) -> ExtractedToolCallInformation:
        self.parser.reset_streaming_state()
        # Reset tool call tracking arrays for new extraction
        self.prev_tool_call_arr = []
        self.streamed_args_for_tool = []
        self.parser.set_tools(self.tools)
        result = self.parser.parse_single_streaming_chunks(model_output)
        if not result.tool_calls:
            return ExtractedToolCallInformation(
                tool_calls=[],
                tools_called=False,
                content=result.content,
            )
        else:
            tool_calls = []
            for tool_call in result.tool_calls:
                if tool_call.function and tool_call.function.name:
                    # Reject phantom tool calls produced when the model
                    # writes an unrendered Jinja template or pseudo-XML
                    # in its response (e.g. ``<function={{ tc.name }}>``).
                    # Surfacing such names as real tool calls causes
                    # "tool not found" errors at the client.
                    if not _is_valid_function_name(tool_call.function.name):
                        continue
                    tool_calls.append(
                        ToolCall(
                            id=tool_call.id,
                            type=tool_call.type,
                            function=FunctionCall(
                                name=tool_call.function.name,
                                arguments=tool_call.function.arguments,
                            ),
                        )
                    )

                    # Update tool call tracking arrays for compatibility
                    tool_index = (
                        tool_call.index
                        if tool_call.index is not None
                        else len(self.prev_tool_call_arr) - 1
                    )

                    # Ensure we have enough entries in our tracking arrays
                    while len(self.prev_tool_call_arr) <= tool_index:
                        self.prev_tool_call_arr.append({"name": "", "arguments": ""})
                    while len(self.streamed_args_for_tool) <= tool_index:
                        self.streamed_args_for_tool.append("")

                    # Update tool call information
                    self.prev_tool_call_arr[tool_index]["name"] = (
                        tool_call.function.name
                    )
                    self.prev_tool_call_arr[tool_index]["arguments"] = (
                        tool_call.function.arguments
                    )

                    # Update streamed arguments
                    if tool_call.function.arguments:
                        self.streamed_args_for_tool[tool_index] = (
                            tool_call.function.arguments
                        )

            return ExtractedToolCallInformation(
                tool_calls=tool_calls,
                tools_called=len(tool_calls) > 0,
                content=result.content,
            )

    def extract_tool_calls_streaming(
        self,
        previous_text: str,
        current_text: str,
        delta_text: str,
        previous_token_ids: Sequence[int],
        current_token_ids: Sequence[int],
        delta_token_ids: Sequence[int],
        request: ChatCompletionRequest,
    ) -> DeltaMessage | None:
        if not previous_text:
            self.parser.reset_streaming_state()
            self.parser._streaming_mode = True
            # Reset tool call tracking arrays for new streaming session
            self.prev_tool_call_arr = []
            self.streamed_args_for_tool = []
            self.parser.set_tools(self.tools)

        # Model sometimes outputs separately causing delta_text to be empty.
        # If there were tool_calls before and all current tool_calls have ended,
        # return an empty tool_call for outer streaming output
        # to correctly output tool_call field
        if not delta_text and delta_token_ids:
            open_calls = current_text.count(
                self.parser.tool_call_start_token
            ) - current_text.count(self.parser.tool_call_end_token)
            if (
                open_calls == 0
                and self.parser.tool_call_index > 0
                or not self.parser.tool_call_index
                and current_text
            ):
                return DeltaMessage(content="")
            return None

        # Parse the delta text and get the result
        delta = self.parser.parse_single_streaming_chunks(delta_text)

        # Update tool call tracking arrays based on incremental parsing results
        if delta and delta.tool_calls:
            for tool_call in delta.tool_calls:
                if tool_call.function:
                    tool_index = (
                        tool_call.index
                        if tool_call.index is not None
                        else len(self.prev_tool_call_arr) - 1
                    )

                    # Ensure we have enough entries in our tracking arrays
                    while len(self.prev_tool_call_arr) <= tool_index:
                        self.prev_tool_call_arr.append({"name": "", "arguments": ""})
                    while len(self.streamed_args_for_tool) <= tool_index:
                        self.streamed_args_for_tool.append("")

                    # Update tool name if provided
                    if tool_call.function.name:
                        self.prev_tool_call_arr[tool_index]["name"] = (
                            tool_call.function.name
                        )

                    # Update arguments incrementally
                    if tool_call.function.arguments is not None:
                        # Concatenate the incremental arguments
                        # to the existing streamed arguments
                        self.prev_tool_call_arr[tool_index]["arguments"] += (
                            tool_call.function.arguments
                        )
                        self.streamed_args_for_tool[tool_index] += (
                            tool_call.function.arguments
                        )
        if delta.content is None and not delta.tool_calls and delta.reasoning is None:
            # If no content and no tool calls, return None to indicate no update
            return None
        return delta

    def get_structural_tag(self, request: ChatCompletionRequest):
        return get_model_structural_tag(
            model="qwen_3_5",
            tools=request.tools,
            tool_choice=request.tool_choice,
            reasoning=get_enable_structured_outputs_in_reasoning(),
        )
