DLLM_NAMESPACE = "dllm"
CONTROLLER_ACTOR_NAME = "controller"
BALANCER_ACTOR_NAME = "balancer"

ENDPOINT_APPLICATION_NAME = "dllm-endpoint"
ENDPOINT_PROXY_DEPLOYMENT_NAME = "dllm-endpoint"

INSTANCE_HEALTHCHECK_INTERVAL_SEC = 10

HTTP_OK = 200

HTTP_PARAM_INVALID = 400

HTTP_TOO_MANY_REQUESTS = 429

HTTP_INTERNAL_ERROR = 500

NUM_RUNNING_REQUESTS = "vllm:num_requests_running"

NUM_WAITING_REQUESTS = "vllm:nun_requests_waiting"

DEVICE_USAGE_PERCENT = "vllm:gpu_cache_usage_perc"

METRICS_UPDATE_CYCLE = 0.5
