{{-   if .Values.extraInit  }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-storage-claim"
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - {{ .Values.extraInit.pvcAccessMode | default "ReadWriteOnce" }}
  {{- if .Values.extraInit.pvcStorageClassName }}
  storageClassName: {{ .Values.extraInit.pvcStorageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.extraInit.pvcStorage }}
{{- end }}