name: summary
description: 'creates a neuralmagic GHA run summary'
inputs:
  label:
    description: 'GHA runner label'
    required: true
  gitref:
    description: 'git commit hash or branch name'
    required: true
  testmo_run_url:
    description: 'testmo URL for this particular run'
    required: true
  python:
    description: 'python version info'
    required: true
  lint_status:
    description: 'status from python lint step'
    required: true
  build_status:
    description: 'status from build step'
    required: true
  test_status:
    description: 'status from test step'
    required: true
runs:
  using: composite
  steps:
  - run: |
      LINT_STATUS=${{ inputs.lint_status }}
      LINT_EMOJI=$(./.github/scripts/step-status ${LINT_STATUS})
      BUILD_STATUS=${{ inputs.build_status }}
      BUILD_EMOJI=$(./.github/scripts/step-status ${BUILD_STATUS})
      TEST_STATUS=${{ inputs.test_status }}
      TEST_EMOJI=$(./.github/scripts/step-status ${TEST_STATUS})
      echo "testmo URL: ${{ inputs.testmo_run_url }}" >> $GITHUB_STEP_SUMMARY
      echo ""
      echo "| Parameter | |" >> $GITHUB_STEP_SUMMARY
      echo "|---|---|" >> $GITHUB_STEP_SUMMARY
      echo "| label: | \`${{ inputs.label }}\` |" >> $GITHUB_STEP_SUMMARY
      echo "| git sha: | \`${{ github.sha }}\` |" >> $GITHUB_STEP_SUMMARY
      echo "| github actor: | '${{ github.actor }}' |" >> $GITHUB_STEP_SUMMARY
      echo "| gitref: | '${{ inputs.gitref }}' |" >> $GITHUB_STEP_SUMMARY
      echo "| branch name: | '${{ github.ref_name }}' |" >> $GITHUB_STEP_SUMMARY
      echo "| python: | ${{ inputs.python }} |" >> $GITHUB_STEP_SUMMARY
      echo "| lint: | ${LINT_EMOJI} |" >> $GITHUB_STEP_SUMMARY
      echo "| build: | ${BUILD_EMOJI} |" >> $GITHUB_STEP_SUMMARY
      echo "| test: | ${TEST_EMOJI} |" >> $GITHUB_STEP_SUMMARY
    shell: bash
