workload: 
  type: dummy

docker:
  env:
    - "LMCACHE_CHUNK_SIZE=256"
    - "LMCACHE_LOCAL_CPU=True"
    - "LMCACHE_MAX_LOCAL_CPU_SIZE=5"
    - "LMCACHE_INTERNAL_API_SERVER_ENABLED=True"
    - "LMCACHE_INTERNAL_API_SERVER_SOCKET_PATH_PREFIX=/tmp/lmcache_internal_api_server/socket"

vllm:
  model: "meta-llama/Llama-3.2-1B-Instruct"
  args:
    - "--max-model-len"
    - "1024"
    - "--gpu-memory-utilization"
    - "0.35"
    - "--load-format"
    - "dummy"
    - "--kv-transfer-config"
    - "{\"kv_connector\":\"LMCacheConnectorV1\",\"kv_role\":\"kv_both\"}"