# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project

import os

from transformers import AutoConfig, PretrainedConfig


class GumihoConfig(PretrainedConfig):
    """Config for the Gumiho speculative drafter.

    Gumiho wraps a small transformer backbone (typically a 2-layer Llama) and
    one or more parallel MLP heads. The first two speculative tokens are
    generated by the transformer backbone (autoregressively, like EAGLE), and
    every additional speculative token is generated in parallel by the MLP
    heads. ``model`` holds the backbone HF config (usually a ``LlamaConfig``),
    and the outer attributes mirror the backbone so vLLM model loading works
    the same way as for any other Llama-family draft model.
    """

    model_type = "gumiho"

    def __init__(
        self,
        model: PretrainedConfig | dict | None = None,
        truncated_vocab_size: int | None = None,
        **kwargs,
    ):
        if isinstance(model, dict):
            model_config = AutoConfig.for_model(**model)
        else:
            model_config = model

        for k, v in kwargs.items():
            if k != "architectures" and k != "model_type" and hasattr(model_config, k):
                setattr(model_config, k, v)

        self.model = model_config

        if self.model is None:
            self.truncated_vocab_size = None
        else:
            # ``vocab_size`` is not strictly part of ``PretrainedConfig``;
            # fall back to ``None`` for unusual backbones that omit it.
            self.truncated_vocab_size = (
                getattr(self.model, "vocab_size", None)
                if truncated_vocab_size is None
                else truncated_vocab_size
            )

        if "architectures" not in kwargs:
            if self.model is not None and getattr(self.model, "architectures", None):
                kwargs["architectures"] = [
                    f"Gumiho{arch}" if not arch.startswith("Gumiho") else arch
                    for arch in self.model.architectures
                ]
            elif self.model is not None and self.model.model_type == "llama":
                kwargs["architectures"] = ["GumihoLlamaForCausalLM"]
            else:
                kwargs["architectures"] = ["GumihoModel"]

        super().__init__(**kwargs)

        if self.model is not None:
            for k, v in self.model.to_dict().items():
                if k not in kwargs and k not in ("architectures", "model_type"):
                    setattr(self, k, v)

    @classmethod
    def from_pretrained(
        cls,
        pretrained_model_name_or_path: str | os.PathLike,
        **kwargs,
    ) -> "GumihoConfig":
        config_dict, kwargs = cls.get_config_dict(
            pretrained_model_name_or_path, **kwargs
        )
        return cls.from_dict(config_dict, **kwargs)

    def to_json_string(self, use_diff: bool = True) -> str:
        del use_diff
        return super().to_json_string(use_diff=False)
