# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project

import json
from abc import abstractmethod

import zmq

from vllm.config import FaultToleranceConfig
from vllm.logger import init_logger
from vllm.utils.network_utils import make_zmq_socket, recv_router_dealer_message
from vllm.v1.engine.utils import broadcast_instruction, wait_for_instruction_result
from vllm.v1.serial_utils import (
    deserialize_method_call,
    run_method,
)

logger = init_logger(__name__)
# Polling timeout in milliseconds for non-blocking message reception
POLL_TIMEOUT_MS = 100


class BaseSentinel:
    """
    Abstract and constrain the core functionalities of the Sentinel.

    Core functionalities covered:
    - Fault listening
    - Fault tolerance instruction reception
    - Fault tolerance instruction execution
    - Upstream and downstream communication

    This class serves as the base abstraction for all LLM-related Sentinel
    implementations, enforcing standardized fault tolerance behavior across
    the system.
    """

    def __init__(
        self,
        upstream_cmd_addr: str | None,
        downstream_cmd_addr: str | None,
        dealer_socket_identity: bytes | None,
        sentinel_tag: str | None,
        fault_tolerance_config: FaultToleranceConfig,
    ):
        self.sentinel_dead = False
        self.ctx = zmq.Context()
        self.sentinel_tag = sentinel_tag
        self.logger = self._make_logger()
        self.ft_config = fault_tolerance_config
        if upstream_cmd_addr is not None:
            assert dealer_socket_identity is not None
            self.upstream_cmd_socket = make_zmq_socket(
                self.ctx,
                upstream_cmd_addr,
                zmq.DEALER,
                bind=False,
                identity=dealer_socket_identity,
            )
        if downstream_cmd_addr is not None:
            self.downstream_cmd_socket = make_zmq_socket(
                ctx=self.ctx,
                path=downstream_cmd_addr,
                socket_type=zmq.ROUTER,
                bind=True,
            )

    def _make_logger(self):
        def log(msg, *args, level="info", **kwargs):
            """
            level: "info", "warning", "error", "debug"
            msg: log message
            """
            prefix = self.sentinel_name
            getattr(logger, level)(prefix + msg, *args, **kwargs)

        return log

    @property
    def sentinel_name(self) -> str:
        if self.sentinel_tag is None:
            return f"[{self.__class__.__name__}] "
        return f"[{self.__class__.__name__}_{self.sentinel_tag}] "

    @abstractmethod
    def run(self) -> None:
        """
        The run() method is launched as a separate thread when a Sentinel
        instance is created.

        This background thread typically runs persistently to ensure real-time
        detection of errors and timely reception of fault tolerance instructions
        from upstream sentinels
        .
        """
        raise NotImplementedError

    def receive_upstream_cmd(self) -> tuple[bool, str | None]:
        """
        This method polls the upstream command socket and attempts to receive
        a serialized command message.
        """
        try:
            has_msg, _, cmd_str = recv_router_dealer_message(
                self.upstream_cmd_socket,
                use_poller=True,
                poll_timeout=POLL_TIMEOUT_MS,
            )
        except zmq.ZMQError:
            self.logger(
                "Socket closed, terminating %s", self.sentinel_name, level="info"
            )
            return False, None
        return has_msg, cmd_str

    def _execute_cmd(self, cmd_str: str) -> tuple[bool, str, str | None]:
        """
        Execute a command represented by a JSON string on the current object.
        The command string is expected to be generated by `serialize_method_call`,
        containing the method name, a unique ID for the command, and method
        parameters.

        Args:
        cmd_str (str): JSON string representing a serialized method call.

        Returns:
            tuple[bool, str, str | None]:
            - success (bool): True if the method ran without error; False otherwise.
            - method_uuid (str): Unique ID of the command.
            - reason (str | None): Error message if execution failed.
        """
        method, method_uuid, method_params = deserialize_method_call(cmd_str)
        self.logger("Executing command: %s", method, level="info")
        try:
            success: bool = run_method(self, method, args=(), kwargs=method_params)
            self.logger("Command (%s) succeeded: %s", method, success, level="info")
            reason = None
        except Exception as e:
            self.logger(
                "Error executing method %s: %s, %s",
                method,
                type(e).__name__,
                e,
                level="error",
            )
            success = False
            reason = f"{type(e).__name__}: {e}"
        return success, method_uuid, reason

    @abstractmethod
    def pause(self, timeout: int = 1, soft_pause: bool = True) -> bool:
        """
        Pause the vLLM instance to enter fault-tolerance mode.
        This method should be called when a fault is detected. It pauses the
        execution, allowing the system to wait for fault-tolerance instructions
        (e.g., retry, scale-down, or other control commands).
        """
        raise NotImplementedError

    @abstractmethod
    def retry(self, timeout: int = 1, **kwargs) -> bool:
        """
        Retry execution after a transient recoverable fault.
        """
        raise NotImplementedError

    def _send_execution_result(
        self, success: bool, method_uuid: str, reason: str | None
    ):
        """
        Send the result of executing a command back to the upstream.
        """
        assert hasattr(self, "upstream_cmd_socket"), "upstream_cmd_socket is required"
        msg = {
            "sentinel_tag": self.sentinel_tag,
            "success": success,
            "method_uuid": method_uuid,
        }
        if not success and reason is not None:
            msg["reason"] = reason
        msg_bytes = json.dumps(msg).encode("utf-8")
        self.upstream_cmd_socket.send_multipart([b"", msg_bytes])

    def _broadcast_command_to_downstream(
        self,
        method_name: str,
        target_downstream_sentinels: set[bytes],
        response_timeout: int = 5,
        **kwargs,
    ):
        """
        Broadcast a command to downstream sentinels and collect responses.
        """
        method_uuid = broadcast_instruction(
            self.downstream_cmd_socket,
            target_downstream_sentinels,
            method_name,
            **kwargs,
        )

        responses = wait_for_instruction_result(
            self.downstream_cmd_socket,
            target_downstream_sentinels,
            method_name,
            response_timeout,
            method_uuid,
        )

        # check the execution results
        all_success = True
        for sentinel_identity in target_downstream_sentinels:
            response = responses.get(sentinel_identity)
            if response is None:
                self.logger(
                    'Downstream sentinels timed out on "%s".',
                    method_name,
                    level="error",
                )
                all_success = False
                break
            elif not response.get("success", False):
                self.logger(
                    'Downstream sentinels failed to execute command "%s" (reason: %s)',
                    method_name,
                    response.get("reason", "unknown"),
                    level="error",
                )
                all_success = False
                break

        return all_success, responses

    def shutdown(self):
        if (
            hasattr(self, "upstream_cmd_socket")
            and self.upstream_cmd_socket is not None
        ):
            self.upstream_cmd_socket.close()
        if (
            hasattr(self, "downstream_cmd_socket")
            and self.downstream_cmd_socket is not None
        ):
            self.downstream_cmd_socket.close()
        if self.ctx is not None:
            self.ctx.term()
        self.sentinel_dead = True
