#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
"""Generate standalone Triton modules from tuned Helion kernels."""

from __future__ import annotations

import argparse
import ast
import hashlib
import importlib.metadata
import json
from pathlib import Path
from pprint import pformat
from typing import Any

import regex as re
import torch

from vllm.kernels.helion.case_key import CaseKey
from vllm.kernels.helion.config_manager import ConfigManager
from vllm.kernels.helion.ops.per_token_group_fp8_quant import (
    per_token_group_fp8_quant,
)

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_ROOT = ROOT / "vllm/kernels/helion_generated/kernels"
KERNEL_NAME = "per_token_group_fp8_quant"
PLATFORM_DEVICE_NAMES = {
    "nvidia_b200": "nvidia_b200",
    "nvidia_h100": "nvidia_h100",
    "nvidia_h100_80gb_hbm3": "nvidia_h100",
    "nvidia_h100_nvl": "nvidia_h100",
    "nvidia_h100_pcie": "nvidia_h100",
    "nvidia_h100_sxm5": "nvidia_h100",
}

_LAUNCHER = """def _get_num_sm(device: torch.device) -> int:
    return torch.cuda.get_device_properties(device).multi_processor_count


def _default_launcher(
    triton_kernel: object,
    grid: tuple[int, ...],
    *args: object,
    num_warps: int,
    num_stages: int,
    ptx_options: str | None = None,
    launch_cooperative_grid: bool = False,
    **kwargs: object,
) -> object:
    run_kwargs = {
        "grid": grid,
        "warmup": False,
        "num_warps": num_warps,
        "num_stages": num_stages,
        "launch_cooperative_grid": launch_cooperative_grid,
        **kwargs,
    }
    if ptx_options is not None:
        run_kwargs["ptx_options"] = ptx_options
    return triton_kernel.run(*args, **run_kwargs)
"""


def _canonical_device_name(name: str) -> str:
    return name.lower().replace(" ", "_").replace("-", "_").replace("/", "_")


def _require_matching_hardware(platform: str) -> None:
    if not torch.cuda.is_available():
        raise RuntimeError(f"Generating {platform} kernels requires a CUDA GPU")
    actual_name = _canonical_device_name(torch.cuda.get_device_name())
    actual = PLATFORM_DEVICE_NAMES.get(actual_name)
    if actual != platform:
        raise RuntimeError(
            f"Generating {platform} kernels requires matching hardware; "
            f"found {torch.cuda.get_device_name()!r}"
        )


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _replace_binary_helper(code: str, helper: str, replacement: str) -> str:
    pattern = rf"\b{re.escape(helper)}\(([^,\n]+),\s*([^\)\n]+)\)"
    return re.sub(
        pattern,
        rf"{replacement}(\1, \2, tl.PropagateNan.ALL)",
        code,
    )


def _postprocess(code: str, token_bucket: int) -> str:
    code = (
        code.replace("from torch._inductor.runtime import triton_helpers\n", "")
        .replace(
            "from torch._inductor.runtime.triton_helpers import math as tl_math\n", ""
        )
        .replace("from torch._inductor.runtime.triton_compat import libdevice\n", "")
        .replace(
            "from helion.runtime import default_launcher as _default_launcher\n", ""
        )
        .replace("import helion\n", "")
    )
    code = code.replace("tl_math.", "tl.").replace("libdevice.", "tl.")
    code = code.replace("helion.runtime.get_num_sm", "_get_num_sm")
    code = _replace_binary_helper(code, "triton_helpers.maximum", "tl.maximum")
    code = _replace_binary_helper(code, "triton_helpers.minimum", "tl.minimum")
    code = code.replace(
        "_helion_per_token_group_fp8_quant", "_triton_per_token_group_fp8_quant"
    )
    code = code.replace("def per_token_group_fp8_quant(", "def call(")
    code = re.sub(r"^\s*# src\[[^\n]*\n", "", code, flags=re.MULTILINE)
    if token_bucket == 1:
        code = re.sub(
            r"(\* )1(,\),)",
            r"\1num_tokens\2",
            code,
            count=1,
        )
    import_end = code.index("\n\n", code.index("import triton.language as tl"))
    code = code[: import_end + 2] + _LAUNCHER + "\n" + code[import_end + 2 :]
    code = (
        "# SPDX-License-Identifier: Apache-2.0\n"
        "# SPDX-FileCopyrightText: Copyright contributors to the vLLM project\n"
        "# This file is generated by scripts/generate_helion_kernels.py.\n"
        "# ruff: noqa\n"
        "# mypy: ignore-errors\n"
        "# fmt: off\n" + code
    )
    _validate_artifact(code)
    return code.rstrip() + "\n"


def _validate_artifact(code: str) -> None:
    tree = ast.parse(code)
    allowed_roots = {"__future__", "torch", "triton"}
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imported = {alias.name.split(".", 1)[0] for alias in node.names}
            if not imported <= allowed_roots:
                raise ValueError(f"forbidden generated import: {sorted(imported)}")
        elif isinstance(node, ast.ImportFrom):
            root = (node.module or "").split(".", 1)[0]
            if root not in allowed_roots:
                raise ValueError(f"forbidden generated import: {node.module}")
    call = next(
        node
        for node in tree.body
        if isinstance(node, ast.FunctionDef) and node.name == "call"
    )
    if [arg.arg for arg in call.args.args] != [
        "input",
        "output_q",
        "output_s",
        "group_size",
        "eps",
        "fp8_min",
        "fp8_max",
        "scale_ue8m0",
        "dummy_is_scale_transposed",
        "dummy_is_tma_aligned",
    ]:
        raise ValueError("generated artifact has an unstable call(...) contract")


def _module_name(case: CaseKey) -> str:
    return (
        f"per_token_group_fp8_quant_h{case['hidden_size']}"
        f"_g{case['group_size']}_t{case['num_tokens']}"
    )


def _manifest(
    platform: str,
    cases: list[CaseKey],
    configs: dict[CaseKey, Any],
) -> str:
    source_path = ROOT / "vllm/kernels/helion/ops/per_token_group_fp8_quant.py"
    config_path = (
        ROOT
        / "vllm/kernels/helion/configs/per_token_group_fp8_quant"
        / f"{platform}.json"
    )
    kernels = {
        (case["hidden_size"], case["group_size"], case["num_tokens"]): (
            f"vllm.kernels.helion_generated.kernels.{platform}."
            f"{KERNEL_NAME}.{_module_name(case)}"
        )
        for case in cases
    }
    serialized_configs = {
        (case["hidden_size"], case["group_size"], case["num_tokens"]): json.loads(
            configs[case].to_json()
        )
        for case in cases
    }
    provenance = {
        "config_path": str(config_path.relative_to(ROOT)),
        "config_sha256": _sha256(config_path),
        "generator": "scripts/generate_helion_kernels.py",
        "helion_version": importlib.metadata.version("helion"),
        "kernel": KERNEL_NAME,
        "platform": platform,
        "source_path": str(source_path.relative_to(ROOT)),
        "source_sha256": _sha256(source_path),
        "torch_version": torch.__version__,
        "triton_version": importlib.metadata.version("triton"),
    }
    return (
        "# SPDX-License-Identifier: Apache-2.0\n"
        "# SPDX-FileCopyrightText: Copyright contributors to the vLLM project\n"
        "# This file is generated by scripts/generate_helion_kernels.py.\n\n"
        "# ruff: noqa\n"
        "# mypy: ignore-errors\n"
        "# fmt: off\n"
        f"KERNELS = {pformat(kernels, sort_dicts=True, width=88)}\n\n"
        f"CONFIGS = {pformat(serialized_configs, sort_dicts=True, width=88)}\n\n"
        f"PROVENANCE = {pformat(provenance, sort_dicts=True, width=88)}\n"
    )


def _init_file() -> str:
    return (
        "# SPDX-License-Identifier: Apache-2.0\n"
        "# SPDX-FileCopyrightText: Copyright contributors to the vLLM project\n"
    )


def _write_or_check(path: Path, content: str, check: bool, errors: list[str]) -> None:
    if check:
        if not path.exists() or path.read_text() != content:
            errors.append(str(path.relative_to(ROOT)))
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def generate(platform: str, check: bool) -> None:
    _require_matching_hardware(platform)
    configs = ConfigManager().get_platform_configs(KERNEL_NAME, platform)
    inputs = per_token_group_fp8_quant.get_inputs()
    cases = sorted(
        (case for case in configs if case in inputs),
        key=lambda case: (
            case["hidden_size"],
            case["group_size"],
            case["num_tokens"],
        ),
    )
    if len(cases) != len(configs) or len(cases) != len(inputs):
        raise RuntimeError(
            f"Config/input mismatch: {len(configs)} configs, {len(inputs)} inputs, "
            f"{len(cases)} common cases"
        )

    platform_dir = OUTPUT_ROOT / platform
    output_dir = platform_dir / KERNEL_NAME
    errors: list[str] = []
    expected = {"__init__.py", "manifest.py"}
    configured = per_token_group_fp8_quant.get_configured_op()._decorated_kernel
    for case in cases:
        filename = f"{_module_name(case)}.py"
        expected.add(filename)
        code = configured.bind(inputs[case]).to_code(configs[case])
        content = _postprocess(code, case["num_tokens"])
        _write_or_check(output_dir / filename, content, check, errors)

    _write_or_check(output_dir / "__init__.py", _init_file(), check, errors)
    _write_or_check(platform_dir / "__init__.py", _init_file(), check, errors)
    _write_or_check(
        output_dir / "manifest.py",
        _manifest(platform, cases, configs),
        check,
        errors,
    )
    if output_dir.exists():
        stale = sorted(
            path for path in output_dir.glob("*.py") if path.name not in expected
        )
        if check:
            errors.extend(str(path.relative_to(ROOT)) for path in stale)
        else:
            for path in stale:
                path.unlink()
    if errors:
        paths = "\n".join(f"  {path}" for path in sorted(errors))
        raise SystemExit(f"Generated Helion kernels are stale:\n{paths}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--kernel",
        choices=[KERNEL_NAME],
        default=KERNEL_NAME,
    )
    parser.add_argument(
        "--platform",
        choices=sorted(set(PLATFORM_DEVICE_NAMES.values())),
        required=True,
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail instead of writing when generated files differ.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    generate(args.platform, args.check)


if __name__ == "__main__":
    main()
