# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: orca_load_report.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'orca_load_report.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16orca_load_report.proto\x12\x10xds.data.orca.v3\"\x8e\x04\n\x0eOrcaLoadReport\x12\x17\n\x0f\x63pu_utilization\x18\x01 \x01(\x01\x12\x17\n\x0fmem_utilization\x18\x02 \x01(\x01\x12\x0b\n\x03rps\x18\x03 \x01(\x04\x12G\n\x0crequest_cost\x18\x04 \x03(\x0b\x32\x31.xds.data.orca.v3.OrcaLoadReport.RequestCostEntry\x12\x46\n\x0butilization\x18\x05 \x03(\x0b\x32\x31.xds.data.orca.v3.OrcaLoadReport.UtilizationEntry\x12\x16\n\x0erps_fractional\x18\x06 \x01(\x01\x12\x0b\n\x03\x65ps\x18\x07 \x01(\x01\x12I\n\rnamed_metrics\x18\x08 \x03(\x0b\x32\x32.xds.data.orca.v3.OrcaLoadReport.NamedMetricsEntry\x12\x1f\n\x17\x61pplication_utilization\x18\t \x01(\x01\x1a\x32\n\x10RequestCostEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x1a\x32\n\x10UtilizationEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x1a\x33\n\x11NamedMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x42]\n\x1b\x63om.github.xds.data.orca.v3B\x13OrcaLoadReportProtoP\x01Z\'github.com/cncf/xds/go/xds/data/orca/v3b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'orca_load_report_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033com.github.xds.data.orca.v3B\023OrcaLoadReportProtoP\001Z\'github.com/cncf/xds/go/xds/data/orca/v3'
  _globals['_ORCALOADREPORT_REQUESTCOSTENTRY']._loaded_options = None
  _globals['_ORCALOADREPORT_REQUESTCOSTENTRY']._serialized_options = b'8\001'
  _globals['_ORCALOADREPORT_UTILIZATIONENTRY']._loaded_options = None
  _globals['_ORCALOADREPORT_UTILIZATIONENTRY']._serialized_options = b'8\001'
  _globals['_ORCALOADREPORT_NAMEDMETRICSENTRY']._loaded_options = None
  _globals['_ORCALOADREPORT_NAMEDMETRICSENTRY']._serialized_options = b'8\001'
  _globals['_ORCALOADREPORT']._serialized_start=45
  _globals['_ORCALOADREPORT']._serialized_end=571
  _globals['_ORCALOADREPORT_REQUESTCOSTENTRY']._serialized_start=416
  _globals['_ORCALOADREPORT_REQUESTCOSTENTRY']._serialized_end=466
  _globals['_ORCALOADREPORT_UTILIZATIONENTRY']._serialized_start=468
  _globals['_ORCALOADREPORT_UTILIZATIONENTRY']._serialized_end=518
  _globals['_ORCALOADREPORT_NAMEDMETRICSENTRY']._serialized_start=520
  _globals['_ORCALOADREPORT_NAMEDMETRICSENTRY']._serialized_end=571
# @@protoc_insertion_point(module_scope)
