#!/bin/bash
# Select tests to run for a PR using Claude + static import analysis.
# Posts the selection as a PR comment for author review.
#
# Usage:
#   .buildkite/scripts/select_tests.sh <pr_number> [base_branch]
#
# Modes:
#   .buildkite/scripts/select_tests.sh 1234           # select + post comment
#   .buildkite/scripts/select_tests.sh 1234 main      # custom base branch
#   .buildkite/scripts/select_tests.sh --dry-run       # select only, no comment
#
# Requirements:
#   - claude CLI (Anthropic Claude Code)
#   - python3 (for the mapping script)
#   - gh CLI (for posting PR comments, unless --dry-run)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Parse arguments
DRY_RUN=false
PR_NUMBER=""
BASE_BRANCH="origin/main"

if [ "${1:-}" = "--dry-run" ]; then
    DRY_RUN=true
elif [ -n "${1:-}" ]; then
    PR_NUMBER="$1"
fi

if [ -n "${2:-}" ]; then
    BASE_BRANCH="$2"
fi

# ---------------------------------------------------------------------------
# Step 1: Get changed files
# ---------------------------------------------------------------------------
CHANGED_FILES=$(git diff "${BASE_BRANCH}...HEAD" --name-only)

if [ -z "$CHANGED_FILES" ]; then
    echo "No changed files detected." >&2
    exit 0
fi

FILE_COUNT=$(echo "$CHANGED_FILES" | wc -l | tr -d ' ')
echo "Found $FILE_COUNT changed files" >&2

# ---------------------------------------------------------------------------
# Step 2: Generate fresh mapping from current code
# ---------------------------------------------------------------------------
echo "Generating import mapping..." >&2
MAPPING=$(python3 "$SCRIPT_DIR/build_test_mapping.py" 2>/dev/null)

# ---------------------------------------------------------------------------
# Step 3: Read static instructions
# ---------------------------------------------------------------------------
INSTRUCTIONS=$(cat "$SCRIPT_DIR/../TEST_SELECTION.md")

# ---------------------------------------------------------------------------
# Step 4: Ask Claude to select tests
# ---------------------------------------------------------------------------
echo "Asking Claude to select tests..." >&2

PROMPT="$(cat <<PROMPTEOF
You are selecting tests for a CI pipeline. Follow the instructions exactly.

## Instructions

${INSTRUCTIONS}

## Source-to-Test Mapping (auto-generated from import analysis)

${MAPPING}

## Changed Files in This PR

${CHANGED_FILES}

## Your Task

Based on the instructions, the mapping table, and the changed files above,
output the test directories/files to run. Follow ALL rules in the instructions.
Use the output format specified in the instructions.
PROMPTEOF
)"

SELECTION=$(claude -p --model haiku "$PROMPT" 2>/dev/null)

if [ -z "$SELECTION" ]; then
    echo "Error: Claude returned empty selection." >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# Step 5: Build the PR comment
# ---------------------------------------------------------------------------

# Filter to only valid "path | reason" lines
CLEAN_SELECTION=$(echo "$SELECTION" | grep -E '^[a-zA-Z_/.]+ *\|' || true)

if [ -z "$CLEAN_SELECTION" ]; then
    echo "Warning: Could not parse Claude's output. Raw output:" >&2
    echo "$SELECTION" >&2
    exit 1
fi

# Check for NONE case
IS_NONE=$(echo "$CLEAN_SELECTION" | grep -c '^NONE ' || true)

if [ "$IS_NONE" -gt 0 ]; then
    NONE_REASON=$(echo "$CLEAN_SELECTION" | head -1 | cut -d'|' -f2 | xargs)
    TARGET_COUNT=0
else
    TARGET_COUNT=$(echo "$CLEAN_SELECTION" | wc -l | tr -d ' ')
fi

# Build the comment body
COMMENT_BODY="## Suggested Test Selection

**${FILE_COUNT} files changed"

if [ "$IS_NONE" -gt 0 ]; then
    COMMENT_BODY="${COMMENT_BODY}, no tests selected.**

**Reason:** ${NONE_REASON}

<details><summary>Changed files</summary>

\`\`\`
${CHANGED_FILES}
\`\`\`

</details>"
else
    COMMENT_BODY="${COMMENT_BODY}, ${TARGET_COUNT} test targets selected.**

### Selected tests

| Test target | Reason |
|---|---|
$(echo "$CLEAN_SELECTION" | while IFS='|' read -r target reason; do
    target=$(echo "$target" | xargs)
    reason=$(echo "$reason" | xargs)
    if [ -n "$target" ]; then
        echo "| \`${target}\` | ${reason} |"
    fi
done)

<details><summary>Changed files (${FILE_COUNT})</summary>

\`\`\`
${CHANGED_FILES}
\`\`\`

</details>"
fi

COMMENT_BODY="${COMMENT_BODY}

### Review

If this selection looks wrong, reply with what should change:
- **Missing tests**: \"Also run tests/distributed/ because this change affects X\"
- **Unnecessary tests**: \"tests/compile/ is not relevant here because Y\"

If it looks right, no action needed.

---
*Auto-generated by test selection script.*"

# ---------------------------------------------------------------------------
# Step 6: Post or print
# ---------------------------------------------------------------------------
if [ "$DRY_RUN" = true ]; then
    echo "$COMMENT_BODY"
else
    if [ -z "$PR_NUMBER" ]; then
        echo "Error: PR number required. Use --dry-run for local testing." >&2
        exit 1
    fi

    # Delete previous test selection comment if it exists (avoid stacking)
    PREVIOUS_COMMENT_ID=$(gh api \
        "repos/{owner}/{repo}/issues/${PR_NUMBER}/comments" \
        --jq '.[] | select(.body | startswith("## Suggested Test Selection")) | .id' \
        2>/dev/null | head -1)

    if [ -n "$PREVIOUS_COMMENT_ID" ]; then
        echo "Deleting previous test selection comment..." >&2
        gh api -X DELETE \
            "repos/{owner}/{repo}/issues/comments/${PREVIOUS_COMMENT_ID}" \
            2>/dev/null || true
    fi

    # Post new comment
    gh pr comment "$PR_NUMBER" --body "$COMMENT_BODY"
    echo "Comment posted to PR #${PR_NUMBER}" >&2
fi

# Also output just the test paths to stdout (for CI pipeline use later)
if [ "$IS_NONE" -eq 0 ]; then
    echo "$CLEAN_SELECTION" | while IFS='|' read -r target _reason; do
        target=$(echo "$target" | xargs)
        if [ -n "$target" ]; then
            echo "$target"
        fi
    done
fi
