name: set neuralmagic env
description: 'sets environment variables for neuralmagic'
inputs:
  hf_token:
    description: 'Hugging Face home'
    required: true
  Gi_per_thread:
    description: 'requested GiB to reserve per thread'
    required: true
runs:
  using: composite
  steps:
  - run: |
      echo "HF_TOKEN=${HF_TOKEN_SECRET}" >> $GITHUB_ENV
      NUM_THREADS=$(./.github/scripts/determine-threading -G ${{ inputs.Gi_per_thread }})
      echo "MAX_JOBS=${NUM_THREADS}" >> $GITHUB_ENV
      echo "VLLM_INSTALL_PUNICA_KERNELS=1" >> $GITHUB_ENV
      echo "PYENV_ROOT=/usr/local/apps/pyenv" >> $GITHUB_ENV
      echo "XDG_CONFIG_HOME=/usr/local/apps" >> $GITHUB_ENV
      WHOAMI=$(whoami)
      echo "PATH=/usr/local/apps/pyenv/plugins/pyenv-virtualenv/shims:/usr/local/apps/pyenv/shims:/usr/local/apps/pyenv/bin:/usr/local/apps/nvm/versions/node/v16.20.2/bin:/usr/local/cuda-12.1/bin:/usr/local/cuda-12.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/${WHOAMI}/.local/bin:" >> $GITHUB_ENV
      echo "LD_LIBRARY_PATH=/usr/local/cuda-12.1/lib64::/usr/local/cuda-12.1/lib64:" >> $GITHUB_ENV
      echo "PROJECT_ID=12" >> $GITHUB_ENV
    env:
        HF_TOKEN_SECRET: ${{ inputs.hf_token }}
    shell: bash
