group: Basic Correctness
depends_on: 
  - image-build
steps:
- label: Basic Correctness
  key: basic-correctness
  timeout_in_minutes: 68
  device: h200_18gb
  source_file_dependencies:
  - vllm/
  - tests/basic_correctness/test_basic_correctness
  - tests/basic_correctness/test_cpu_offload
  - tests/basic_correctness/test_mem.py
  commands:
  - export VLLM_WORKER_MULTIPROC_METHOD=spawn
  - pytest -v -s basic_correctness/test_mem.py
  - pytest -v -s basic_correctness/test_basic_correctness.py
  - pytest -v -s basic_correctness/test_cpu_offload.py
  mirror:
    amd:
      dind: false
      device: mi300_1
      timeout_in_minutes: 60

- label: Basic Correctness (Distributed)
  key: basic-correctness-distributed
  timeout_in_minutes: 30
  device: a100
  num_devices: 2
  source_file_dependencies:
  - vllm/config/parallel.py
  - vllm/distributed/device_communicators/ray_communicator.py
  - vllm/v1/executor/
  - vllm/v1/engine/llm_engine.py
  - tests/basic_correctness/test_basic_correctness.py
  commands:
  - export VLLM_WORKER_MULTIPROC_METHOD=spawn
  - TARGET_TEST_SUITE=A100 pytest -v -s basic_correctness/ -m 'distributed(num_gpus=2)'
  mirror:
    amd:
      device: mi300_2
      dind: false
      commands:
      - export VLLM_WORKER_MULTIPROC_METHOD=spawn
      - TARGET_TEST_SUITE=MI300 pytest -v -s basic_correctness/ -m 'distributed(num_gpus=2)'
