group: Basic Correctness
depends_on: 
  - image-build
steps:
- label: ":nvidia: (H200 MIG 18GB) Basic Correctness %N"
  key: basic-correctness
  timeout_in_minutes: 68
  device: h200_18gb
  parallelism: 5
  source_file_dependencies:
  - vllm/
  - "!vllm/distributed/kv_transfer/"
  - tests/basic_correctness/
  commands:
  - export VLLM_WORKER_MULTIPROC_METHOD=spawn
  - |
    case "$$BUILDKITE_PARALLEL_JOB" in
      0) pytest -v -s basic_correctness/test_mem.py ;;  # target: <=20m
      1) pytest -v -s basic_correctness/test_models_gemma2.py basic_correctness/test_basic_correctness.py ;;  # target: <=20m
      2) pytest -v -s basic_correctness/test_models_llama.py ;;  # target: <=20m
      3) pytest -v -s basic_correctness/test_cpu_offload.py ;;  # target: <=20m
      4) pytest -v -s basic_correctness/test_prefetch_offload.py ;;  # target: <=20m
      *) exit 2 ;;
    esac
  mirror:
    amd:
      label: ":amd: (MI300) Basic Correctness"
      dind: false
      device: mi300_1
      parallelism: 1
      timeout_in_minutes: 60
      depends_on:
      - image-build-amd
      commands:
      - export VLLM_WORKER_MULTIPROC_METHOD=spawn
      - pytest -v -s basic_correctness/test_mem.py
      - pytest -v -s basic_correctness/test_models_gemma2.py basic_correctness/test_models_llama.py basic_correctness/test_basic_correctness.py
      - pytest -v -s basic_correctness/test_cpu_offload.py
      - pytest -v -s basic_correctness/test_prefetch_offload.py
