group: Ray Compatibility
depends_on:
  - image-build
steps:
- label: Ray Dependency Compatibility Check
  # Informational only — does not block the pipeline.
  # If this fails, it means the PR introduces a dependency that
  # conflicts with Ray's lock file (ray_test_py311_cu128.lock).
  # See https://github.com/vllm-project/vllm/issues/33599
  soft_fail: true
  device: cpu
  timeout_in_minutes: 10
  source_file_dependencies:
  - requirements/
  - setup.py
  commands:
  - bash /vllm-workspace/.buildkite/scripts/check-ray-compatibility.sh
