group: RL
depends_on: 
  - image-build
steps:
- label: ":nvidia: (H200 MIG 35GB) RL Entrypoints"
  device: h200_35gb
  key: rl-entrypoints-tests
  timeout_in_minutes: 40
  working_dir: "/vllm-workspace/tests"
  source_file_dependencies:
  - vllm/
  - "!vllm/distributed/kv_transfer/"
  - tests/entrypoints/rl
  commands:
  - pytest -v -s entrypoints/rl/weight_transfer
  - export VLLM_WORKER_MULTIPROC_METHOD=spawn
  - pytest -v -s entrypoints/rl --ignore=entrypoints/rl/weight_transfer
  mirror:
    amd:
      label: ":amd: (MI355 DPX) RL Entrypoints"
      dind: false
      device: mi355_dpx
      timeout_in_minutes: 50
      depends_on:
      - image-build-amd
