// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: Copyright contributors to the vLLM project

//! Roundtrip tests for the real chat-template and output-processor pairing.
//!
//! The invariant under test is that a structured assistant message rendered as history can be
//! parsed from the generated assistant completion and then rendered back to the exact same
//! assistant completion.
//!
//! The tool-call fixture also snapshots the output grammar built by the initialized parser for each
//! tool-choice variant, with the rendered completion as its generation, as one file per model under
//! `tests/grammar_replay/`. `grammar_replay.rs` replays these cases through the real XGrammar.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Debug;
use std::ops::Range;
use std::path::PathBuf;
use std::pin::Pin;
use std::sync::Arc;

use anyhow::{Context as _, Result, bail, ensure};
use futures::{Stream, StreamExt as _, stream};
use serde::ser::Error as _;
use serde::{Serialize, Serializer};
use serde_json_fmt::JsonFormat as JsonFmt;
use serial_test::file_serial;
use vllm_chat::{
    AssistantContentBlock, AssistantMessage, AssistantMessageExt as _, AssistantToolCall,
    ChatEvent, ChatMessage, ChatRequest, ChatRole, ChatTool, ChatToolChoice, FinishReason,
    GenerationPromptMode, LoadModelBackendsOptions, NewChatOutputProcessorOptions, ParserSelection,
    RendererSelection, ToolStrictLevel, load_model_backends,
};
use vllm_parser::output_grammar::BuiltOutputGrammar;
use vllm_text::{DecodedTextEvent, Finished, Prompt};
use vllm_tokenizer::Tokenizer;

const TEXT_COMPLETION_CHUNK_CHARS: usize = 7;
const TOKEN_COMPLETION_CHUNK_TOKENS: usize = 1;

/// One model/parser configuration used to run the fixed roundtrip fixtures.
#[derive(Clone)]
struct RoundtripCase {
    /// Hugging Face model id or local checkpoint resolved through the production backend loader.
    model_id: &'static str,
    /// Final assistant-history suffix rendered by the chat template but not
    /// generated by the model body consumed by the output processor.
    // TODO: we should adopt `ContinueFinalAssistant` mode to naturally handle this.
    assistant_stop_suffix: &'static str,
    /// Tool parser selection used by the output processor.
    tool_call_parser: ParserSelection,
    /// Reasoning parser selection used by the output processor.
    reasoning_parser: ParserSelection,
    /// How this model's chat template handles thinking mode.
    thinking_behavior: ThinkingBehavior,
    /// JSON formatting expected after this model's template has materialized
    /// tool-call arguments.
    json_fmt: JsonFmt,
    /// Whether the template renders tool-call argument object keys in sorted order.
    sort_json_keys: bool,
}

#[derive(Clone, Copy)]
enum ThinkingBehavior {
    /// The chat template accepts explicit thinking on/off kwargs, and uses
    /// `default` when the request does not specify either kwarg.
    Toggleable { default: bool },
    /// The chat template always behaves as `value` for this fixture.
    Always { value: bool },
    /// The chat template selects thinking mode through `reasoning_effort`.
    ReasoningEffort {
        default: bool,
        enabled: &'static str,
        disabled: &'static str,
    },
}

impl ThinkingBehavior {
    fn default(self) -> bool {
        match self {
            Self::Toggleable { default } => default,
            Self::Always { value } => value,
            Self::ReasoningEffort { default, .. } => default,
        }
    }

    fn fixtures(self) -> Vec<Option<bool>> {
        match self {
            Self::Toggleable { .. } => vec![
                Some(true),  // explicitly enable thinking
                Some(false), // explicitly disable thinking
                None,        // use default template behavior
            ],
            Self::Always { value } => vec![
                Some(value), // explicitly request the supported thinking behavior
                None,        // use default template behavior
            ],
            Self::ReasoningEffort { .. } => vec![
                Some(true),  // explicitly enable thinking
                Some(false), // explicitly disable thinking
                None,        // use default template behavior
            ],
        }
    }

    fn apply(self, request: &mut ChatRequest, thinking: Option<bool>) {
        let Some(thinking) = thinking else {
            return;
        };

        match self {
            Self::Toggleable { .. } | Self::Always { .. } => {
                for key in ["thinking", "enable_thinking"] {
                    request.chat_options.template_kwargs.insert(key.to_string(), thinking.into());
                }
            }
            Self::ReasoningEffort {
                enabled, disabled, ..
            } => {
                request.chat_options.template_kwargs.insert(
                    "reasoning_effort".to_string(),
                    if thinking { enabled } else { disabled }.into(),
                );
            }
        }
    }
}

/// Tool-choice variant of the tool-call fixture.
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize)]
#[serde(rename_all = "snake_case")]
enum ToolChoiceVariant {
    /// `auto`, with content before the tool calls.
    Auto,
    /// `required`, with tool calls only: builder grammars admit no content
    /// before the calls.
    Required,
    /// Named `get_weather`, with a single call to it and no content.
    Named,
}

impl ToolChoiceVariant {
    const ALL: [Self; 3] = [Self::Auto, Self::Required, Self::Named];

    fn tool_choice(self) -> ChatToolChoice {
        match self {
            Self::Auto => ChatToolChoice::Auto,
            Self::Required => ChatToolChoice::Required,
            Self::Named => ChatToolChoice::Function {
                name: "get_weather".to_string(),
            },
        }
    }
}

impl RoundtripCase {
    /// Qwen3 XML tool-call format with `qwen3` reasoning tags.
    fn qwen3() -> Self {
        Self {
            model_id: "Qwen/Qwen3-0.6B",
            assistant_stop_suffix: "<|im_end|>\n",
            tool_call_parser: ParserSelection::Auto,
            reasoning_parser: ParserSelection::Auto,
            thinking_behavior: ThinkingBehavior::Toggleable { default: true },
            json_fmt: spaced_json_fmt(),
            sort_json_keys: false,
        }
    }

    /// Qwen3.5 coder-style JSON tool-call format with `qwen3` reasoning tags.
    fn qwen35() -> Self {
        Self {
            model_id: "Qwen/Qwen3.5-4B",
            assistant_stop_suffix: "<|im_end|>\n",
            tool_call_parser: ParserSelection::Auto,
            reasoning_parser: ParserSelection::Auto,
            thinking_behavior: ThinkingBehavior::Toggleable { default: true },
            json_fmt: compact_json_fmt(),
            sort_json_keys: false,
        }
    }

    /// MiMo V2.6 uses bare reasoning and Qwen Coder tool tags.
    fn mimo_v26() -> Self {
        Self {
            model_id: "XiaomiMiMo/MiMo-V2.6-Flash-RL",
            assistant_stop_suffix: "<|im_end|>",
            tool_call_parser: ParserSelection::Auto,
            reasoning_parser: ParserSelection::Auto,
            thinking_behavior: ThinkingBehavior::Toggleable { default: true },
            json_fmt: compact_json_fmt(),
            sort_json_keys: false,
        }
    }

    /// MiniMax M2.5 XML invoke format with `<think>` reasoning tags.
    fn minimax_m25() -> Self {
        Self {
            model_id: "MiniMaxAI/MiniMax-M2.5",
            assistant_stop_suffix: "[e~[\n",
            tool_call_parser: ParserSelection::Auto,
            reasoning_parser: ParserSelection::Auto,
            thinking_behavior: ThinkingBehavior::Always { value: true },
            json_fmt: compact_json_fmt(),
            sort_json_keys: false,
        }
    }

    /// MiniMax M3 invoke format with `<mm:think>` reasoning tags.
    fn minimax_m3() -> Self {
        Self {
            model_id: "MiniMaxAI/MiniMax-M3",
            assistant_stop_suffix: "[e~[\n",
            tool_call_parser: ParserSelection::Auto,
            reasoning_parser: ParserSelection::Auto,
            thinking_behavior: ThinkingBehavior::Always { value: true },
            json_fmt: compact_json_fmt(),
            sort_json_keys: false,
        }
    }

    /// DeepSeek V4 DSML tool-call format.
    fn deepseek_v4() -> Self {
        Self {
            model_id: "deepseek-ai/DeepSeek-V4-Flash",
            assistant_stop_suffix: "<｜end▁of▁sentence｜>",
            tool_call_parser: ParserSelection::Auto,
            reasoning_parser: ParserSelection::Auto,
            thinking_behavior: ThinkingBehavior::Toggleable { default: false },
            json_fmt: compact_json_fmt(),
            sort_json_keys: false,
        }
    }

    /// DeepSeek V4.1 Flash DSML tool-call format.
    fn deepseek_v41() -> Self {
        Self {
            model_id: "deepseek-ai/DeepSeek-V4.1-Flash",
            assistant_stop_suffix: "<｜end▁of▁sentence｜>",
            tool_call_parser: ParserSelection::Auto,
            reasoning_parser: ParserSelection::Auto,
            thinking_behavior: ThinkingBehavior::Toggleable { default: true },
            json_fmt: compact_json_fmt(),
            sort_json_keys: false,
        }
    }

    /// DeepSeek V3.2 DSML tool-call format.
    fn deepseek_v32() -> Self {
        Self {
            model_id: "deepseek-ai/DeepSeek-V3.2-Exp",
            assistant_stop_suffix: "<｜end▁of▁sentence｜>",
            tool_call_parser: ParserSelection::Auto,
            reasoning_parser: ParserSelection::Auto,
            thinking_behavior: ThinkingBehavior::Toggleable { default: false },
            json_fmt: compact_json_fmt(),
            sort_json_keys: false,
        }
    }

    /// GLM-4.5 XML-like argument format with `<think>` reasoning tags.
    fn glm45() -> Self {
        Self {
            model_id: "zai-org/GLM-4.5",
            assistant_stop_suffix: "",
            tool_call_parser: ParserSelection::Auto,
            reasoning_parser: ParserSelection::Auto,
            thinking_behavior: ThinkingBehavior::Toggleable { default: true },
            json_fmt: compact_json_fmt(),
            sort_json_keys: false,
        }
    }

    /// GLM-4.7 XML-like argument format with `<think>` reasoning tags.
    fn glm47() -> Self {
        Self {
            model_id: "zai-org/GLM-4.7-Flash",
            assistant_stop_suffix: "",
            tool_call_parser: ParserSelection::Auto,
            reasoning_parser: ParserSelection::Auto,
            thinking_behavior: ThinkingBehavior::Toggleable { default: true },
            json_fmt: compact_json_fmt(),
            sort_json_keys: false,
        }
    }

    /// GLM-5.2 XML-like argument format with `<think>` reasoning tags.
    fn glm52() -> Self {
        Self {
            model_id: "zai-org/GLM-5.2-FP8",
            assistant_stop_suffix: "",
            tool_call_parser: ParserSelection::Auto,
            reasoning_parser: ParserSelection::Auto,
            thinking_behavior: ThinkingBehavior::Toggleable { default: true },
            json_fmt: compact_json_fmt(),
            sort_json_keys: false,
        }
    }

    /// Gemma4 channel reasoning with custom function-call arguments.
    fn gemma4() -> Self {
        Self {
            model_id: "google/gemma-4-E4B-it",
            assistant_stop_suffix: "<|tool_response>",
            tool_call_parser: ParserSelection::Auto,
            reasoning_parser: ParserSelection::Auto,
            thinking_behavior: ThinkingBehavior::Always { value: true },
            json_fmt: compact_json_fmt(),
            sort_json_keys: true,
        }
    }

    /// Gemma4 through the checkpoint's `response_template` (`hf` parser).
    fn gemma4_hf() -> Self {
        Self {
            tool_call_parser: ParserSelection::Explicit("hf".to_string()),
            reasoning_parser: ParserSelection::Explicit("hf".to_string()),
            ..Self::gemma4()
        }
    }

    /// Kimi K2.5 tool-call format with `<think>` reasoning tags.
    #[allow(dead_code)]
    fn kimi_k25() -> Self {
        Self {
            model_id: "moonshotai/Kimi-K2.5",
            assistant_stop_suffix: "<|im_end|>",
            tool_call_parser: ParserSelection::Auto,
            reasoning_parser: ParserSelection::Auto,
            thinking_behavior: ThinkingBehavior::Toggleable { default: true },
            json_fmt: spaced_json_fmt(),
            sort_json_keys: false,
        }
    }

    /// Kimi K3 XTML tool/reasoning channels (native renderer + unified parser).
    ///
    /// Needs HF tokenizer files under `HF_HOME` (`tiktoken.model` +
    /// `tokenizer_config.json`). Weights are not required for this text-level
    /// roundtrip.
    fn kimi_k3() -> Self {
        Self {
            model_id: "moonshotai/Kimi-K3",
            assistant_stop_suffix: "<|end_of_msg|>",
            tool_call_parser: ParserSelection::Auto,
            reasoning_parser: ParserSelection::Auto,
            thinking_behavior: ThinkingBehavior::Toggleable { default: true },
            json_fmt: compact_json_fmt(),
            sort_json_keys: false,
        }
    }

    /// HY3 suffixed reasoning/tool markers discovered from tokenizer added vocab.
    fn hy_v3() -> Self {
        Self {
            model_id: "tencent/Hy3",
            assistant_stop_suffix: "<｜hy_eos:opensource｜>",
            tool_call_parser: ParserSelection::Auto,
            reasoning_parser: ParserSelection::Auto,
            thinking_behavior: ThinkingBehavior::ReasoningEffort {
                default: false,
                enabled: "high",
                disabled: "no_think",
            },
            json_fmt: compact_json_fmt(),
            sort_json_keys: false,
        }
    }

    /// SeedOSS with `<seed:think>` / `</seed:think>` reasoning tags.
    fn seed_oss() -> Self {
        Self {
            model_id: "ByteDance-Seed/Seed-OSS-36B-Instruct",
            assistant_stop_suffix: "<seed:eos>",
            tool_call_parser: ParserSelection::Auto,
            reasoning_parser: ParserSelection::Auto,
            thinking_behavior: ThinkingBehavior::Always { value: true },
            json_fmt: compact_json_fmt(),
            sort_json_keys: false,
        }
    }

    /// Step-3.5 with `<think>` / `</think>` reasoning tags and newline trimming.
    fn step3p5() -> Self {
        Self {
            model_id: "stepfun-ai/Step-3.5-Flash",
            assistant_stop_suffix: "<|im_end|>\n",
            tool_call_parser: ParserSelection::Auto,
            reasoning_parser: ParserSelection::Auto,
            thinking_behavior: ThinkingBehavior::Always { value: true },
            json_fmt: compact_json_fmt(),
            sort_json_keys: false,
        }
    }

    /// Nemotron V3 with `<think>` / `</think>` reasoning tags.
    fn nemotron_v3() -> Self {
        Self {
            model_id: "nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16",
            assistant_stop_suffix: "<|im_end|>\n",
            tool_call_parser: ParserSelection::Auto,
            reasoning_parser: ParserSelection::Auto,
            thinking_behavior: ThinkingBehavior::Always { value: true },
            json_fmt: compact_json_fmt(),
            sort_json_keys: false,
        }
    }

    /// GPT-OSS Harmony token-id renderer and native Harmony output processor.
    fn gpt_oss() -> Self {
        Self {
            model_id: "openai/gpt-oss-20b",
            assistant_stop_suffix: "",
            tool_call_parser: ParserSelection::Auto,
            reasoning_parser: ParserSelection::Auto,
            thinking_behavior: ThinkingBehavior::Always { value: true },
            json_fmt: compact_json_fmt(),
            sort_json_keys: false,
        }
    }

    /// Inkling typed content blocks with native token-id rendering.
    fn inkling() -> Self {
        Self {
            model_id: "thinkingmachines/Inkling",
            assistant_stop_suffix: "<|content_model_end_sampling|>",
            tool_call_parser: ParserSelection::Auto,
            reasoning_parser: ParserSelection::Auto,
            thinking_behavior: ThinkingBehavior::Always { value: true },
            json_fmt: compact_json_fmt(),
            sort_json_keys: true,
        }
    }
}

macro_rules! roundtrip_tests {
    ($($case:ident => $(#[$case_attr:meta])* [$($fixture:ident),* $(,)?]),+ $(,)?) => {
        paste::paste! {
            $(
                #[tokio::test]
                #[file_serial([<hf_ $case>])]
                $(#[$case_attr])*
                async fn [<roundtrip_ $case>]() -> Result<()> {
                    let case = RoundtripCase::$case();
                    let backends = load_roundtrip_backends(&case).await?;
                    $(
                        [<run_roundtrip_ $fixture>](&case, &backends).await?;
                    )*
                    Ok(())
                }
            )+
        }
    };
}

roundtrip_tests! {
    qwen3 => [reasoning_and_content, tool_call_mix],
    qwen35 => [reasoning_and_content, tool_call_mix],
    mimo_v26 => [reasoning_and_content, tool_call_mix],
    minimax_m25 => [reasoning_and_content, tool_call_mix],
    minimax_m3 => [reasoning_and_content, tool_call_mix],
    deepseek_v4 => [reasoning_and_content, tool_call_mix],
    deepseek_v41 => [reasoning_and_content, tool_call_mix],
    deepseek_v32 => [tool_call_mix],
    glm45 => [reasoning_and_content, tool_call_mix],
    glm47 => [reasoning_and_content, tool_call_mix],
    glm52 => [reasoning_and_content, tool_call_mix],
    seed_oss => [reasoning_and_content, tool_call_mix],
    step3p5 => [reasoning_and_content],
    nemotron_v3 => [reasoning_and_content],
    gemma4 => [tool_call_mix], // Gemma4 strips reasoning in history if there's no tool call
    gemma4_hf => [tool_call_mix],
    kimi_k25 => [tool_call_mix], // Kimi K2.5 strips reasoning in history
    // K3 drops plain-assistant reasoning in history; tool-call turns keep it.
    kimi_k3 => [tool_call_mix],
    // HY3's final plain-assistant history omits EOS; tool-call history keeps it
    // and exercises both stages of the tokenizer-derived unified parser.
    hy_v3 => [tool_call_mix],
    gpt_oss => [tool_call_mix], // Harmony strips reasoning in history if there's no tool call
    inkling => [reasoning_and_content, tool_call_mix],
}

/// Run the fixed reasoning+content fixture for one model/parser case.
async fn run_roundtrip_reasoning_and_content(
    case: &RoundtripCase,
    backends: &vllm_chat::LoadedModelBackends,
) -> Result<()> {
    for thinking in case.thinking_behavior.fixtures() {
        run_roundtrip_reasoning_and_content_inner(case, backends, thinking).await?;
    }
    Ok(())
}

async fn run_roundtrip_reasoning_and_content_inner(
    case: &RoundtripCase,
    backends: &vllm_chat::LoadedModelBackends,
    thinking: Option<bool>,
) -> Result<()> {
    let request = roundtrip_request(
        "roundtrip-reasoning-content",
        vec![ChatMessage::text(ChatRole::User, "What is 2 + 2?")],
        Vec::new(),
        None,
        thinking,
        case.thinking_behavior,
    );
    let expected_reasoning = "Need compute 2 + 2 directly.";
    let expected_text = "The answer is 4.";
    let effective_thinking = thinking.unwrap_or(case.thinking_behavior.default());

    let assistant = {
        let mut content = Vec::new();
        if effective_thinking {
            content.push(AssistantContentBlock::Reasoning {
                text: expected_reasoning.to_string(),
            });
        }
        content.push(AssistantContentBlock::Text {
            text: expected_text.to_string(),
        });
        AssistantMessage { content }
    };
    let result = run_roundtrip(case, backends, &request, assistant).await?;

    assert_eq!(
        result.parsed_message.reasoning().as_deref(),
        effective_thinking.then_some(expected_reasoning),
        "parsed message: {:#?}",
        result.parsed_message
    );
    assert_eq!(result.parsed_message.text(), expected_text);
    assert_eq!(result.parsed_message.tool_calls().count(), 0);

    assert_eq!(
        result.rerendered_closed_completion,
        result.closed_completion
    );

    Ok(())
}

/// Run the fixed reasoning+multiple-tools fixture for one model/parser case,
/// once per tool-choice variant.
async fn run_roundtrip_tool_call_mix(
    case: &RoundtripCase,
    backends: &vllm_chat::LoadedModelBackends,
) -> Result<()> {
    let mut results = Vec::new();
    for variant in ToolChoiceVariant::ALL {
        let result = run_roundtrip_tool_call_mix_inner(case, backends, variant).await?;
        results.push((variant, result));
    }
    check_grammar_replay_file(case, backends, results)
}

async fn run_roundtrip_tool_call_mix_inner(
    case: &RoundtripCase,
    backends: &vllm_chat::LoadedModelBackends,
    variant: ToolChoiceVariant,
) -> Result<RoundtripResult> {
    let request = roundtrip_request(
        "roundtrip-reasoning-tools",
        vec![ChatMessage::text(
            ChatRole::User,
            "Check Shanghai weather and add 1.0 plus 2.",
        )],
        test_tools(),
        Some(variant.tool_choice()),
        Some(true), // always enable thinking in this fixture
        case.thinking_behavior,
    );
    let expected_reasoning = "Need call the weather and add tools.";
    let (expected_text, tool_call_count) = match variant {
        ToolChoiceVariant::Auto => (Some("I will call the tools."), 2),
        ToolChoiceVariant::Required => (None, 2),
        ToolChoiceVariant::Named => (None, 1),
    };

    let mut content = vec![AssistantContentBlock::Reasoning {
        text: expected_reasoning.to_string(),
    }];
    content.extend(expected_text.map(|text| AssistantContentBlock::Text {
        text: text.to_string(),
    }));
    let tool_calls = [
        AssistantContentBlock::ToolCall(AssistantToolCall {
            id: "functions.get_weather:0".to_string(),
            name: "get_weather".to_string(),
            arguments: r#"{"location":"Shanghai"}"#.to_string(),
        }),
        AssistantContentBlock::ToolCall(AssistantToolCall {
            id: "functions.add:1".to_string(),
            name: "add".to_string(),
            // Intentionally use a non-lexical order of keys to verify text-level
            // fidelity of the roundtrip where JSON formatting remains stable. The
            // `items` key also exercises templates that call `arguments.items()`.
            arguments: r#"{"y":1.0,"x":2,"items":["left","right"]}"#.to_string(),
        }),
    ];
    content.extend(tool_calls.into_iter().take(tool_call_count));
    let result = run_roundtrip(case, backends, &request, AssistantMessage { content }).await?;

    assert_eq!(
        result.parsed_message.reasoning().as_deref(),
        Some(expected_reasoning),
        "parsed message: {:#?}",
        result.parsed_message
    );
    assert_eq!(
        result.parsed_message.text(),
        expected_text.unwrap_or_default()
    );

    let tool_calls = result.parsed_message.tool_calls().collect::<Vec<_>>();
    assert_eq!(
        tool_calls.len(),
        tool_call_count,
        "parsed message: {:#?}",
        result.parsed_message
    );
    assert_eq!(tool_calls[0].name, "get_weather");
    assert_eq!(
        tool_calls[0].arguments,
        expected_arguments(case, r#"{"location": "Shanghai"}"#)?,
    );
    if let Some(add) = tool_calls.get(1) {
        assert_eq!(add.name, "add");
        assert_eq!(
            add.arguments,
            expected_arguments(case, r#"{"y": 1.0, "x": 2, "items": ["left", "right"]}"#)?,
        );
    }

    assert_eq!(
        result.rerendered_closed_completion,
        result.closed_completion
    );

    Ok(result)
}

/// Compact JSON argument formatting used by JSON-native parsers/renderers.
fn compact_json_fmt() -> JsonFmt {
    JsonFmt::new()
}

/// Python `json.dumps`-style compact formatting with a space after commas and
/// colons.
fn spaced_json_fmt() -> JsonFmt {
    JsonFmt::new()
        .comma(", ")
        .expect("literal comma separator is valid JSON")
        .colon(": ")
        .expect("literal colon separator is valid JSON")
}

/// Parse and format expected tool-call arguments from raw JSON text.
/// Pass in a raw JSON string instead of a structured value to ensure the exact precision and
/// formatting of numbers are preserved.
fn expected_arguments(case: &RoundtripCase, raw_json: &str) -> Result<String> {
    let mut value: serde_json::Value =
        serde_json::from_str(raw_json).context("invalid expected tool-call arguments")?;
    if case.sort_json_keys {
        sort_json_value(&mut value);
    }

    case.json_fmt
        .format_to_string(&value)
        .context("failed to format expected tool-call arguments")
}

/// Sort JSON object keys recursively to match templates that render mappings with `dictsort`.
fn sort_json_value(value: &mut serde_json::Value) {
    match value {
        serde_json::Value::Object(map) => {
            for value in map.values_mut() {
                sort_json_value(value);
            }

            let mut entries = std::mem::take(map).into_iter().collect::<Vec<_>>();
            entries.sort_by(|(left, _), (right, _)| left.cmp(right));
            map.extend(entries);
        }
        serde_json::Value::Array(values) => {
            for value in values {
                sort_json_value(value);
            }
        }
        _ => {}
    }
}

/// Load the real model chat/text backend for one roundtrip case.
async fn load_roundtrip_backends(case: &RoundtripCase) -> Result<vllm_chat::LoadedModelBackends> {
    load_model_backends(
        case.model_id,
        LoadModelBackendsOptions {
            renderer: RendererSelection::Auto,
            ..Default::default()
        },
    )
    .await
    .with_context(|| format!("failed to load HF model files for {}", case.model_id))
}

/// Roundtrip artifacts needed for semantic and exact-text assertions.
struct RoundtripResult {
    /// Final assistant message reconstructed by the output processor.
    parsed_message: AssistantMessage,
    /// Assistant-completion suffix cut from rendering the expected assistant as
    /// history.
    closed_completion: Prompt,
    /// Assistant-completion suffix cut after rendering the parsed assistant
    /// back as history.
    rerendered_closed_completion: Prompt,
    /// Output grammar built by the same initialized parser that parsed the
    /// completion.
    output_grammar: Option<BuiltOutputGrammar>,
}

/// Render, parse, and rerender one assistant turn through the production
/// renderer/output-processor boundary.
async fn run_roundtrip(
    case: &RoundtripCase,
    backends: &vllm_chat::LoadedModelBackends,
    request: &ChatRequest,
    assistant: AssistantMessage,
) -> Result<RoundtripResult> {
    let renderer = backends.chat_backend.chat_renderer();
    let rendered = render_closed_completion(renderer.as_ref(), request, &assistant)?;

    let ParsedCompletion {
        message: parsed_message,
        output_grammar,
    } = parse_completion(case, backends, request, &rendered).await?;
    let rerendered = render_closed_completion(renderer.as_ref(), request, &parsed_message)?;

    Ok(RoundtripResult {
        parsed_message,
        closed_completion: rendered.completion,
        rerendered_closed_completion: rerendered.completion,
        output_grammar,
    })
}

/// Rendered prompt/completion artifacts at the renderer boundary.
struct RenderedTurn {
    prompt: Prompt,
    completion: Prompt,
}

/// Render `history` as a production prompt and `history + assistant` as closed
/// history, then return the production prompt and the assistant completion.
fn render_closed_completion(
    renderer: &dyn vllm_chat::ChatRenderer,
    base_request: &ChatRequest,
    assistant: &AssistantMessage,
) -> Result<RenderedTurn> {
    let mut prompt_request = base_request.clone();
    prompt_request.chat_options.generation_prompt_mode = GenerationPromptMode::StartNewAssistant;
    let prompt = renderer.render(&prompt_request).context("failed to render prompt")?.prompt;

    let mut full_request = base_request.clone();
    full_request.chat_options.generation_prompt_mode = GenerationPromptMode::NoGenerationPrompt;
    full_request.messages.push(ChatMessage::from(assistant.clone()));
    let full = renderer.render(&full_request).context("failed to render full prompt")?.prompt;

    let completion = match (&prompt, full) {
        (Prompt::Text(prompt), Prompt::Text(full)) => {
            let range = completion_range(prompt.as_bytes(), full.as_bytes())
                .with_context(|| format!("prompt: {prompt:?}\nfull: {full:?}"))?;
            let completion = full.get(range).context("completion splits a UTF-8 character")?;
            Prompt::Text(completion.to_string())
        }
        (Prompt::TokenIds(prompt), Prompt::TokenIds(full)) => {
            let range = completion_range(prompt, &full)
                .with_context(|| format!("prompt: {prompt:?}\nfull: {full:?}"))?;
            Prompt::TokenIds(full[range].to_vec())
        }
        (prompt, full) => bail!("prompt kind changed between renders: {prompt:?} vs {full:?}"),
    };

    Ok(RenderedTurn { prompt, completion })
}

/// Locate the assistant completion in `full`, the history rendered with the
/// assistant message, given `prompt`, the same history rendered for generation.
///
/// Some templates render request-scoped control messages after the whole
/// history, such as Kimi K3's `tool_choice=required` message. With history `A`,
/// control messages `C`, generation prompt `G`, and completion `B`, the renders
/// are `prompt = A + C + G` and `full = A + G + B + C`. `C` is empty for most
/// templates, which makes `prompt` a prefix of `full`.
fn completion_range<T: PartialEq + Debug>(prompt: &[T], full: &[T]) -> Result<Range<usize>> {
    if full.starts_with(prompt) {
        return Ok(prompt.len()..full.len());
    }
    ensure!(
        full.len() >= prompt.len(),
        "full prompt is shorter than production prompt"
    );

    // `A` is a common prefix of both renders; try every split of the remaining
    // `prompt` into `C + G` and require exactly one to fit `full`.
    let common_prefix_len = prompt.iter().zip(full).take_while(|(p, f)| p == f).count();
    let mut control_lens = Vec::new();
    for history_len in 0..=common_prefix_len {
        let rest = &prompt[history_len..];
        for control_len in 1..=rest.len() {
            let (control, generation) = rest.split_at(control_len);
            if full[history_len..].starts_with(generation) && full.ends_with(control) {
                control_lens.push(control_len);
            }
        }
    }
    let [control_len] = control_lens[..] else {
        bail!(
            "full prompt must be `A + G + B + C` for production prompt `A + C + G`; found {} splits",
            control_lens.len()
        );
    };

    Ok(prompt.len() - control_len..full.len() - control_len)
}

#[test]
fn completion_range_skips_trailing_control_messages() {
    let history = "<user>hi</user>";
    let control = "<system>call tools</system>";
    let generation = "<assistant>";
    let completion = "call()</assistant>";

    let prompt = format!("{history}{generation}");
    let full = format!("{history}{generation}{completion}");
    let range = completion_range(prompt.as_bytes(), full.as_bytes()).unwrap();
    assert_eq!(&full[range], completion);

    let prompt = format!("{history}{control}{generation}");
    let full = format!("{history}{generation}{completion}{control}");
    let range = completion_range(prompt.as_bytes(), full.as_bytes()).unwrap();
    assert_eq!(&full[range], completion);
}

/// Output of one production output processor over a rendered completion.
struct ParsedCompletion {
    /// Terminal assistant message.
    message: AssistantMessage,
    /// Output grammar built by the processor after initialization.
    output_grammar: Option<BuiltOutputGrammar>,
}

/// Feed one rendered assistant completion body into the real output processor
/// and collect its terminal assistant message, along with the output grammar
/// the initialized processor builds for the request.
async fn parse_completion(
    case: &RoundtripCase,
    backends: &vllm_chat::LoadedModelBackends,
    base_request: &ChatRequest,
    rendered: &RenderedTurn,
) -> Result<ParsedCompletion> {
    let tokenizer = backends.text_backend.tokenizer();
    let prompt_token_ids = match &rendered.prompt {
        Prompt::Text(prompt) => tokenizer
            .encode(prompt, base_request.add_special_tokens)
            .context("failed to encode rendered prompt")?,
        Prompt::TokenIds(token_ids) => token_ids.clone(),
    };

    let mut request = base_request.clone();
    let mut processor = backends.chat_backend.new_chat_output_processor(
        &mut request,
        NewChatOutputProcessorOptions {
            // Pin every tool schema so that builder-backed parsers build an
            // output grammar for replay. The strict level does not affect parsing.
            tool_strict_level: ToolStrictLevel::Parameter,
            tool_call_parser: &case.tool_call_parser,
            reasoning_parser: &case.reasoning_parser,
        },
    )?;
    processor.initialize(&prompt_token_ids)?;
    let output_grammar = processor.build_output_grammar()?;

    let decoded = decoded_completion_stream(
        tokenizer.as_ref(),
        prompt_token_ids,
        &rendered.completion,
        case.assistant_stop_suffix,
    )?;
    let mut events = processor.process(decoded)?;

    while let Some(event) = events.next().await {
        if let ChatEvent::Done { message, .. } = event? {
            return Ok(ParsedCompletion {
                message,
                output_grammar,
            });
        }
    }

    bail!("output processor finished without a Done event")
}

/// Build a decoded-text stream from an already-rendered completion body.
///
/// The first event carries real prompt token ids so reasoning parsers can
/// initialize from the same prompt boundary production uses. Completion text is
/// split into small chunks to exercise streaming parser state across marker
/// and JSON boundaries.
fn decoded_completion_stream(
    tokenizer: &dyn Tokenizer,
    prompt_token_ids: Vec<u32>,
    completion: &Prompt,
    assistant_stop_suffix: &str,
) -> Result<Pin<Box<dyn Stream<Item = vllm_chat::Result<DecodedTextEvent>> + Send>>> {
    let mut events = vec![DecodedTextEvent::Start {
        prompt_token_ids: Arc::from(prompt_token_ids.clone().into_boxed_slice()),
        prompt_logprobs: None,
    }];

    let chunks = match completion_body(tokenizer, completion, assistant_stop_suffix)? {
        CompletionBody::Text(body) => {
            // The engine returns token ids, so attribute the rendered text
            // through the production decoder, then split it into small char
            // chunks to exercise marker splits.
            let token_ids =
                tokenizer.encode(body, false).context("failed to encode text completion")?;
            let mut rest = vllm_text::DecodedText::default();
            for chunk in incremental_decode_chunks(
                tokenizer,
                &prompt_token_ids,
                &token_ids,
                TOKEN_COMPLETION_CHUNK_TOKENS,
            )? {
                rest.append(chunk.delta);
            }
            ensure!(
                rest.text == body,
                "text completion must roundtrip through the tokenizer\nbody: {body:?}\ndecoded: {:?}",
                rest.text
            );
            split_by_chars(body, TEXT_COMPLETION_CHUNK_CHARS)
                .into_iter()
                .map(|delta| DecodedCompletionChunk {
                    delta: rest.drain_prefix(delta.len()),
                    token_ids: Vec::new(), // unused for text-level roundtrip cases
                })
                .collect()
        }
        CompletionBody::TokenIds(body) => incremental_decode_chunks(
            tokenizer,
            &prompt_token_ids,
            body,
            TOKEN_COMPLETION_CHUNK_TOKENS,
        )?,
    };

    if chunks.is_empty() {
        events.push({
            DecodedTextEvent::TextDelta {
                decoded: vllm_text::DecodedText::default(),
                sampled: vllm_text::SampledDelta::default(),
                finished: Some(Box::new(Finished {
                    usage: Default::default(),
                    finish_reason: FinishReason::stop_eos(),
                    kv_transfer_params: None,
                    ec_transfer_params: None,
                    sampling_mask: None,
                    timestamps: Default::default(),
                })),
            }
        });
    } else {
        let last_index = chunks.len() - 1;
        for (index, chunk) in chunks.into_iter().enumerate() {
            let finished = (index == last_index).then(|| Finished {
                usage: Default::default(),
                finish_reason: FinishReason::stop_eos(),
                kv_transfer_params: None,
                ec_transfer_params: None,
                sampling_mask: None,
                timestamps: Default::default(),
            });
            events.push(DecodedTextEvent::TextDelta {
                decoded: chunk.delta,
                sampled: vllm_text::SampledDelta {
                    token_ids: chunk.token_ids,
                    logprobs: None,
                },
                finished: finished.map(Box::new),
            });
        }
    }

    Ok(stream::iter(events).map(Ok).boxed())
}

/// Generated part of a closed assistant completion, without the rendered stop
/// suffix.
enum CompletionBody<'a> {
    Text(&'a str),
    TokenIds(&'a [u32]),
}

/// Strip the rendered stop suffix from a closed assistant completion.
fn completion_body<'a>(
    tokenizer: &dyn Tokenizer,
    completion: &'a Prompt,
    assistant_stop_suffix: &str,
) -> Result<CompletionBody<'a>> {
    match completion {
        Prompt::Text(text) => {
            let body = text.strip_suffix(assistant_stop_suffix).with_context(|| {
                format!(
                    "closed assistant completion did not end with {:?}: {:?}",
                    assistant_stop_suffix, text
                )
            })?;
            Ok(CompletionBody::Text(body))
        }
        Prompt::TokenIds(token_ids) => {
            let body = if assistant_stop_suffix.is_empty() {
                token_ids.as_slice()
            } else {
                let stop_token_ids = tokenizer
                    .encode(assistant_stop_suffix, false)
                    .context("failed to encode token-id completion stop suffix")?;
                token_ids.strip_suffix(stop_token_ids.as_slice()).with_context(|| {
                    format!(
                        "token-id completion did not end with {:?}: {:?}",
                        assistant_stop_suffix, token_ids
                    )
                })?
            };
            Ok(CompletionBody::TokenIds(body))
        }
    }
}

/// One decoded completion chunk fed into the output processor.
struct DecodedCompletionChunk {
    /// Attributed for token-id completions, as the production decoder emits it.
    delta: vllm_text::DecodedText,
    token_ids: Vec<u32>,
}

/// Split text into chunks containing at most `chunk_chars` Unicode scalar
/// values.
fn split_by_chars(text: &str, chunk_chars: usize) -> Vec<String> {
    let mut chunks = Vec::new();
    let mut start = 0;
    let mut count = 0;

    for (index, _) in text.char_indices() {
        if count == chunk_chars {
            chunks.push(text[start..index].to_string());
            start = index;
            count = 0;
        }
        count += 1;
    }

    if start < text.len() {
        chunks.push(text[start..].to_string());
    }

    chunks
}

/// Split token ids into chunks containing at most `chunk_size` ids.
fn split_by_count(token_ids: &[u32], chunk_size: usize) -> Vec<Vec<u32>> {
    token_ids.chunks(chunk_size).map(<[u32]>::to_vec).collect()
}

/// Decode token ids incrementally using the production tokenizer stream.
fn incremental_decode_chunks(
    tokenizer: &dyn Tokenizer,
    prompt_token_ids: &[u32],
    token_ids: &[u32],
    chunk_size: usize,
) -> Result<Vec<DecodedCompletionChunk>> {
    let mut decoder = tokenizer.create_decode_stream(prompt_token_ids, false, 0);
    let mut chunks = Vec::new();
    for chunk_token_ids in split_by_count(token_ids, chunk_size) {
        let mut delta = vllm_text::DecodedText::default();
        for token_id in chunk_token_ids.iter().copied() {
            decoder.push_token(token_id)?;
            while let Some(chunk) = decoder.next_chunk() {
                delta.append(chunk);
            }
        }
        chunks.push(DecodedCompletionChunk {
            delta,
            token_ids: chunk_token_ids,
        });
    }

    let (last_chunk, _) = decoder.flush(None)?;
    if let Some(last_chunk) = last_chunk {
        if let Some(delta) = chunks.last_mut() {
            delta.delta.append(last_chunk);
        } else {
            chunks.push(DecodedCompletionChunk {
                delta: last_chunk,
                token_ids: Vec::new(),
            });
        }
    }

    Ok(chunks)
}

/// Grammar replay cases of one model, replayed through the real XGrammar by
/// `grammar_replay.py`.
#[derive(Serialize)]
struct GrammarReplayFile {
    /// Hugging Face model id whose tokenizer the replay loads.
    model_id: &'static str,
    /// Model vocabulary size, which sizes the XGrammar token mask.
    vocab_size: usize,
    /// Request stop set, passed to the matcher as `override_stop_tokens`.
    #[serde(serialize_with = "serialize_one_line")]
    all_stop_token_ids: BTreeSet<u32>,
    /// Cases keyed by tool-choice variant.
    cases: BTreeMap<ToolChoiceVariant, GrammarReplayCase>,
}

/// One parser-built output grammar with the generation it must accept.
#[derive(Serialize)]
struct GrammarReplayCase {
    /// Parser-built grammar; only token-zero grammars are replayed from the
    /// first generated token.
    grammar: BuiltOutputGrammar,
    /// Generated completion text, without the stop token.
    completion: String,
    /// Generated token IDs presented to the matcher, ending with a stop token.
    #[serde(serialize_with = "serialize_one_line")]
    generation_token_ids: Vec<u32>,
}

/// Serialize a token ID list on one line inside the pretty-printed file.
fn serialize_one_line<S: Serializer>(
    token_ids: &impl Serialize,
    serializer: S,
) -> std::result::Result<S::Ok, S::Error> {
    let json = spaced_json_fmt().format_to_string(token_ids).map_err(S::Error::custom)?;
    serde_json::value::RawValue::from_string(json)
        .map_err(S::Error::custom)?
        .serialize(serializer)
}

/// Directory of checked-in grammar replay files.
fn grammar_replay_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/grammar_replay")
}

/// Snapshot the output grammars of one model's roundtrips, keyed by variant,
/// as its grammar replay file, or check that no stale file remains when the
/// parser builds none.
fn check_grammar_replay_file(
    case: &RoundtripCase,
    backends: &vllm_chat::LoadedModelBackends,
    results: Vec<(ToolChoiceVariant, RoundtripResult)>,
) -> Result<()> {
    let model_name = case.model_id.rsplit_once('/').map_or(case.model_id, |(_, name)| name);
    let path = grammar_replay_dir().join(format!("{model_name}.json"));
    let outline_path = path.with_extension("txt");
    let results = results
        .into_iter()
        .filter_map(|(variant, result)| {
            Some((variant, result.output_grammar?, result.closed_completion))
        })
        .collect::<Vec<_>>();
    if results.is_empty() {
        for path in [&path, &outline_path] {
            ensure!(
                !path.exists(),
                "{} builds no output grammar, but grammar replay file {path:?} exists",
                case.model_id
            );
        }
        return Ok(());
    }

    let tokenizer = backends.text_backend.tokenizer();
    let hints = backends.text_backend.sampling_hints()?;
    // Lowered `_all_stop_token_ids` of a request without user stop tokens.
    let mut all_stop_token_ids = hints.extra_eos_token_ids;
    all_stop_token_ids.extend(hints.primary_eos_token_id);

    // The generation ends with the first token of the rendered stop suffix, or
    // with the primary EOS for templates that render none.
    let stop_token_id = if case.assistant_stop_suffix.is_empty() {
        hints.primary_eos_token_id.context("model has no primary EOS token")?
    } else {
        tokenizer.encode(case.assistant_stop_suffix, false)?[0]
    };
    ensure!(
        all_stop_token_ids.contains(&stop_token_id),
        "stop token {stop_token_id} of {:?} is not in the stop set {all_stop_token_ids:?}",
        case.assistant_stop_suffix
    );

    let mut cases = BTreeMap::new();
    for (variant, grammar, closed_completion) in results {
        let (completion, mut generation_token_ids) = match completion_body(
            tokenizer.as_ref(),
            &closed_completion,
            case.assistant_stop_suffix,
        )? {
            CompletionBody::Text(body) => (body.to_string(), tokenizer.encode(body, false)?),
            CompletionBody::TokenIds(body) => (tokenizer.decode(body, false)?, body.to_vec()),
        };
        generation_token_ids.push(stop_token_id);
        cases.insert(
            variant,
            GrammarReplayCase {
                grammar,
                completion,
                generation_token_ids,
            },
        );
    }

    // A readable outline of the same grammars, for review only.
    let mut outline = String::new();
    for (variant, case) in &cases {
        if !outline.is_empty() {
            outline.push('\n');
        }
        let variant = serde_json::to_value(variant)?;
        let coverage = serde_json::to_value(case.grammar.coverage)?;
        outline.push_str(&format!(
            "# {} ({})\n",
            variant.as_str().context("variant name")?,
            coverage.as_str().context("coverage name")?,
        ));
        outline.push_str(&vllm_parser::output_grammar::test_utils::outline(
            &case.grammar.format,
        ));
    }
    expect_test::expect_file![outline_path].assert_eq(&outline);

    let file = GrammarReplayFile {
        model_id: case.model_id,
        vocab_size: backends.text_backend.model_vocab_size(),
        all_stop_token_ids,
        cases,
    };
    let mut json = serde_json::to_string_pretty(&file)?;
    json.push('\n');
    expect_test::expect_file![path].assert_eq(&json);

    Ok(())
}

/// Build a chat request fixture with parser-enabling tool-choice semantics.
fn roundtrip_request(
    request_id: impl Into<String>,
    messages: Vec<ChatMessage>,
    tools: Vec<ChatTool>,
    tool_choice: Option<ChatToolChoice>,
    thinking: Option<bool>,
    thinking_behavior: ThinkingBehavior,
) -> ChatRequest {
    let tool_context = vllm_chat::ResolvedToolContext::new(&messages, tools, tool_choice, true)
        .expect("tool context should resolve");
    let mut request = ChatRequest {
        request_id: request_id.into(),
        messages,
        tool_context,
        ..ChatRequest::for_test()
    };

    // Explicitly enable or disable thinking using the controls understood by
    // this model's template. If unspecified, use the template default.
    thinking_behavior.apply(&mut request, thinking);

    request
}

/// Return the function tools used by the multiple-tool-call fixture.
fn test_tools() -> Vec<ChatTool> {
    vec![
        ChatTool {
            name: "get_weather".to_string(),
            description: Some("Get weather for a location".to_string()),
            parameters: serde_json::json!({
                "type": "object",
                "properties": {
                    "location": { "type": "string" }
                },
                "required": ["location"]
            }),
            strict: None,
            defer_loading: None,
        },
        ChatTool {
            name: "add".to_string(),
            description: Some("Add two integers".to_string()),
            parameters: serde_json::json!({
                "type": "object",
                "properties": {
                    "y": { "type": "number" },
                    "x": { "type": "number" },
                    "items": {
                        "type": "array",
                        "items": { "type": "string" }
                    }
                },
                "required": ["y", "x", "items"]
            }),
            strict: None,
            defer_loading: None,
        },
    ]
}
