name: build nm-vllm
description: 'build nm-vllm'
inputs:
  python:
    description: 'python version, e.g. 3.10.12'
    required: true
  venv:
    description: 'name for python virtual environment'
    required: true
  pypi:
    description: 'ip address for pypi server'
    required: true
outputs:
  build_status:
    description: "final status from 'pip install -e'"
    value: ${{ steps.build.outputs.build_status }}
  whl_status:
    description: "final status from 'pip3 wheel --no-deps -w dist'"
    value: ${{ steps.build.outputs.whl_status }}
  whl:
    description: 'basename for generated whl'
    value: ${{ steps.build.outputs.whl }}
  tarfile:
    description: 'basename for generated tar.gz'
    value: ${{ steps.build.outputs.tarfile }}
runs:
  using: composite
  steps:
  - id: build
    run: |
      COMMIT=${{ github.sha }}
      VENV="${{ inputs.venv }}-${COMMIT:0:7}"
      source $(pyenv root)/versions/${{ inputs.python }}/envs/${VENV}/bin/activate
      # TODO: adjust when we need a proper release. use nightly now.
      pip3 install -r requirements-cuda.txt -r requirements-build.txt
      # build
      SUCCESS=0
      pip3 install -e . || SUCCESS=$?
      echo "build_status=${SUCCESS}" >> "$GITHUB_OUTPUT"
      if [ ${SUCCESS} -ne 0 ]; then
        exit 1
      fi
      # strip binaries
      if [ ! $(command -v strip) ]; then
          sudo apt install -y binutils
      fi
      if [ ! $(command -v file) ]; then
          sudo apt install -y file
      fi
      for eachso in $(find . -type f -name '*.so')
      do
          strip $eachso
          file $eachso
      done
      # whl
      SUCCESS=0
      pip3 wheel --no-deps -w dist . || SUCCESS=$?
      echo "whl_status=${SUCCESS}" >> "$GITHUB_OUTPUT"
      BASE=$(./.github/scripts/convert-version ${{ inputs.python }})
      ls -alh dist
      WHL_FILEPATH=$(find dist -iname "*${BASE}*.whl")
      RENAME=$(echo ${WHL_FILEPATH} | sed -e 's/linux_x86_64/manylinux_2_17_x86_64/')
      mv ${WHL_FILEPATH} ${RENAME}
      WHL=$(basename ${RENAME})
      echo "whl=${WHL}" >> "$GITHUB_OUTPUT"
      if [ ${SUCCESS} -ne 0 ]; then
        exit 1
      fi
      # sdist
      python3 setup.py sdist || SUCCESS=$?
      pyenv uninstall --force ${{ inputs.python}}/envs/${VENV}
      ls -alh dist
      TAR_FILEPATH=$(find dist -type f -iname "*.tar.gz")
      echo "${TAR_FILEPATH}"
      TARFILE=$(basename ${TAR_FILEPATH})
      echo "tarfile=${TARFILE}" >> "$GITHUB_OUTPUT"
      exit ${SUCCESS}
    shell: bash
