name: build-whl
on:
  # makes workflow reusable
  workflow_call:
    inputs:
      build_label:
        description: "requested runner label (specifies instance)"
        type: string
        required: true
      timeout:
        description: "time limit for run in minutes "
        type: string
        required: true
      gitref:
        description: "git commit hash or branch name"
        type: string
        required: true
      Gi_per_thread:
        description: 'requested GiB to reserve per thread'
        type: string
        required: true
      python:
        description: "python version, e.g. 3.10.12"
        type: string
        required: true

  # makes workflow manually callable
  workflow_dispatch:
    inputs:
      build_label:
        description: "requested runner label (specifies instance)"
        type: string
        required: true
      timeout:
        description: "time limit for run in minutes "
        type: string
        required: true
      gitref:
        description: "git commit hash or branch name"
        type: string
        required: true
      Gi_per_thread:
        description: 'requested GiB to reserve per thread'
        type: string
        required: true
      python:
        description: "python version, e.g. 3.10.12"
        type: string
        required: true

env:
    VENV_BUILD_BASE: "BUILD"
    VENV_WHL_BASE: "WHL-TEST"
    WHL_TEST_RESULTS: "whl-test-results"

jobs:

    BUILD-TEST-WHL:

        runs-on: ${{ inputs.build_label }}
        timeout-minutes: ${{ fromJson(inputs.timeout) }}

        steps:

            - name: checkout
              id: checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
                ref: ${{ inputs.gitref }}
                submodules: recursive

            - name: setenv
              id: setenv
              uses: ./.github/actions/nm-set-env/
              with:
                hf_token: ${{ secrets.NM_HF_TOKEN }}
                Gi_per_thread: ${{ inputs.Gi_per_thread }}

            - name: set python
              id: set_python
              uses: ./.github/actions/nm-set-python/
              with:
                python: ${{ inputs.python }}
                venv: ${{ env.VENV_BUILD_BASE }}

            - name: create testmo run
              id: create_testmo_run
              uses: ./.github/actions/nm-testmo-run-create/
              if: success() || failure()
              with:
                testmo_url: https://neuralmagic.testmo.net
                testmo_token: ${{ secrets.TESTMO_TEST_TOKEN }}
                source: 'build-whl'

            - name: python lint
              id: lint
              uses: ./.github/actions/nm-lint-python/

            - name: build
              id: build
              uses: ./.github/actions/nm-build-vllm/
              with:
                Gi_per_thread: ${{ inputs.Gi_per_thread }}
                python: ${{ inputs.python }}
                venv: ${{ env.VENV_BUILD_BASE }}
                pypi: ${{ secrets.NM_PRIVATE_PYPI_LOCATION }}

            - name: build whl
              id: build_whl
              uses: ./.github/actions/nm-build-vllm-whl/
              with:
                python: ${{ inputs.python }}
                venv: ${{ env.VENV_BUILD_BASE }}

            - name: upload whl
              uses: actions/upload-artifact@v4
              if: success() || failure()
              with:
                name: ${{ steps.build_whl.outputs.whl }}
                path: dist/${{ steps.build_whl.outputs.whl }}
                retention-days: 15

            - name: summary
              uses: ./.github/actions/nm-whl-summary/
              with:
                label: ${{ inputs.build_label }}
                gitref: ${{ inputs.gitref }}
                testmo_run_url: https://neuralmagic.testmo.net/automation/runs/view/${{ steps.create_testmo_run.outputs.id }}
                python: ${{ inputs.python }}
                whl: ${{ steps.build_whl.outputs.whl }}

            - name: complete testmo run
              uses: ./.github/actions/nm-testmo-run-complete/
              if: success() || failure()
              with:
                testmo_url: https://neuralmagic.testmo.net
                testmo_token: ${{ secrets.TESTMO_TEST_TOKEN }}
                testmo_run_id: ${{ steps.create_testmo_run.outputs.id }}
