name: Lint PNG exports from excalidraw
on:
  push:
    branches:
      - "main"
    paths:
      - '*.excalidraw.png'
      - '.github/workflows/png-lint.yml'
  pull_request:
    branches:
      - "main"
    paths:
      - '*.excalidraw.png'
      - '.github/workflows/png-lint.yml'

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: "Run png-lint.sh to check excalidraw exported images"
        run: |
          tools/png-lint.sh
