# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project
from collections.abc import Callable
from typing import Any, Protocol

from vllm.distributed.ec_transfer.ec_connector.cpu.metadata import XferAck, XferReq


class TransferEngine(Protocol):
    def get_agent_metadata(self) -> bytes: ...
    def add_remote_peer(self, metadata: bytes, mem_descriptor: bytes) -> Any: ...
    def remove_remote_agent(self, agent_name: str) -> None: ...
    def add_remote_agent(self, metadata: bytes) -> str: ...
    def post_write(
        self,
        local_xfer_handle: Any,
        local_indices: list[int],
        peer: Any,
        remote_indices: list[int],
    ) -> Any: ...
    def check_xfer_state(self, handle: Any) -> str: ...
    def release_xfer_handle(self, handle: Any) -> None: ...


class ProducerTransport(Protocol):
    def start(
        self,
        on_xfer_req: Callable[[bytes, XferReq], None],
        sweep: Callable[[], list[tuple[bytes, str, bool]]],
        has_in_flight: Callable[[], bool],
    ) -> None: ...
    def stop(self) -> None: ...


class ConsumerTransport(Protocol):
    def get_or_create_peer(self, host: str, port: int, metadata: bytes) -> Any: ...
    def send_xfer_req(self, peer: Any, req: XferReq) -> None: ...
    def drain_acks(self) -> list[XferAck]: ...
    def close_all(self) -> None: ...
