# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project

import torch.fx

from vllm.logger import init_logger

from ..fx_utils import is_func
from ..vllm_inductor_pass import VllmInductorPass

logger = init_logger(__name__)


class InputMutationSlicingPass(VllmInductorPass):
    """
    This pass fixes shape-mismatched in-place mutations (copy_) on graph
    input arguments generated by the compiler.

    When PyTorch compilation detects that the forward function modifies
    input parameters (e.g., inputs_embeds), it inserts an `aten.copy_`
    node at the end of the graph to write the new value back to the
    input tensor.

    In Sequence Parallel (SP) mode, the computation flow is sharded
    while input parameters are full-length. This causes a shape mismatch
    in the compiler-inserted copy_ operations (e.g., scattered residual
    [N/tp, H] vs full placeholder [N, H]).

    Instead of removing these copy_ nodes (which would lose the residual
    value needed for pipeline parallel communication), this pass fixes
    them by slicing the destination placeholder to match the source shape.
    Each TP rank writes its scattered shard to the low portion of the
    placeholder, preserving the mutation for downstream PP communication.

    Example:
    auto_functionalized_321 = auto_functionalized(fused_add_rms_norm, ...)
    getitem_1922: "bf16[(s59//4), 5120]" = auto_functionalized_321[1]
    getitem_1923: "bf16[(s59//4), 5120]" = auto_functionalized_321[2]
    all_gather_default: "bf16[4*((s59//4)), 5120]" = all_gather(getitem_1922)
    copy_: "bf16[s59, 5120]" = aten.copy_(arg1_1, getitem_1923)  # mismatch!
    return (all_gather_default,)

    Is fixed to:
    auto_functionalized_321 = auto_functionalized(fused_add_rms_norm, ...)
    getitem_1922: "bf16[(s59//4), 5120]" = auto_functionalized_321[1]
    getitem_1923: "bf16[(s59//4), 5120]" = auto_functionalized_321[2]
    all_gather_default: "bf16[4*((s59//4)), 5120]" = all_gather(getitem_1922)
    sliced: "bf16[(s59//4), 5120]" = aten.slice(arg1_1, 0, 0, s59//4)
    copy_: "bf16[(s59//4), 5120]" = aten.copy_(sliced, getitem_1923)
    return (all_gather_default,)
    """

    @VllmInductorPass.time_and_log
    def __call__(self, graph: torch.fx.Graph) -> None:
        count = 0

        for node in list(graph.nodes):
            # 1. Find aten.copy_ operations
            if not is_func(node, torch.ops.aten.copy_.default):
                continue

            dst = node.args[0]
            src = node.args[1]

            # 2. Check if dst is a graph input parameter
            if not (isinstance(dst, torch.fx.Node) and dst.op == "placeholder"):
                continue

            dst_val = dst.meta.get("val")
            src_val = src.meta.get("val")

            dst_shape = dst_val.shape if dst_val is not None else None
            src_shape = src_val.shape if src_val is not None else None

            if dst_shape is None or src_shape is None:
                logger.debug(
                    "Metadata missing for %s or %s, skipping...",
                    dst.name,
                    src.name,
                )
                continue

            if dst_shape == src_shape:
                logger.debug(
                    "Skipping copy_ fix for %s <- %s because metadata shapes match: %s",
                    dst.name,
                    src.name,
                    dst_shape,
                )
                continue

            # 3. Fix: slice the destination to match source shape,
            #    writing the scattered shard to the low portion.
            logger.debug(
                "Fixing input mutation copy_ (shape mismatch): "
                "%s (%s) <- %s (%s), slicing dst dim0 to %s",
                dst.name,
                dst_shape,
                src.name,
                src_shape,
                src_shape[0],
            )
            with graph.inserting_before(node):
                sliced_dst = graph.call_function(
                    torch.ops.aten.slice.Tensor,
                    args=(dst, 0, 0, src_shape[0]),
                )
                sliced_dst.meta["val"] = dst_val[: src_shape[0]]

            node.args = (sliced_dst, src)
            count += 1

        if count > 0:
            logger.debug(
                "Fixed %d input mutation copy_ nodes "
                "(sliced dst to match SP shard shape).",
                count,
            )
